electrode-io/electrode-native

- ern-core/src/MiniApp.js
- ern-core/src/utils.js
- ern-local-cli/src/commands/create-miniapp.js
The PR aims at prompting user if MiniApp contains uppercase letters. New packages must not have uppercase letters in the name.
```
$ ern create-miniapp HelloWorld
NPM does not allow package names containing upper case letters.
? Please type package name to publish to npm. Press Enter to use the default. (hello-world)
```
> prompt for a valid npm package name

- package.json
* **Problem:** `npm link` doesn't work because _package.json_’s `bin` entry points to a non-existent file
* **Solution:** Fix `bin` entry
* **Testing:** Try `npm link` in the repo's root (`npm unlink` to undo)
> Remove `bin` from package.json

- package.json
* **Problem:** The package.json lacks some metadata. npm complains:
```
npm WARN ern-platform@0.5.1 No repository field.
```
* **Solution:** Add the metadata!
* **Testing:** Make sure the JSON isn't malformed:
```
node -pe 'require("./package.json")'
```
(Should output JSON and not throw)
> Add metadata to package.json

- ern-local-cli/src/commands/miniapp.js
Remove deprecated `ern miniapp` command. 
This command was still showing up in the command list when running `ern` but command directory did not existed anymore, which was leading in an exception being thrown when trying to run this command.
Thanks @gmbharath12 for reporting
> Remove deprecated miniapp command

- ern-local-cli/src/lib/utils.js
Noticed this while re-booting:
This corrects the loading message typo!
> Correct loading message

- docs/cli/add.md
- ern-local-cli/src/commands/add.js
Improve `ern add` command to allow for user to provide more than one package to add to the MiniApp. Thanks @swashcap 
```
➜  MovieListMiniApp ern add react-native-ernnavigation-api react-native-electrode-bridge react-native-ernmovie-api
✔ react-native-ernnavigation-api is not declared in the manifest. Performing additional checks.
✔ Adding react-native-ernnavigation-api to MiniApp
✔ Adding react-native-electrode-bridge@1.5.9 to MiniApp
✔ react-native-ernmovie-api is not declared in the manifest. Performing additional checks.
✔ Adding react-native-ernmovie-api to MiniApp
```
`package.json` dependencies extract, following command execution :
```
"dependencies": {
"react-native-electrode-bridge": "1.5.9",
"react-native-ernmovie-api": "0.0.9",
"react-native-ernnavigation-api": "0.0.3"
[...]
} …
```
> Update ern add command with multi packages support

- docs/getting-started/getting-started.md
Line formatting on a step in the “Getting Started” doc’s “Implementing the MovieApi on the native side” section is broken:
Add a line break after the first section step.
I didn't know about GitBook’s CLI! It’s neat. Here’s how to preview this edit if you’re interested:
1. Install the GitBook CLI: `npm install -g gitbook-cli`
2. Install project GitBook plugins. Make sure you’re in the `electrode-native` directory:
```shell
gitbook install
```
3. Run `gitbook serve` and open http://localhost:4000/getting-started/getting-started.html
4. Observe fixed formatting!
🎉
> Fix “Getting Started” doc line break.

- global-cli/package.json
- global-cli/src/index.js
Replace `.includes` with `.indexOf` due to the fact that `global-cli` is not transpiled to run on older versions of node and that `.includes` was introduced in ES6/Node6.
> Fix global CLI for node < 6

- ern-container-gen/src/generators/android/AndroidGenerator.js
Fix a bug that was happening during Android Container generation when some third party native modules such as `react-native-vector-icons` are used.
The problem is that Container Generator is trying to process mustache templates in `lib/src/main/assets` which is a bad thing and leads to generation errors if some of the assets (images/fonts) contain some mustache placeholders (`{{{` for ex). 
This commit extends mustache templating exclusion to the `lib/src/main/assets` as we know only assets will be present in this folder and no files to apply mustache templating on.
> Extend mustache templating exclusion to Android assets

- docs/README.md
Use relative paths to markdown files instead of using the documentation absolute web url.
This is the proper way to do it, this way when clicking the links, they are not loaded in new tabs.
> Update links in documentation README

- docs/cli/upgrade.md
- ern-local-cli/src/commands/upgrade-miniapp.js
Renames `upgrade` command to `upgrade-miniapp`
Because this command is only to be used to upgrade MiniApps, it makes its more clear and remove some confusion that it was somehow to "upgrade" ern.
> Rename upgrade command to upgrade-miniapp

- ern-local-cli/src/index.js
Fixes [Issue](https://github.com/electrode-io/electrode-native/issues/101)
We added the support for `ern` CLI to support `--version` flag.
Usage 
```
ern --version
___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v1000.0.0] [Cauldron: -NONE-]
ern-local-cli : 1000.0.0
electrode-native : 1.0.9
```
> Add --version flag to ern command

- ern-local-cli/src/commands/platform/list.js
A a link to the release notes next to each listed platform version when using `ern platform list` command.
Allows to easily go through the release notes of any version by `⌘ + LEFT CLICK` on the link in the terminal.
Also `ern platform list` now don't show the versions pre `0.7.0` as they were test versions, not meant to be installed. Official initial public version release of `Electrode Native` is `0.7.0` so starting from this point.
```
➜  ern platform list
___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v1000.0.0] [Cauldron: benoit]
[CURRENT] [INSTALLED] [NOT INSTALLED]
v0.7.0 …
```
> Add release notes link to ern platform list command

- ern-cauldron-api/src/api.js
- ern-cauldron-api/src/index.js
- ern-core/src/cauldron.js
We won't store binaries in Cauldron anymore, as we are going to rely on a [binary store](https://github.com/electrode-io/electrode-native-binarystore) instead.
This code is therefore deprecated and won't be used anymore. Cleaning it up.
> Remove all binary access from Cauldron

- ern-local-cli/src/commands/cauldron/add/dependencies.js
- ern-local-cli/src/commands/cauldron/add/miniapps.js
- ern-local-cli/src/commands/cauldron/add/nativeapp.js
- ern-local-cli/src/commands/cauldron/del/dependencies.js
- ern-local-cli/src/commands/cauldron/del/miniapps.js
- ern-local-cli/src/commands/cauldron/del/nativeapp.js
- ern-local-cli/src/commands/cauldron/get/config.js
- ern-local-cli/src/commands/cauldron/get/dependency.js
- ern-local-cli/src/commands/cauldron/get/nativeapp.js
- ern-local-cli/src/commands/cauldron/update/dependencies.js
- ern-local-cli/src/commands/cauldron/update/miniapps.js
- ern-local-cli/src/commands/cauldron/update/nativeapp.js
- ern-local-cli/src/lib/Ensure.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/Esnure-test.js
- ern-local-cli/test/utils-test.js
- Add new `isCauldronActive` check to `Ensure` class and use it in `logErrorAndExitIfNotSatisfied` util function. 
- Add appropriate unit tests (also fix some unit tests that were not using chai `throw` in a correct way).
- Add `isCauldronActive` check to all `Cauldron` commands, to ensure that a Cauldron is active before the command is run, and if not, fail with a proper error message.
> Add isCauldronActive check

- ern-core/src/BinaryStore.js
- ern-core/src/ErnBinaryStore.js
- ern-core/src/index.js
Add the `BinaryStore` interface and first concrete implementation of a binary store provider : `ErnBinaryStore`.
A `Binary Store` is a file storage service (hosted on some server) that can be used by `Electrode Native` to store mobile application binaries (APKs for Android, APPs for iOS) and retrieve them on demand.
`ErnBinaryStore` is the client class to access the [Electrode Native Binary Store](https://github.com/electrode-io/electrode-native-binarystore) server. Different binary store client/server implementations might come in the future, but this is the one provided part of `Electrode Native` platform.
Binary stores will be used by some existing react-native commands (`ern start` and maybe `ern run-ios` / `ern run-android`) in order to easily launch the binary associated to any …
> Add BinaryStore and first store implementation ErnBinaryStore

- ern-local-cli/package.json
- ern-local-cli/src/lib/utils.js
- ern-util/package.json
- ern-util/src/index.js
- ern-util/src/ios.js
- ern-util/yarn.lock
Move iOS build/simulator specific code that was present in `local-cli` utils, to new dedicated ios utils in `ern-util` similar to the way we did for android build/emulator specific code.
The utility functions have been lightly refactored and moved to `ios.js` (Android specific utils are kept in `android.js`).
> Extract iOS simulator specific code to new iOS utils

- docs/cli/binarystore/add.md
- docs/cli/binarystore/get.md
- docs/cli/binarystore/remove.md
- ern-core/src/cauldron.js
- ern-local-cli/src/commands/binarystore.js
- ern-local-cli/src/commands/binarystore/add.js
- ern-local-cli/src/commands/binarystore/get.js
- ern-local-cli/src/commands/binarystore/remove.js
Add a few initial commands to work with a Binary Store (storing `.app` and `.apk` files)
- `ern binarystore add` 
To add the binary of a specific mobile application version to the binary store
- `ern binarystore get`
To retrieve the binary of a specific mobile application version from the binary store
- `ern binarystore remove`
To remove the binary of a specific mobile application version from the binary store
More documentation will come soon
> Introduce binarystore commands

- ern-local-cli/src/lib/utils.js
- ern-util/src/android.js
Also to introduce `runAndroidApk` function as an alternative to `runAndroidProject`, to allow installing an Android APK on a simulator/connected device.
> Light refactoring and cleanup of android utils

- ern-container-gen/hull/android/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- ern-container-gen/package.json
- ern-container-gen/src/generateContainer.js
- ern-container-gen/yarn.lock
Per https://github.com/facebook/react-native/commit/5d4c6e5f23e3f7f64576cccff76822d4b7635ab1, `module name` was renamed to `module path` in React Native 0.49 (Android). 
This is a breaking change for Android Container as it is calling `setJSMainModuleName` in `ElectrodeReactContainer.java`, now renamed to `setJSMainModulePath`.
This PR ensure that Android Container generator will generate proper code for React Native >= 0.49, while remaining backward compatible for previous versions of React Native.
This was properly tested using Getting Started guide as reference. Please note that version 0.49 of React Native has also been published to jCenter.
> Update Android containergen for RN 0.49 support

- docs/platform-parts/container.md
Noticed this container docs list isn't formatted right:
Changing to `ol` fixes the issue. Gitbook local preview:
> Fix container configuration documentation's lists display.

- docs/getting-started/getting-started.md
Update getting started guide for current development platform version (soon to be `0.8.0`), following some structural changes introduced in React Native `0.49.0` as well as some `ern` command updates :
- `App.js`, instead of `index.android.js` and `index.ios.js` (reflecting RN 0.49+ file structure change).
- Remove import and invocation of `AppRegistry` as it is now done in `index.android.js` and `index.ios.js` (reflecting RN 0.49+ file structure change).
- Pass all dependencies to `ern add` instead of calling `ern add` three times (reflecting `ern add` command inprovement).
- Other minor rewording and typo fixing.
> Update getting started guide

- ern-cauldron-api/src/api.js
- ern-cauldron-api/src/util.js
- package.json
[boom](https://www.npmjs.com/package/boom) module usage in `cauldron-api` was a left-over of the old Cauldron technology stack (node based service). Only one function left was making use of it, with no real purpose.
The problem also being that `boom` is not declared as a direct dependency of `cauldron-api`, so it was not part of it, making the import fail under some circumstances.
This PR gets rid of `boom` usage in `cauldron-api` and also removes `boom` from our top level platform dev dependencies as it is not used directly anymore, even not in tests.
Fixes https://github.com/electrode-io/electrode-native/issues/171
> Remove usage of boom module in cauldron-api

- package.json
Top level platform `package.json` file is only used for development / lerna flow, as we don't publish this package. 
The version therefore does not really matter here, but for some reason it was set to `0.5.1` for a while, which might be confusing.
This PR is just setting top level `package.json` version to `1000.0.0` which is coherent as it's our dev version number.
> Set top level package version to 1000.0.0

- ern-container-gen/hull/ios/ElectrodeContainer.xcodeproj/project.pbxproj
- ern-container-gen/src/generators/ios/IosGenerator.js
- Remove `FRAMEWORK_SEARCH_PATHS` from ios Container Hull pbxproj (as they will get created by Container generator if needed)
- Add new `addFrameworkReference` directive for plugin injection configuration. It can be used to inject references to Frameworks that are external to the container (i.e Frameworks that might be inside the host application already). For example :
```json
"addFrameworkReference": [
"../../../Modules/WalmartIOSShared/Externals/FacebookSDK/Bolts.framework",
"../../../Modules/WalmartIOSShared/Externals/FacebookSDK/FBSDKCoreKit.framework",
"../../../Modules/WalmartIOSShared/Externals/FacebookSDK/FBSDKLoginKit.framework",
"../../../Modules/WalmartIOSShared/Externals/FacebookSDK/FBSDKShareKit.framework"
]
```
> Add new iOS plugin configuration directive addFrameworkReference

- ern-core/src/MavenUtils.js
- ern-core/src/Platform.js
- ern-local-cli/scripts/postinstall.js
- ern-util/src/config.js
- global-cli/src/index.js
- setup-dev.js
Use Node.js [os.homedir()](https://nodejs.org/api/os.html#os_os_homedir) function to get user home directory (cross-platform), instead of looking for `HOME` environment variable (not cross-platform).
> Use os.homedir() instead of process.env['HOME']

- ern-local-cli/package.json
Current way to declare the `ern-local-cli` postinstall script is not working on Windows. 
This PR fix this for Windows, while remaining compatible with OSX and other platforms.
> Explicitly use node to run ern-local-cli postinstall script

- ern-container-gen/src/utils.js
- ern-local-cli/src/commands/start.js
- ern-local-cli/src/lib/start.js
This PR add support to add extra JavaScript dependencies to the composite MiniApp. 
`start` command is now using this support through a new option `--extraJsDependencies`
This proves to be useful in case some dependencies of the MiniApps that are `dev` only, needs to be part of the Composite. For example, if a MiniApp is making use of `remote-redux-devtools` as a `devDependency`, the dependency won't be part of the Composite by default, due to the fact that only `production` dependencies are installed when generating a Composite. 
With this support, it is now possible to add the dependency to the Composite, if needed.
Example:
```bash
$ ern start \
-n testbinary:android:17.18.0 \
-p com.walmart.android \
-a app.main.MainActivity \
-e remote-redux-devtools@^0.5.7
```
> Add support for generating composite MiniApp with extra JS dependencies

- ern-core/src/MavenPublisher.js
- ern-core/src/MavenUtils.js
- ern-util/src/ReactNativeCli.js
- ern-util/src/android.js
- ern-util/src/findNativeDependencies.js
This pull request adds complete support of `run-android` command on Windows.
`create-miniapp` and `run-android` commands are now both properly working end-to-end on Windows (tested on my Windows workstation). Which in turns means that `runner-gen` and `container-gen` are also properly working on Windows (at least in the basic use case of a starter MiniApp).
Will continue exploring the rest of the commands on Windows and make necessary cross platform adjustments where needed, more pull requests to follow.
> Windows support - Continued

- ern-container-gen/src/generateContainer.js
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/utils.js
Refactoring pass on `ern-container-gen` module to make it more cross-platform friendly. 
Mostly getting rid of the hardcoded literal paths and using `path` cross-platform node module instead.
Also contains a few very light misc improvements.
Has been tested for both iOS and Android using Walmart latest container as a reference..
More PRs will follow to cleanup `ern-container-gen` module.
> Refactor ern-container-gen for better cross-platform support

- docs/cli/cauldron/regen-container.md
- ern-local-cli/src/commands/cauldron/regen-container.js
In addition to what is stated in the documentation of this command below, this command also proves to be quite useful for Electrode Native developers as it allows us (through forking of a reference Cauldron / Containers git repositories) to easily validate medium/heavy refactoring of the Container Generator, by regenerating the Container of a reference native application version and validating that our code changes to the Container Generator did not introduce issues in the generate code (through git diffing of the reference Container version and new one).
> Introduce new Cauldron command regen-container

- ern-api-impl-gen/src/generators/ios/ApiImplGithubGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
The `replaceInFile` plugin injection directive was only replacing the first occurrence of the matched string. 
With this PR, all found occurrences of the string are properly replaced.
> Plugin config injection directive replaceInFile now does a global replace

- ern-container-gen/src/generateContainer.js
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/utils.js
- ern-local-cli/src/lib/publication.js
- ern-runner-gen/src/index.js
- Clean comments (remove a lot of them that were really not needed or just plain wrong).
- Container generator has a dependency on `ern-core` so it can now the platform path from there, no need to provide platform path as a parameter to the generator. This parameter has been removed.
- Update directories paths in `paths` object given to the iOS/Android generators, so that it contains `ios` / `android` path segment. This way the platform generators do no need to always append `ios` or `android` to the provided paths.
> Container generator light refactoring

- ern-api-gen/package.json
- ern-api-impl-gen/package.json
- ern-api-impl-gen/src/generators/android/ApiImplMavenGenerator.js
- ern-api-impl-gen/src/generators/ios/ApiImplGithubGenerator.js
- ern-api-impl-gen/src/index.js
- ern-cauldron-api/package.json
- ern-container-gen/package.json
- ern-core/package.json
- ern-core/src/Manifest.js
- ern-core/src/MavenPublisher.js
- ern-core/src/MiniApp.js
- ern-core/src/Platform.js
- ern-core/src/handleCopyDirective.js
- ern-local-cli/package.json
- ern-local-cli/src/commands/create-container.js
- ern-local-cli/src/lib/publication.js
- ern-local-cli/src/lib/utils.js
- ern-runner-gen/package.json
- ern-runner-gen/src/index.js
- ern-util-dev/package.json
- ern-util/package.json
- ern-util/src/YarnCli.js
- ern-util/src/ios.js
- ern-util/src/spin.js
- Use `path.join` where appropriate instead of hardcoding path
- Do not use template literals when unneeded (i.e `shell.cd(ROOT_DIR)` instead of ```shell.cd(`${ROOT_DIR}`)```)
- Rework `spin` utility function
- Make the spinner instance shared to avoid spinner collisions. Use `spin` instead of relying directly on `ora`, where appropriate.
- Spinner is now disabled in `debug` or `trace` log level as it collides with other logs (bad looking output) and does not add any interesting information.
- `__ERN_TEST__` env variable will be set during test execution. It can be useful in case we want to skip some code or disable some things during test execution (first use part of this PR, to disable the spinners during test execution, as they are not needed)
> Light refactorings

- ern-container-gen/src/generateContainer.js
- ern-runner-gen/src/index.js
* **Problem:** Running a linked ern fails due to hard-coded paths
* **Solution:** Change to package-relative paths
* **Testing:** Not sure as I don't think there's unit/integration tests for the altered modules. Try `ern run-ios` on a project?
> Change container, runner to relative paths

- ern-local-cli/src/commands/run-ios.js
Log an appropriate error message in case `run-ios` command is used on a non Mac OS X machine (Windows or Linux).
> Disable run-ios command for non Mac OS X platforms

- ern-util/src/android.js
The exec command was being wrapped in a promise with the same copy and paste error handling. Created a utility function to promisify the exec command. Used the promisified version of the code to make the exec command processing more concise.
> Promisify exec command

- ern-local-cli/src/commands/create-api-impl.js
Problem : create-api-impl command checks if `{apiName}` exists in npm and prompts user 
Solution : check if {apiName}-impl exists while running create-api-impl and prompt user
> check if {apiName}-impl exists while create-api-impl

- ern-runner-gen/src/index.js
Fixes https://github.com/electrode-io/electrode-native/issues/218
A generated iOS runner project can now be launched from another user workstation
> Replace home path with tidle in iOS runner pbxproj

- ern-util/src/NativeApplicationDescriptor.js
- ern-util/src/index.js
- ern-util/src/noop.js
- ern-util/test/NativeApplicationDescriptor-test.js
- Remove needless use of `noop` function
- Remove `noop` function and exports from `ern-util`
- Add some guard clauses to NativeApplicationDesccriptor constructor
- Add unit tests for NativeApplicationDescriptor class
> Light refactor of NativeApplicationDescriptor class

- docs/cli/run-android.md
- docs/cli/run-ios.md
Update the documentation to match the current state of `run-android` and `run-ios` commands
> Add options to run-android and run-ios documentation

- ern-api-impl-gen/package.json
- ern-api-impl-gen/yarn.lock
- ern-container-gen/hull/ios/ElectrodeContainer.xcodeproj/project.pbxproj
- ern-container-gen/package.json
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/yarn.lock
- Add new `addFrameworkSearchPath` directive
- Improve existing `addProject` directive to allow adding a `Framework` project
- Fix a couple of bugs in iOS container generator
=> Bumped version of `xcode-ern` to `1.0.1` which contain the code needed to support `addProject` improvement.
These changes were made to properly support referencing an external iOS project (with a Framework target) inside the Container, which was needed for proper build of Container with FacebookSDK for Walmart iOS app.
> Improve iOS plugin injection configuration directives

- ern-cauldron-api/src/api.js
- ern-cauldron-api/src/base-git.js
- ern-cauldron-api/src/filestore.js
- ern-cauldron-api/src/gitstore.js
- ern-core/src/cauldron.js
- ern-local-cli/src/commands/cauldron/add/dependencies.js
- ern-local-cli/src/commands/cauldron/add/miniapps.js
- ern-local-cli/src/commands/cauldron/add/nativeapp.js
- ern-local-cli/src/commands/cauldron/batch.js
- ern-local-cli/src/commands/cauldron/del/dependencies.js
- ern-local-cli/src/commands/cauldron/del/miniapps.js
- ern-local-cli/src/commands/cauldron/regen-container.js
- ern-local-cli/src/commands/cauldron/update/dependencies.js
- ern-local-cli/src/commands/cauldron/update/miniapps.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/utils-test.js
Closes https://github.com/electrode-io/electrode-native/issues/227
Since Cauldron transactional support has been introduced, it does not make a lot of sense to keep individual atomic git commit messages for Cauldron in the context of a transaction.
Indeed, for example, adding a MiniApp to a native application is a Cauldron transaction, results in 4 individual commits messages (adding the miniapp, remove previous yarn lock, add new yarn lock, bump container version). This is a bit confusing and too verbose when reviewing a Cauldron git commit history.
This PR refactors Cauldron client so that it does not perform atomic commits during a transaction, but rather issue a single commit when calling `commitTransaction` method.
The `commitTransaction` method now takes the final commit message as …
> Cauldron transactional commits

- package.json
Electrode Native platform rebuild script was not properly cleaning up ern modules dist directories, resulting in some deleted src files in ern modules to remain in the dist directories.
The rebuild script will now remove all dist folders from ern modules before proceeding with lerna clean/bootstrap (that in part regenerates the dist folders).
> Clean all dist directories as part of rebuild script

- auto-rebuild.js
- package.json
- yarn.lock
- Replace `pre-commit` dependency with `husky` to have access to more git hooks
- Add a `postmerge` githook to rebuild platform if needed
This PR improves Electrode Native platform developer experience by automating `yarn install` (if top level platform dependencies have changed) or `npm run rebuild` (if one or more `ern` module dependencies have changed) on every merge (`git pull` does a merge).
> Add git postmerge hook to rebuild platform if needed

- package.json
This section was associated to `pre-commit` dependency that we are not using anymore in favor of husky.
> Remove pre-commit deprecated section in platform package.json

- .travis.yml
- ern-api-gen/src/apigen.js
- ern-api-impl-gen/src/generators/ios/ApiImplGithubGenerator.js
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-local-cli/src/commands/regen-api.js
- system-tests.js
- Rename updatePlugin option in regen-api to skipVersion and update logic accordingly.
- Set process environment variable SYSTEM_TESTS during system tests execution. 
- AndroidGenerator is making use of this to disable Container maven publication during tests (as we are using a NodeJs environment on Travis which does not come with Android SDK). This is temporary.
- Fix ApiImplGitHubGenerator to avoid system test failure due to thrown error.
Improve system tests
- Update .travis.yml file to run system tests as a cron job (daily)
> Improve system-tests

- ern-local-cli/src/commands/create-api.js
`ern create-api react-native-ernmovie-api -s` 
`Generating react-native-ernmovie-api API [object Object]`
> create-api interpolates irrelevant variable

- system-tests.js
- :bug: Fix `create-api` command run by using the `--skipNpmCheck`
- :art: Do not use `=true` for flags
Fix error noticed during daily CI build : https://travis-ci.org/electrode-io/electrode-native/builds/295600105#L3505
Opened https://github.com/electrode-io/electrode-native/issues/268 considering that the test should have failed, but not in this way.
> Fix system-tests

- ern-api-gen/package.json
- ern-api-impl-gen/package.json
- ern-cauldron-api/package.json
- ern-container-gen/package.json
- ern-core/package.json
- ern-local-cli/package.json
- ern-runner-gen/package.json
- ern-util-dev/bin/ern-mocha.js
- ern-util-dev/package.json
- ern-util/package.json
- package.json
- yarn.lock
This PR bring back independent module test run functionality that got lost in a regression. 
It is is now once again possible to run tests of a single `ern` module by running `npm run test` from within the given `ern` module directory.
Quite useful when writing tests for a single `ern` module, avoid having to run all other tests that we don't care about.
`cross-env` dependency was used by the previous methodology, and it was the only usage left of this dependency in Electrode Native. This PR also gets rid of the `cross-env` dependency.
> Allow independent ern module test runs

- docs/cli/create-api-impl.md
- ern-api-impl-gen/src/ApiImpl.js
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-core/src/MiniApp.js
- ern-core/src/utils.js
- ern-local-cli/src/commands/create-api-impl.js
Closes https://github.com/electrode-io/electrode-native/issues/254
* create-api-impl now supports passing `packageName` , `scope`
* underlying logic is adapted
* documentation is updated
> create-api-impl now supports options `packageName` , `scope`

- .gitignore
- ern-api-gen/resources/es6/babelrc.mustache
- ern-util-dev/bin/ern-nyc.js
- package.json
**Description**
This PR fixes the `coverage` script of Electrode Native.
Running `npm run coverage` from the root directory now properly run `coverage` for all `ern` modules and aggregates the coverage result in a single coverage report.
Upon running `npm run coverage`, a `.coverage` directory (git ignored) will be created in each `ern` module directory. Each of these `.coverage` directory will contain the raw json code coverage report of the module. `istanbul-combine` is then called once all `ern` modules have been processed, and will aggregate all individual json reports and output an html report (that will be located in the `coverage` directory of electrode-native root.
**Things done**
- Fix `nyc` / `istanbul-combine` command line arguments
- Require our custom `babel-register` …
> Fix coverage script

- docs/cli/create-api-impl.md
- docs/cli/create-api.md
- ern-local-cli/src/commands/create-api-impl.js
- ern-local-cli/src/commands/create-api.js
- Reword the description of existing command options
- Remove `-s` alias from `--skipNpmCheck` and move it as the `--scope` alias instead
- Properly check for validity of NPM package name
> refactor create-api command

- .travis.yml
- ern-core/test/dummy-test.js
- ern-runner-gen/test/dummy-test.js
- ern-util-dev/bin/ern-nyc.js
- package.json
- yarn.lock
This PR enables unit tests code coverage script execution on TravisCI and report publication to [coveralls](https://coveralls.io/) service.
- Adds a dependency on [node coveralls](https://github.com/nickmerwin/node-coveralls)
- Create a new npm script `coverage-ci` that does sensibly the same things as the existing `coverage` npm script with the difference that it won't create an `html` report but a `text-lcov` report instead that is piped to `coveralls` binary for publication to `coveralls`.
The `coverage` npm script can still be used locally to generate a local html code coverage report.
- Update Travis build configuration, `.travis.yml`, to run `coverage-ci` script after successful execution of tests.
- Adds initial `test` directory to `ern-core` and `ern-runner-gen` modules that were …
> Add coveralls support

- ern-runner-gen/runner-hull/ios/ErnRunner/Info.plist
Set `UIViewControllerBasedStatusBarAppearance` to `false` so that `RCTStatusBarManager` does not cause a red screen when used in some standalone MiniApps.
> Update Info.plist of iOS Runner

- ern-core/src/GitManifest.js
Fixes https://github.com/electrode-io/electrode-native/issues/317
Fix a bug that has already been there but only surfaced with platform version `0.10.0`.
Code was working fine for previous versions `v0.8.0`, `v0.9.0` or even `v1000.0.0` as the version comparison statement was properly evaluated to `true` for the following :
```js
'0.5.0' <= '0.9.0'  // true
'0.5.0' <= '1000.0.0' // true
```
However for `v0.10.0` the string comparison was returning false, leading to the bug.
```js
'0.5.0' <= '0.10.0' // false
```
**Fix :** Do not use string comparison when comparing versions but rather rely on `semver` lib that has proper logic to compare versions.
> Fix manifest platform version filtering

- docs/platform-parts/manifest.md
Typo and list formatting problem on the [manifest docs](http://www.electrode.io/site/docs/introduction.html):
Fix typo, reformat list:
> Manifest documentation fixes

- ern-core/src/iosUtil.js
- ern-util/src/fileUtil.js
* **Problem:** Debugging `ern` CLI commands locally via symlink-ed packages is difficult as certain packages `require` themselves. 
* **Solution:** Change `import`s to reference the modules directly
* **Testing:**
* Set up for debug development
```shell
ern platform use 0.10.0
cd <development electrode-native dir>
npm link
cd ~/.ern/versions/
rm -rf 0.10.0/node_modules
ln -s <development electrode-native dir> node_modules
```
Running `ern --help` should display help output and not explode 💥
* CI should pass?
> Internalize imports

- ern-util/src/ios.js
- ern-util/test/fixtures/instruments-with-device.txt
- ern-util/test/fixtures/instruments.txt
- ern-util/test/ios-test.js
The device chooser doesn't work when running `ern run-ios`:
It turns out that [the device check](https://github.com/electrode-io/electrode-native/blob/2f4cc50a5b3da81c324efd2fc31340e51382a706/ern-util/src/ios.js#L27-L30) now returns the host computer’s `ComputerName`! Very odd, this must be new behavior. Passing the host’s udid causes Xcode to fail: the computer itself isn't a valid iOS build target.
Add a check for the `ComputerName` in `parseIOSDevicesList`. Add some unit tests.
???
(See added unit tests.)
> fix(ern-util): remove false positive in iOS device parsing

- ern-util/package.json
- ern-util/yarn.lock
Bump `code-push` dependency version to [2.0.3](https://github.com/Microsoft/code-push/releases/tag/v2.1.3-beta) (disregard the release version number as the SDK package is versioned differently) that contains the code we need to support Electrode Native code-push integration.
> Bump code-push version

- ern-cauldron-api/src/api.js
- ern-cauldron-api/src/gitstore.js
- ern-cauldron-api/src/schemas.js
- ern-cauldron-api/test/api-test.js
- ern-cauldron-api/test/fixtures/cauldron-fixture.json
- ern-core/src/cauldron.js
- ern-local-cli/src/commands/code-push/release.js
- ern-local-cli/src/lib/publication.js
- ern-util/src/CodePushSdk.js
- Updates the structure of CodePush updates stored in Cauldron as follow :
- `codePush` object is now stored directly inside of the native application version object instead of being nested into the `miniapps` object.
- Instead of storing all CodePush deployments entries in a single array, we now group entries by deployment name (`Production`, `Staging` ...) to make things cleaner and easier to work with from a code perspective.
New format sample :
```json
"codePush": {
"Staging": [
{
"metadata": {
"deploymentName": "Staging",
"isMandatory": false,
"appVersion": "1.0",
"size": 522946,
"releaseMethod": "Upload",
"label": "v7",
"releasedBy": "lemaireb@gmail.com",
"rollout": "100"
},
"miniapps": [
"code-push-test-miniapp@0.0.19"
]
},
{
"metadata": {
"deploymentName": "Staging", …
```
> Update CodePush Cauldron structure

- ern-cauldron-api/src/api.js
- ern-cauldron-api/src/gitstore.js
- ern-cauldron-api/test/api-test.js
- ern-core/src/cauldron.js
- ern-local-cli/src/commands/code-push/patch.js
- ern-local-cli/src/commands/code-push/promote.js
- ern-local-cli/src/commands/code-push/release.js
- ern-local-cli/src/lib/Ensure.js
- ern-local-cli/src/lib/publication.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/publication-test.js
- ern-util/src/CodePushSdk.js
- ern-util/src/NativeApplicationDescriptor.js
- ern-util/test/NativeApplicationDescriptor-test.js
Closes https://github.com/electrode-io/electrode-native/issues/340
Closes https://github.com/electrode-io/electrode-native/issues/341
- Add `code-push patch` command
- Add `code-push promote` command
- Introduce new CodePush configuration at the native application platform level.
- appName : Allow to specify the CodePush application name that is matching the native application stored in the Cauldron. If not specified, the CodePush application name will be the name from the native application descriptor.
- versionModifiers  : Allow to specify modifiers for the CodePush target application version to use. Modifiers are applied per CodePush deployment name. If no modifier is defined for a given deployment name, then the version used will be the version from the native application descriptor. …
> Code push improvements

- ern-core/src/cauldron.js
- ern-local-cli/src/commands/code-push/promote.js
- ern-local-cli/src/commands/code-push/release.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/utils-test.js
Closes https://github.com/electrode-io/electrode-native/issues/303
This PR makes it possible to supply target native application versions to `code-push release` and `code-push promote` commands as a semver expression rather than providing all target versions one by one.
> Add support for semver versions to code-push commands

- ern-local-cli/src/commands/platform/list.js
Fixes https://github.com/electrode-io/electrode-native/issues/377
`ern platform list`
```
[CURRENT] [INSTALLED] [NOT INSTALLED]
v0.7.0		https://github.com/electrode-io/electrode-native/releases/tag/v0.7.0
v0.8.0		https://github.com/electrode-io/electrode-native/releases/tag/v0.8.0
v0.9.0		https://github.com/electrode-io/electrode-native/releases/tag/v0.9.0
v0.10.0		https://github.com/electrode-io/electrode-native/releases/tag/v0.10.0
v0.10.1		https://github.com/electrode-io/electrode-native/releases/tag/v0.10.1
```
> use semver to list version over 0.xx.0

- docs/platform-parts/manifest.md
Line 99, was "Reusing *exiting* native modules". I fixed the typo "exiting" by changing it to "existing".
> Typo in Reusing Existing Native Modules

- ern-core/src/iosUtil.js
Fix `ern-core` import issue that was causing system-tests to fail.
When importing from same module we need to directly refer to the file instead of importing the module.
> Fix ern-core import issue

- ern-core/src/CauldronHelper.js
- ern-core/test/CauldronHelper-test.js
Previous PR changed the logic for `CauldronApi` method `createNativeApp` resulting in CI failing during system-tests.
https://travis-ci.org/electrode-io/electrode-native/builds/311695712
This PR fixes the issue.
> Fix CauldronHelper addNativeApp logic

- ern-util/package.json
- ern-util/yarn.lock
Bump code-push version to [2.1.4](https://github.com/Microsoft/code-push/releases/tag/v2.1.4) to get access to the proper `promote` function implementation.
> Upgrade code-push version

- ern-container-gen/src/generators/ios/IosGenerator.js
Skip plugin injection if it has no injection configuration declared in the manifest plugin configuration.
> Fix a bug in iOS container generator

- ern-container-gen/hull/android/lib/src/debug/AndroidManifest.xml
- ern-container-gen/hull/android/lib/src/main/AndroidManifest.xml
- ern-runner-gen/runner-hull/android/app/src/main/AndroidManifest.xml
As the `container-gen` performs `bundleRelease` , `DevSettingsActivity` will not be merge with the application manifest.
> move DevSettingsActivity to Android Manifest

- ern-container-gen/src/generators/android/AndroidGenerator.js
Because `plugin.origin` was undefined, it was always evaluating the if conditional to false. 
Because we don't yet support non NPM published native dependencies (for ex GIT published) we don't need this check as of now. 
In the context of Walmart, the only native dependency non NPM published (StackTracker) has now been published to NPM, so there is no more issue of executing the code in the if loop for all native dependencies.
> Fix Android generator handling of standalone native API impls

- ern-runner-gen/runner-hull/ios/ErnRunner/ViewController.m
Adapt to iphone x screen when running on iOS version 11 for ErnRunner.
> Add iphone X safelayout support for ERNRunner

- ern-local-cli/src/commands/code-push/release.js
- ern-local-cli/src/lib/publication.js
- Fix a bug that was causing `code-push release` command to fail, because the provided descriptor(s) were handled as strings instead of an array.
- Fix a bug that was causing a `code-push release` command to create atomic Cauldron commits and log an error to the terminal, failing to commit the transaction, due to the fact that no Cauldron transaction was initiated in the first place.
> Code push release related fixes

- ern-local-cli/src/commands/cauldron/add/nativeapp.js
- system-tests.js
Execute 
ern cauldron add nativeapp walmart:android:17.24.0 -c 1000.1000.1
ern cauldron add nativeapp walmart:android:17.24.0 -c appname:android:12.2.2
`TypeError: Cannot read property 'nativeDeps' of undefined`
After Fix 
```
Error: Could not resolve native application version to copy Cauldron data from.
Examine current value : 1000.1000.1```
> handle incorrect copy from version value while adding native app

- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/utils-test.js
- **Add utility function normalizeVersionsToSemver**
This function can be used to normalize provided versions strings, to make sure that they are semver compliant (i.e the versions needs a minor and patch). Please see the test for reference.
- **Improve getDescriptorsMatchingSemVerDescriptor function**
This is somewhat a bug fix rather than an improvement as this function would fail if provided versions that are not semver compliant (for example for descriptor `walmart:android:17.22`, the version `17.22` is not semver compliant and would have caused the function to throw an error). This improvement makes it that all versions are semver normalized (adding minor and/or patch if missing) before to be processed).
> Improvements

- ern-local-cli/src/lib/publication.js
Fix wrong path used for CodePush release that was leading to releasing only the bundle but not the assets.
> Fix a bug in performCodePushOtaUpdate

- ern-util-dev/bin/ern-babel.js
Fix [system tests failure](https://travis-ci.org/electrode-io/electrode-native/builds/328930441#L6960) of past few days on CI.
Because we relocated the container generators hulls inside the `src` folder, these hull files were not properly copied over to the distibution (dist) folder during Babel transpilation. Due to the fact that non dev (release) versions of `ern` are using the distribution directory, the Container generator was unable to locate the missing hulls, leading in a system tests failure on CI but not on local dev version.
To fix this issue, this PR informs Babel CLI, through the [copy-files](https://babeljs.io/docs/usage/cli/#babel-copy-files) option, to copy over all files from `src` to the `dist` folder, and not just source (transpiled) files.
> Use copy-files options of Babel

- docs/GLOSSARY.md
- docs/cli/cauldron/add/miniapps.md
- docs/cli/cauldron/del/miniapps.md
- docs/cli/cauldron/update/miniapps.md
- ern-container-gen/src/utils.js
- ern-core/src/CauldronHelper.js
- ern-core/src/MiniApp.js
- ern-local-cli/src/commands/cauldron/add/miniapps.js
- ern-local-cli/src/commands/cauldron/update/miniapps.js
This PR introduce support in Cauldron/Container Generator for non registry based MiniApp paths.
It makes it possible to add non NPM published MiniApps to a Cauldron and properly generate a container out of it. Due to [current yarn bug with the lock file in case of git dependency paths](https://github.com/yarnpkg/yarn/issues/4734), the lock will not be generated, nor used if one of the MiniApp path is git based.
This feature makes it more convenient for development and CI. For example, one can create a native app `MyAppDev:android:1.0.0` in Cauldron and add MiniApps as git paths to this specific native application name/version. All it takes then to regenerate a new Container including all the latest code changes from all MiniApps is just to run `ern cauldron regen-container -d …
> Add support for non registry MiniApp paths to Cauldron

- system-tests.js
Due to a recent PR merged to master which makes it possible to add MiniApps to the Cauldron given their git or file system path, one of the system test got broken.
This PR just gets rid of this test (new tests dedicated to git/file MiniApp cauldron tests might be introduced in a future PR, this PR is just fixing the current test suite to unblock daily build)
> Fix system tests

- ern-local-cli/src/commands/start.js
- ern-local-cli/src/lib/start.js
- Use `d` alias for the descriptor instead of `n` (this is the convention across commands, even the documentation was stating `d` alias for `start` command. No idea why it was moved to `n`).
- Fix the command. The `start` source file was not using flow (and has no tests) and in consequence did not triggered proper typing errors. Added the `// @flow` header and properly refactored code to use new `PackagePath` type instead of former `DependencyPath`.
> Start command

- docs/cli/link.md
- ern-local-cli/src/lib/start.js
Improve start command by removing the restriction that was requiring the working directory of the MiniApp to be similar in content with the one of the MiniApp shipped in the Composite. 
Close https://github.com/electrode-io/electrode-native/issues/259
> Improve start command

- docs/cli/code-push/promote.md
- ern-core/src/compatibility.js
- ern-local-cli/src/commands/code-push/promote.js
- ern-local-cli/src/lib/publication.js
- Run native dependencies versions compatibility checks for target native application version when using `code-push promote` command. If compatibility checks are failing, the promotion will be aborted (similar to `code-push release`)
- Add the `force` option flag to `code-push promote` command (similar to `code-push release`) which will, if set, discard compatibility checks results and proceed with promotion in any case.
Close https://github.com/electrode-io/electrode-native/issues/451
> Run native compatibility checks for code-push promote command

- ern-cauldron-api/test/CauldronApi-test.js
- ern-container-gen/test/temp-test.js
- ern-core/test/CauldronHelper-test.js
- ern-local-cli/test/Ensure-test.js
- ern-local-cli/test/utils-test.js
- ern-util-dev/src/index.js
While looking at coverage reports I noticed that most of the tests ensuring that exceptions are properly thrown were not actually covering any lines in platform code base.
After further investigation, it appeared that the `doesThrow` and `doesNotThrow` function were not properly implemented. The tests were passing as the calls were actually throwing (in the case of `doesThrow`) exceptions, just not the exception thrown from the proper location. All due to missing `this` context for some calls.
This PR fixes this, we should bring test coverage up a little bit.
> Fix doesThrow and doesNotThrow test utils

- docs/cli/cauldron/del/nativeapp.md
- ern-local-cli/src/commands/cauldron/del/nativeapp.js
Remove the restriction of having to specify a complete native application descriptor for `cauldron del nativeapp` command, so that it is possible -again- to remove all versions of a specific native application platform or to fully remove a native application, along with its platform(s) and version(s) from the Cauldron.
> Update cauldron del nativeapp command

- ern-container-gen/src/generators/android/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
1. Remove static reference to ReactInstanceManager since ReactInstanceManager stores an activity instance and keeping it static might cause memory leaks. 
2. Throw illegal state exception with a proper message if the container is accessed before it is initialized. 
3. Formatting
4. Proper annotations.
5. Proper logging. 
Tested and validated by generating a new container.
> improvements ElectrodeContainer.java

- ern-core/src/nativeDependenciesLookup.js
Root cause due to a recent refactoring of the native dependencies resolution algorithm, which was not properly implemented for Windows (not properly handling the platform difference in file system path format in regex).
Closes https://github.com/electrode-io/electrode-native/issues/504
> Fix run-android on Windows

- docs/cli/create-api.md
- ern-api-gen/src/apigen.js
- ern-api-gen/src/generateProject.js
- ern-local-cli/src/commands/create-api.js
- ern-util-dev/src/index.js
Fixes https://github.com/electrode-io/electrode-native/issues/509
@belemaire Planning to cleanup `shouldGenerateBlankApi` property as it is never used. We do not expose this option any way. Thoughts?
>  create-api uses --schemaPath to accept initial config

- ern-local-cli/src/lib/Ensure.js
`cauldronIsActive` function will now fail if the Cauldron schema version mismatch
> Remove schema version mismatch ignore from caulronIsActive function

- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
Android and iOS generator were not completely properly cleaning the directories used for generation, before starting a new Container generation.
Hidden files (prefixed by `.`) were not removed part of this cleanup, and because of this, Container generation or publication could fail under some circumstances.
This commit ensure that all container generator directories are fully cleaned of all files, including hidden ones.
> Perform full cleanup of Container generator directories before generation

- docs/platform-parts/manifest.md
- ern-core/src/GitManifest.js
For some obscure historic reason, the configuration of scoped plugins had to be stored in the Manifest in a directory name containing the scope and name of the plugin, delimited by a colon.
For example, for `@myScope/myModule`, the convention was to name the directory as `@myScope:myModule` (excluding the extra version suffix). This is problematic for Windows as the colon `:` character is a reserved one on Windows and cannot be present in the name of directories.
This PR keeps backward compatibility with the old way (`:` delimited), while introducing support for a more proper and natural way of dealing with scoped plugins.
It is now possible in the manifest, to keep scoped plugin configurations in a directory named after the scope, and not as a single name delimited with `:`.
i.e :
**OLD …
> Fix manifest scoped plugin config on Windows

- ern-core/src/MiniApp.js
`upgrade-miniapp` command helper function was not properly updated following refactoring to `DependencyPath`, resulting in the function not upgrading any dependency. 
This PR fix the  `upgradeToPlatformVersion` function so that it now properly works again.
> Fix upgrade-miniapp command

- ern-container-gen/src/utils.js
Remove a log that was left-over from a previous refactoring and now misleading/incorrect.
> Remove improper log

- ern-cauldron-api/src/BaseGit.js
It seems like on some systems (Looper VM running CentOS being one where I faced the issue), the `git fetch upstream master` command does not properly work (failing with the following error : `remote: fatal: ambiguous argument 'upstream': unknown revision or path not in the working tree.`.
Might also have noticed the issue a few times in other context.
It is for some reason related to the git CLI invocation itself. The invocation was weird anyway, as a git fetch does not work on a specific branch so to see `master` in the argument was strange in the first place.
Using `git fetch all` is properly working on a looper instance, so it seems like in can properly handle more/all systems.
> Fix BaseGit Cauldron

- ern-cauldron-api/src/CauldronApi.js
- ern-cauldron-api/src/FlowTypes.js
- ern-cauldron-api/src/schemas.js
- ern-cauldron-api/test/CauldronApi-test.js
- ern-core/src/CauldronHelper.js
- ern-core/src/MiniApp.js
- ern-core/test/CauldronHelper-test.js
- ern-local-cli/src/commands/cauldron/add/dependencies.js
- ern-local-cli/src/commands/cauldron/add/nativeapp.js
- ern-local-cli/src/commands/cauldron/batch.js
- ern-local-cli/src/commands/cauldron/del/dependencies.js
- ern-local-cli/src/commands/cauldron/del/jsapiimpls.js
- ern-local-cli/src/commands/cauldron/del/miniapps.js
- ern-local-cli/src/commands/cauldron/del/nativeapp.js
- ern-local-cli/src/commands/cauldron/get/nativeapp.js
- ern-local-cli/src/commands/cauldron/update/dependencies.js
- ern-local-cli/src/commands/cauldron/update/jsapiimpls.js
- ern-local-cli/src/lib/Ensure.js
- ern-local-cli/src/lib/publication.js
- ern-local-cli/test/Ensure-test.js
- Add proper typing (flow) throughout all of `CauldronApi` and `CauldronHelper`
- Throw exceptions in Cauldron API functions for most of the `get` methods in case what is accessed does not exist in Cauldron (instead of returning `undefined`)
- Move `throwIfPartialNapDescriptor` from `CauldronHelper` to `CauldronApi`
- Improve / normalize commit messages
- Lighten CauldronHelper logic. Idea is to get rid of `CauldronHelper` extra logic as much as possible when it is just used as a proxy to `CauldronApi` methods (1 to 1 mapping). `CauldronHelper` should ideally just be an additional layer on top of the `CauldronApi` offering some functions that orchestrate calls to the `CauldronApi`. Going toward this direction.
> Refactor Cauldron

- docs/cli/create-container.md
- ern-local-cli/src/commands/create-container.js
- ern-local-cli/src/lib/publication.js
Closes https://github.com/electrode-io/electrode-native/issues/536
Also removes `version` and `containerName` options from the `create-container` command as they are not used any-longer for creating a container (publication specific options. left-overs from past refactoring).
> Ignore rnpm assets

- ern-core/src/PackagePath.js
Add proper support of Windows file system package paths, to PackagePath class.
This missing support was causing side effects issues such as https://github.com/electrode-io/electrode-native/issues/531
Fix https://github.com/electrode-io/electrode-native/issues/531
> Fix PackagePath for Windows file system paths

- ern-core/src/nativeDependenciesLookup.js
This commit fix the issue that was impacting scoped npm packages use with Electrode Native on Windows.
Scope and name of the package were using an invalid delimiter (`\` instead of `/`) on Windows resulting in failure when Electrode Native was trying to yarn add the package(s).
Fixes https://github.com/electrode-io/electrode-native/issues/548
> Fix a bug impacting scoped npm packages on Windows

- ern-local-cli/src/commands/create-api.js
Fixes #509 
map the property name to the one used to normalize config.
> create-api command passes wrong property name downstream for --schema

- ern-local-cli/src/lib/publication.js
- ern-local-cli/test/publication-test.js
This PR adds similar plugins versions compatibility logic to `runLocalContainerGen` as the one used to work with Containers from a Cauldron.
This fixes the `create-container` command, in the case it was used to create a Container with MiniApps provided on the command line (i.e not create a Container from a Caudron descriptor). In that case, the `create-container` command was not running proper compatibility checks for plugins versions. It was too agressive, in the sense that if any plugin versions were mismatching, the command would throw an error. For example, if two MiniApps, MiniAppA and MiniAppB are both using react-native-my-api at two different versions (1.0.0 and 1.1.0 let's say), then the `create-container` would fail (while when adding MiniApps to Cauldron it would succeed and …
> Improve create-container plugins versions compatibility checks

- docs/cli/publish-container.md
- ern-container-gen/src/FlowTypes.js
- ern-container-gen/src/publishers/MavenPublisher.js
- ern-local-cli/src/commands/publish-container.js
Simplify `publish-container` command for publication to maven local by providing good defaults.
- If `version` is not specified, it will default to `1.0.0`.
- If `url` is not specified, and `maven` publisher is used, the `url` will default to standard maven local path `~/.m2/repository`.
- If maven publisher `config` is not specified, or partially specified, the following default configuration values will be used :
- artifactId: `local-container`
- groupId: `com.walmartlabs.ern`
This way, the following verbose command :
`ern publish-container ~/my-android-container --publisher maven --version 1.0.0 --url file:~/.m2/repository --config '{"artifactId":"local-container","groupId":"com.walmartlabs.ern"}'`
Can be simplified as :
`ern publish-container ~/my-android-container --publisher maven` …
> Default to maven local publication for publish-container maven publisher

- ern-local-cli/src/lib/publication.js
`extraNativeDependencies` provided to `runLocalContainerGen` function were not used at all. 
This was leading to extra dependencies provided to `create-container` command through the `--dependencies` option, not being added to the generated Container.
This PR fixes that.
> Fix extra dependencies handling for local container generation

- ern-core/src/android.js
- ern-core/test/CauldronHelper-test.js
- ern-core/test/fixtures/common.js
Working on making sure that all unit and system tests are passing on Windows to be able to run them consistently before each release.
`ern-core` tests were failing due to an invalid import statement in one of the tests (which for some reason was not causing any issue on Mac/Linux).
Also, 2 android related tests were failing due to the line terminator being encoded differently on Windows (`\r\n` v.s `\n`).
This PR fixes both issues, `ern-core` tests are now passing on Windows.
> Windows fixes

- docs/GLOSSARY.md
make package path terminology consistent with npm & yarn
> make package path terminology consistent with npm & yarn

- docs/overview/dependency-management.md
Command "upgrade" does not exist, I believe you meant "upgrade-miniapp"?
That command is supposed to upgrade used ERN platform, but as a side-effect it also upgrades default supported platform modules, too, which is the issue being discussed here. However that is not enough, if you are using some 3rd party or own custom modules.
> Docs: "upgrade" to "upgrade-miniapp"

- ern-core/src/Platform.js
- ern-local-cli/src/commands/cauldron/repo/add.js
- ern-local-cli/src/commands/cauldron/repo/clear.js
- ern-local-cli/src/commands/cauldron/repo/use.js
- Remove improper hardcoding of path as a string (instead of using `path` module)
- Centralize default cauldron directory path in `Platform` class along with other platform related paths
> Add cauldron default directory to Platform class

- docs/cli/cauldron/add/nativeapp.md
- ern-local-cli/src/commands/cauldron/add/nativeapp.js
Add new value `none` for `copyFromVersion` of `cauldron add nativeapp`
This can effectively be used to disable interactive mode triggered by the `cauldron add nativeapp` command in case no previous native app version copy is desired (otherwise, the only way to discard copy from was through the interactive prompt, which makes things much more difficult for a CI job)
> Add a way to bypass copy from option of cauldron add nativeapp

- ern-container-gen/src/generators/android/hull/lib/src/main/AndroidManifest.xml
- ern-container-gen/src/generators/android/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeMiniAppActivity.java
- ern-container-gen/src/utils.js
Some third-party native components should have custom Android permissions (eg. `android.permission.CAMERA`) on the container's AndroidManifest.xml, so it should be configurable.
Also, it's good practice to implement react-native's `PermissionAwareActivity` so on newer versions of Android, the user will be prompted to accept it on runtime.
> [container-gen] Custom Android permissions configuration for native components

- docs/platform-parts/bridge.md
Layout subtitle "response" in same way as "Request" and "Event" (typo fix)
Also trying to link to part of documentation that was mentioned in this one.
> Docs: link to API docs from Bridge

- docs/platform-parts/apis.md
SUGGESTION:
I like links in documentation, but e.g. this doc is missing them. Maybe you left them out on purpose, because you believe it's better to guide users through "learn the platform basics first" pipeline, before they might get lost into command details and be even more confused.
Anyway, I like links. No problem, if you feel this PR does not improve anything and close it.
> Docs: platform api doc to link to commands

- docs/GLOSSARY.md
- ern-local-cli/src/lib/Ensure.js
Add an explicit sentence to indicate "ElectrodeNative module name" is a GLOSSARY. The original message doesn't show it's a defined glossary in electrode doc. Thus, it takes user's time to figure out why it's a not valid module name.
> Add example to GLOSSARY for ElectrodeNative module name. 

- ern-core/src/CauldronHelper.js
- Fix the command in case no descriptor is explicitly provided as a command option. In that case, the command was failing after selecting the platform with error `An error occurred: Looks like there are no application defined in cauldron for ios`. This was due to naming the argument of `getNativeAppsForPlatform` function as `platform` which was also the name of a local variable used in the function, leading to the issue.
- Remove the break statement so that it does not add the publisher to the first native app returned but in case of multiple native apps present in Cauldron, it will properly ask the user to choose to which native app the publisher should be added to.
> Fix cauldron add publisher command

- ern-local-cli/src/commands/cauldron/add/nativeapp.js
`cauldron add nativeapp` command was failing with error `An error occurred: Cannot read property 'name' of undefined` when the application name/platform was present in the cauldron but no versions were present. 
Could be reproduced through :
- `ern cauldron add nativeapp newapp:android:1.0.0`
- `ern cauldron del nativeapp newapp:android:1.0.0`
- `ern cauldron add nativeapp newapp:android:1.0.0`
Last command would fail with this error.
This PR fixes this fringe scenario.
Thanks @gmbharath12 for reporting this one.
> Fix cauldron add nativeapp

- docs/cli/code-push/promote.md
- ern-cauldron-api/src/FlowTypes.js
- ern-core/src/CauldronHelper.js
- ern-core/test/CauldronHelper-test.js
- ern-local-cli/src/commands/code-push/promote.js
- ern-local-cli/src/lib/publication.js
- ern-util-dev/fixtures/default-cauldron-fixture.json
- Add `--label/-l` option to `code-push promote` command to allow promotion of a release matching a specific label (if option is omitted, will fall back to current behavior of promoting latest release for the given source descriptor / deployment).
- Add `promotedFromLabel` field to the `metadata`object stored in the Cauldron for each promoted release. This is helpful to know which source label is associated to a given promotion entry.
Closes https://github.com/electrode-io/electrode-native/issues/638
> Code push promote label

- ern-core/src/Manifest.js
Very Walmart specific right now, but might be useful for users facing similar fringe scenario. Not documenting this one though for now.
This is too solve an issue with our CI systems that require a token part of the git URL to be accessed. However we don't want this token to be part of the URL visible in the Cauldron, for anyone having access to the Cauldron to see. This token is encrypted and stored on the CI machine, and obfuscated during logging on CI, it should therefore be injected in the URL dynamically.
The only way to do this is through a new local configuration object (`overrideManifestUrlModifier`) that contains two properties  `searchValue` and `replaceValue` that will be fed to `String.prototype.replace` to modify the accordingly override manifest url on the fly before using …
> Offer dynamic modification of manifest url based on local config

- ern-local-cli/src/lib/start.js
Fix an issue causing `start` command to fail in the specific use case when no MiniApps are linked.
> Fix ern start when no MiniApps are linked

- ern-container-gen/src/index.js
- ern-container-gen/src/publishers/JcenterPublisher.js
- ern-container-gen/src/publishers/supplements/jcenter-publish.gradle
- ern-local-cli/src/lib/utils.js
close #490
Support for Jcenter publisher in the cauldron. You can add the following entry inside your cauldron publisher config to enable this feature. 
```
"config": {
"containerGenerator": {
"containerVersion": "1.0.62",
"publishers": [ 
{
"name": "jcenter"
}
]
}
}
```
Once added, make sure to include the following details in your gradle.properties file to have the aar files published to your bintray repository. 
```
bintrayUser=<your-bintray-username>
bintrayApiKey=<your-bintray-apikey>
bintrayRepo=<your-bintray-repo-name>
bintrayVcsUrl=<your-project-repo-url>
```
> add jcenter publisher support.

- ern-runner-gen/runner-hull/ios/ErnRunner/Info.plist
So it won't crash when a plugin tries to use some native feature. See [CocoaKeys](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html) for more info.
As iOS doesn't have a manifest merger feature like Android (Info.plist modifications on framework won't reflect on app), we need to add `NS*UsageDescription` keys to ErnRunner Info.plist (and later, manually on the main app).
> Add a list of all NS*UsageDescription to ErnRunner

- ern-local-cli/src/commands/code-push/promote.js
Seems like a typo (or bad copy/paste) slipped in the code of `code-push promote` command.
This bug was leading to prompting the user to select a source native application descriptor, even if one was explicitly provided to the command through `--sourceNapDescriptor` option (rendering command unusable on CI).
> Fix code-push promote command

- ern-local-cli/scripts/postinstall.js
Fix the function `isGitInstalled` for Windows.
The command was done for Linux/Mac in mind, not Windows. On Windows it was throwing an error, leading to impossibility to properly install Electrode Native.
> Fix git check for Windows

- ern-container-gen/src/generators/android/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
* **Problem:** `ElectrodeReactContainer.Config` settings aren’t honored
* **Solution:** Ensure the `isReactNativeDeveloperSupport` property is set _before_ `ElectrodeReactNativeHost` instantiation reads the value.
* **Testing:** Need help!
> Fix Android container config passing

- ern-container-gen/src/utils.js
Fix `Error: ENOENT, no such file or directory 'package.json'` that was thrown by `ern create-container` command under a certain condition.
This error was happening in case some directory in the parent directories tree of the container generated output directory, was containing a Node Application (a package.json present). In that case, yarn (and npm) behavior is to add the packages at this level (parent directory) and not current directory from where `yarn add` command is being run. Calling `yarn init` from the generated container output directory, before executing `yarn add` commands, ensure that the package.json will be created in the directory from which `yarn add` commands are getting called, thus solving the issue.
> Fix a bug in create-container command

- ern-local-cli/src/lib/utils.js
Fixes https://github.com/electrode-io/electrode-native/issues/639
corner cases resulting in containerVersion out of sync with publisher #639
> corner cases resulting in containerVersion out of sync with publisher 

- docs/cli/cauldron/batch.md
- ern-core/src/CauldronHelper.js
- ern-core/src/MiniApp.js
- ern-core/src/index.js
- ern-core/src/resolveNativeDependenciesVersions.js
- ern-core/test/CauldronHelper-test.js
- ern-core/test/resolveNativeDependenciesVersions-test.js
- ern-local-cli/src/commands/cauldron/add/miniapps.js
- ern-local-cli/src/commands/cauldron/batch.js
- ern-local-cli/src/commands/cauldron/regen-container.js
- ern-local-cli/src/commands/cauldron/update/miniapps.js
- ern-local-cli/src/lib/utils.js
- ern-util-dev/fixtures/default-cauldron-fixture.json
This PR introduces new utility functions and alter the algorithms of the following commands :
```
- cauldron add miniapps
- cauldron update miniapps
- cauldron batch
- cauldron regen-container
```
Without digging into implementation details, the high level change here is regarding proper synchronization of native dependencies stored in the Cauldron for the Container impacted by these commands.
The new algorithm is doing the following :
- List the native dependencies of all the MiniApps that are getting added or updated to/in the Cauldron Container. Also list the native dependencies of all the MiniApps currently in the Container. In a nutshell we just list the native dependencies of all the MiniApps that are going to be listed in the Container once the operation complete.
- For all these …
> Improve native dependencies versions sync in Cauldron

- package.json
- system-tests/fixtures/api/schema.json
- system-tests/fixtures/constants.js
- system-tests/regen-fixtures.js
Add a new script `regen-fixtures` to regenerate one or more system test fixture(s).
It can be launched while on dev version of Electrode Native, by running `npm run regen-fixtures` from the root of the Electrode Native workspace, as illustrated below.
One or more fixtures to regenerate can be selected.
This can be used after doing changes to the code generation output of Container or APIs to ensure that system tests will still pass.
```
➜  npm run regen-fixtures
? Choose one or more system test fixture(s) to regenerate (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◯ android-container
◯ ios-container
◯ api-impl-js
◯ api-impl-native
◯ ComplexApi
◯ TestApi
```
Close https://github.com/electrode-io/electrode-native/issues/611
> Add a script to regenerate system tests fixtures

- docs/cli/cauldron/repo/add.md
- ern-local-cli/src/commands/cauldron/repo/add.js
Close https://github.com/electrode-io/electrode-native/issues/389
Initial idea was to redirect stdin to ask the user for credentials, but it complicates things a lot. Also it can lead to issue when people try to do that on CI. So to make things more robust, the simple solution is just to ensure that users provide the credentials as part of the HTTPS url. 
If users don't want their username/password to be used, they can use a token instead, and still if they don't want that, then they can use an SSH url ;)
> Force authentication details to be part of an https cauldron url

- ern-core/src/CodePushSdk.js
- ern-core/src/index.js
- ern-local-cli/src/lib/publication.js
- ern-local-cli/test/publication-test.js
This PR adds the ability to pass custom configs to codePush SDK. Allowing you to specify your serverUrl for the OTA.
> Code push custom server

- ern-container-gen/src/utils.js
Initial commit to allow user written JS scripts to be executed during container generation, at certain steps of the container generation lifecycle. For now, this commit just allow for running a custom script function after the JS Composite MiniApp is generated.
Electrode Native provide the output directory path of the composite as a parameter to the script function, as well as the yarn object.
This is currently tailored for a specific use case that we need to deal with internally, and not the final implementation. Final implementation will include more hooks such as `beforeNativeContainerGeneration`, `afterNativeContainerGeneration`,`beforeJsCompositeGeneration`, `afterJsCompositeGeneration`, `beforeJsBundling`, `afterJsBundling` ... and will also provide more arguments than just the …
> Add initial custom scripting support for Container generator

- docs/cli/run-android.md
- docs/cli/run-ios.md
- ern-local-cli/src/commands/run-android.js
- ern-local-cli/src/commands/run-ios.js
- ern-local-cli/src/lib/utils.js
- ern-runner-gen/runner-hull/android/app/src/main/java/com/walmartlabs/ern/RunnerConfig.java
- ern-runner-gen/runner-hull/ios/ErnRunner/RunnerConfig.m
- ern-runner-gen/src/index.js
Add `host` and `port` options to `run-ios` and `run-android`.
All that this does for now is to add the `host` and `port` to the generation config source file (`RunnerConfig.java` and `RunnerConfig.m`).
Next step is to update Container code to properly use the specified host and port instead of always using the default (localhost/8081).
Related to https://github.com/electrode-io/electrode-native/issues/688
> Add host and port options to run-ios and run-android

- ern-core/src/nativeDependenciesLookup.js
Issue: 
When trying to add `react-native-permissions` as a plugin, the plugin doesn't get passed to ContainerGenerator. After digging into the code, it turns out the following function returned an incorrect result. This function assumes that a folder that has files end with either .swift or .java is a native module. However, this assumption is not correct as many native module third party plugin is written in objective-c whose file extension is either .h or .m. 
Solution:
add `.h` as a filter because for ios native module, if it's just a .framework, it will have only `.h` file extension. As with `.xcproject` module, it will have both .h and .m file extensions. Thus, add `.h` as filter.
> Add .h to determine if a directory is a native module

- ern-cauldron-api/src/CauldronApi.js
- ern-cauldron-api/src/index.js
- ern-cauldron-api/test/CauldronApi-test.js
- ern-container-gen/src/FlowTypes.js
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/index.js
- ern-container-gen/src/utils.js
- ern-core/src/CauldronHelper.js
- ern-core/src/ReactNativeCli.js
- ern-core/src/index.js
- ern-core/test/CauldronHelper-test.js
- ern-local-cli/package.json
- ern-local-cli/src/lib/publication.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/yarn.lock
Whenever a new Container is generated from a Cauldron, the resulting JS bundle and assets are now zipped and added to the Cauldron, using a filename convention based on the native application descriptor.
For example, when generating a new Container for the following native application descriptor `MyApp:android:1.0.0`, the JS bundle and assets will be zipped, resulting in a zip file named `MyApp:android:1.0.0.zip` which is then stored in the Cauldron, at the root, in the `bundles` directory. Any new Container generation for a given descriptor will generate a new zip file that will overwrite the one stored for this native application descriptor (if any).
This feature isn't really useful on its own but allows for future improvements that will make use of this zip files in the context of …
> Store Container JS bundle and assets in Cauldron

- docs/cli/code-push/promote.md
- docs/cli/code-push/release.md
- ern-local-cli/src/commands/code-push/promote.js
- ern-local-cli/src/commands/code-push/release.js
- ern-local-cli/src/lib/Ensure.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/Ensure-test.js
- ern-local-cli/test/utils-test.js
- For using `targetBinaryVersion` option users must target only 1 descriptor
- For using `targetBinaryVersion` option users cannot use semVerDescriptor
>  pre check if the code push command options are well formed

- docs/getting-started/getting-started.md
Fix `MainActivity.java` from Getting Started guide.
`TAG` is not properly declared in the source file, leading to compilation issue. 
Using harcoded `"NAVIGATION"` String instead of `TAG` (similar to how the other log statement is done a few lines above), to fix issue.
> Fix Getting Started guide for Android

- ern-local-cli/src/lib/utils.js
We don't want this logic of storing the bundle in Cauldron in `v0.17.0` release as it has no use for now and probably not even for future versions, as we are potentially shifting to a different angle of approach for CodePush bundle delta update. So for now, getting rid of this one as it is useless and will consume Cauldron storage for no reason. 
Just removing a single piece of code, while keeping all the support code for bundle storing, as it might turn out to be useful for other purposes.
> Do not store the Container zipped bundle in Cauldron

- .gitignore
- .vscode/settings.json
This way, developers using Visual Studio Code for electrode-native development, will have proper workspace settings applied.
> Add Visual Studio Code workspace settings

- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeBridgeHolder.java
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeBridgeTransceiver.java
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeNativeBridge.java
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/yarn.lock
Update Native API implement system test fixture due to release [1.5.12](https://github.com/electrode-io/react-native-electrode-bridge/releases/tag/v1.5.12) of react-native-electrode-bridge.
This fix the failure reported in [latest nightly build](https://travis-ci.org/electrode-io/electrode-native/builds/374733197).
> Update system test fixture

- ern-container-gen/src/generators/ios/hull/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeBridgeDelegate.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodePluginConfig.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
https://github.com/electrode-io/electrode-native/commit/c97f353086e00aaf1e7676b6b5e314e2e0e12f15 commit broke the iOS Container Generator.
This is because our `pbxproj` parser library is very picky/sensitive and any modification to the `pbxproj` of the Container can potentially cause issues.
When modifying the Container `pbxproj`, it is always a good idea to run the Container Generator system tests through `yarn run system-tests` and selecting only the test `create-container-ios-fixture.js` when prompted. This way one can ensure that Container generation is still properly working.
This PR also updates the iOS Container system test fixture to reflect the latest code changes to the iOS Container introduced in https://github.com/electrode-io/electrode-native/commit/c97f353086e00aaf1e7676b6b5e …
> Fix ios container pbxproj

- ern-container-gen/src/FlowTypes.ts
- ern-container-gen/src/publishers/GithubPublisher.ts
- ern-container-gen/src/publishers/JcenterPublisher.ts
- ern-container-gen/src/publishers/MavenPublisher.ts
- ern-local-cli/src/commands/publish-container.ts
- ern-local-cli/src/lib/publication.ts
- ern-local-cli/src/lib/utils.ts
Light refactoring around Container publishers :
- Remove duplication of publisher factory code (quite similar code in two different source files). Centralize this code in a new function `publishContainer` (in ern-local-cli/publication.js).
- Move logic to copy Container to temporary directory, out of the publishers. It removes some duplicated code in the publishers, and also by doing this upstream, we can guarantee that new publishers (or third party publishers that could be supported soon) will be provided with a duplicated container path instead of the original container path (not to be tampered with).
> Refactor Container publishers

- ern-container-gen/src/FlowTypes.ts
- ern-container-gen/src/publishers/GithubPublisher.ts
- ern-container-gen/src/publishers/JcenterPublisher.ts
- ern-container-gen/src/publishers/MavenPublisher.ts
- ern-local-cli/src/commands/publish-container.ts
- Makes `url` property optional in `ContainerPublisherConfig`. Some publishers might not need an url (for example current JCenter publisher). 
- Add some logging to the publishers.
- Remove validation and default value set in `publish-container` command. It's not the responsibility of the command to do this, but rather the publishers themselves should perform validation and setting default values for config.
> Improve Container publishers

- ern-container-gen/src/generators/android/AndroidGenerator.ts
- ern-container-gen/src/generators/ios/IosGenerator.ts
- ern-container-gen/src/utils.ts
- ern-local-cli/src/commands/create-container.ts
`create-container` command accept an `--outDir/--out` option to specify the output directory for the generated Container.
Container generator performs cleanup of this directory if it exists (it forces remove all files recursively). This is very dangerous as if a user makes a mistake and set output directory to the user home directory for example, the whole user home directory will be destroyed.
To avoid this, `create-container` command will now ensure that in case an output directory is provided, this directory either does not exist yet (will be created) or is empty. Otherwise the command will fail with the following informative error :
```
An error occurred: /Users/blemair/Code/myContainer directory exists and is not empty.
Output directory should either not exist (it will be created) or …
```
> Update create-container command to disallow non empty out directory

- ern-util-dev/bin/ern-typescript.js
- package.json
Transfer responsibility of removing Electrode Native module `dist`directory to the `ern-typescript` script. It makes more sense as it is this script that is producing the `dist` directory in the first place.
> Cleanup dist directory from ern-typescript script

- docs/cli/publish-container.md
- ern-container-publisher/src/publishContainer.ts
- ern-local-cli/src/commands/publish-container.ts
For some reason, Cauldron was using `github` as the name of the publisher whereas the `publish-container` command was expecting `git`. Thanks to a recent refactoring, container publication got centralized and is not all over the place so let's use same naming for the `GitHubPublisher` as `github` (makes more sense than `git` given the naming of the class).
> Rename git publisher to github

- ern-api-impl-gen/package.json
- ern-api-impl-gen/src/generators/ApiImplGen.ts
- yarn.lock
This PR fix a bug that was reported by daily job system tests failure.
A bug was recently discovered and fixed in GitManifest (comparing versions as strings instead of using semver lib) : https://github.com/electrode-io/electrode-native/commit/2e7d23272db2c0783654b921850ce68c6c0f3300#diff-2fde8a8f6c7fa832045033cb61368189L203
Fixing this bug actually uncovered another issue/bug in api-impl-gen.
The problem is that api-impl-gen is installing the api dependency along with its dependencies. APIs have a dependency on bridge, but not on a fixed version of bridge, rather a range (`1.5.x`). `yarn add` call goes fine with such a range dependency but at some point in GitManifest, when asking for the plugin configuration, the manifest resolver fails on the call to `semver.gte` as this function is …
> Fix issue in api-impl-gen related to bridge version range

- yarn-lock-check.js
Given that we are now using [Yarn Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) there is no longer a need to check for validity of modules lock files because due to the nature of yarn workspaces, there is just one top level lock file and no module lock files. 
From Yarn Workspaces documentation :
> Yarn will use a single lockfile rather than a different one for each project, which means less conflicts and easier reviews.
This PR updates yarn-lock-check script so that it doesn't look for lock files in modules directories and just check the validity of the top level project lock file.
> Update yarn-lock-check script

- system-tests/fixtures/api-impl-js/ReactNativeErnmovieApiImplJs/package.json
- system-tests/fixtures/api-impl-js/ReactNativeErnmovieApiImplJs/yarn.lock
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/util/BridgeArguments.java
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeBridgeHolder.h
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeBridgeHolder.m
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeBridgeProtocols.h
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeBridgeTransceiver.m
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeEventRegistrar.h
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeEventRegistrar.m
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeRequestHandlerProcessor.swift
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeRequestProcessor.swift
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeRequestRegistrar.h
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeRequestRegistrar.m
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/EventListenerProcessor.swift
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/EventProcessor.swift
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/Processor.swift
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/yarn.lock
- system-tests/fixtures/api/ComplexApi/IOS/SysteTestEventAPI.swift
- system-tests/fixtures/api/ComplexApi/IOS/SysteTestEventEvents.swift
- system-tests/fixtures/api/ComplexApi/IOS/SysteTestEventRequests.swift
- system-tests/fixtures/api/ComplexApi/IOS/SystemTestsAPI.swift
- system-tests/fixtures/api/ComplexApi/IOS/SystemTestsRequests.swift
- system-tests/fixtures/api/ComplexApi/package.json
- system-tests/fixtures/api/TestApi/IOS/WalmartItemAPI.swift
- system-tests/fixtures/api/TestApi/IOS/WalmartItemEvents.swift
- system-tests/fixtures/api/TestApi/IOS/WalmartItemRequests.swift
- system-tests/fixtures/api/TestApi/package.json
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
Regen iOS fixtures following bridge [v1.5.15](https://github.com/electrode-io/react-native-electrode-bridge/releases/tag/v1.5.15) release, containg iOS native code changes, and https://github.com/electrode-io/electrode-native/pull/762 updating iOS API generator.
> Regen iOS system test fixtures

- .prettierignore
Don't want Prettier to mess with json files formatting, especially package.json, so disabling it for json files.
> Disable Prettier for json files

- .travis.yml
- package.json
- Use npm groups to group related scripts together (following best practices).
- Sort package.json scripts alphabetically for better coherence (grouping) and readability.
- Make all scripts as one liners for better readability (thanks to be prettier being now disabled for json files)
> Clean package.json scripts

- package.json
Update glob pattern for tslint exclude from `node_modules/**`  to `**/node_modules/**`, ensuring that we properly exclude all node_modules directories and not just the top level one.
> Update tslint excludes

- ern-cauldron-api/src/getActiveCauldron.ts
Before this change, `getActiveCauldron` was assuming that the current Cauldron could not be changed at runtime. It was caching the Cauldron instance once created and returning this cached instance event if the current active Cauldron repo was changed.
This was OK because no commands were changing the current cauldron at runtime, but for more advanced sessions, this is an issue (for example for a desktop app, the session might run for a long time and the user might switch between Cauldrons at runtime). 
This code update still cache the Cauldron instance, but if the user choose a different Cauldron repository at runtime, a new Cauldron instance will be properly created.
> Improve getActiveCauldron function

- ern-container-gen/src/FlowTypes.ts
- ern-container-gen/src/utils.ts
- ern-core/src/NativeApplicationDescriptor.ts
- ern-core/src/NativePlatform.ts
- ern-core/src/index.ts
- ern-local-cli/src/commands/code-push/promote.ts
- ern-local-cli/src/commands/code-push/release.ts
- ern-local-cli/src/commands/create-container.ts
- ern-local-cli/src/lib/publication.ts
- ern-local-cli/src/lib/utils.ts
**Add NativePlatform type**
We were using type `'android' | 'ios'` in multiple locations in the code to type variables representing a platform.
Multiple problems with this approach :
- Duplication
- Prone to error (mistyping)
- Painful if ever a new native platform is supported
Therefore, moving this one as a dedicated type `NativePlatform` in `ern-core`.
Let's make sure that everywhere we see a variable holding a native platform name in the code, we use this type rather than plain old `string` type (primitive type obsession anti-pattern). In this PR I just replaced all locations where `'android' | 'ios'` (or reverse) were used. I did not took care of the one variables that are using `string` (harder to locate).
**Add more properties to Container metadata**
Add the following properties to …
> New NativePlatform type and Container metadata enhancement

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/schemas.ts
- ern-cauldron-api/src/types.ts
- ern-local-cli/src/lib/utils.ts
Store the ern version that was used to generate a Cauldron Container as `ernVersion`.
No usage in Electrode Native -yet-, just to document in Cauldron the version used to generate a Container, to help troubleshoting.
> Store ern version along with Container in Cauldron

- docs/cli/platform/install.md
- docs/cli/platform/use.md
- ern-core/src/Platform.ts
- ern-local-cli/src/commands/platform/install.ts
- ern-local-cli/src/commands/platform/use.ts
- `latest` can now be used as the `version` provided to the `platform use` and `platform install` commands.  It will pick the latest available version of Electrode Native (convenient for users who don't want to check the available versions before using these commands, but just want to update to the most recent version of Electrode Native).
- These commands will now gracefully fail with a proper error message in case the `version` used is not a valid version.
- If a version is valid but not available, the `platform use` command now properly logs the `non available version` only (prior to this PR, the `ern v${version} is not installed yet. Installing now.` was logged before failing with `non available version`, which was confusing.
- **Internal** : Remove the need to do a string replacement …
> Introduce latest version for platform use and install commands

- docs/cli/cauldron/repo/add.md
- ern-cauldron-api/src/BaseGit.ts
- ern-cauldron-api/src/CauldronApiFactory.ts
- ern-cauldron-api/src/GitDocumentStore.ts
- ern-cauldron-api/src/GitFileStore.ts
- ern-cauldron-api/src/getActiveCauldron.ts
- ern-core/src/Platform.ts
- ern-local-cli/src/commands/cauldron/repo/add.ts
- Add support for local Cauldrons :
- Local Cauldrons are just local git repositories
- They are stored in `~/.ern/local-cauldrons`
- Can be created through `ern cauldron repo add <alias> local`
- Way faster than remote Cauldrons as there is no need to sync with the remote or perform push
- Can be used for different use cases, one being to try out Electrode Native with Cauldrons without the need to create a remote git repository (ease training).
If thinking of Cauldrons as being workspaces, an Electrode Native user can choose to have one or more local workspace(s) (local Cauldron(s)) and one or more shared team workspace(s) (remote Cauldron(s)).
- Refactor some function signatures so that we pass an object to them rather than multiple parameters. We should favor passing objects to …
> Introduce local Cauldrons

- docs/getting-started/getting-started.md
- system-tests/fixtures/constants.js
In preparation of Electrode Native v0.19.0 release, published new versions of the following MiniApps (bumping React Native from `0.55.3` to `0.55.4`.
`moviedetailsminiapp` from `0.0.19` to `0.0.20`
`movielistminiapp` from `0.0.19` to `0.0.20`
Updated system tests and getting started guide to use these new versions.
> Update MiniApp versions for system tests and getting started

- ern-api-impl-gen/src/ApiImpl.ts
- ern-api-impl-gen/src/generators/ApiImplGen.ts
- ern-container-gen/src/copyAndroidRnpmAssetsFromMiniAppPath.ts
- ern-container-gen/src/copyIosRnpmAssetsFromMiniAppPath.ts
- ern-container-gen/src/generateMiniAppsComposite.ts
- ern-container-gen/src/populateApiImplMustacheView.ts
- ern-core/src/MiniApp.ts
- ern-core/src/fileUtil.ts
- ern-core/src/index.ts
- ern-core/src/packageJsonFileUtils.ts
Introduce `packageJsonFileUtils.ts` in `ern-core` module, exporting the following helper functions :
- `readPackageJson`
- `readPackageJsonSync`
- `writePackageJson`
- `writePackageJsonSync`
Replace code that was reading/writing to package.json file with these functions, removing some duplication.
Lightly refactor `fileUtil.ts` by the same occasion.
> Move common package.json access code to dedicated functions

- ern-container-gen/package.json
Remove instruction to copy some publishers related files for distribution, given that these files are not present in `ern-container-gen` module anymore (following publishers extraction refactoring).
> Clean ern-container-gen package.json

- ern-container-gen/src/generateMiniAppsComposite.ts
If multiple miniapps have a `package.json` babel config, only the first miniapp's config gets used. This is happening because of `for ... in` instead of `for ... of` on the `babelPlugin` array.
> Iterate babel resolver plugin config correctly for multiple miniapps

- ern-container-publisher/src/publishContainer.ts
- ern-container-publisher/src/types/ContainerPublisher.ts
- ern-container-publisher/src/types/ContainerPublisherConfig.ts
- ern-container-publisher/src/types/index.ts
Quick refactoring to extract types from `types.ts` in `ern-container-publisher` and move each type as an independent `.ts` file in a new `types` directory (following similar design as for `ern-container-generator). Should soon follow up with other modules as well.
This is better to hold one type per file (with filename being type name). Leaner and cleaner but also helps when looking for a specific type as it is more convenient to do a file search (one result) vs a file content search (which can yield many results -everywhere type is being used-).
> Extract Container Publisher types

- ern-api-impl-gen/package.json
- ern-container-gen-ios/package.json
- ern-container-gen/package.json
- ern-core/package.json
- ern-core/src/Manifest.ts
- ern-core/src/iosUtil.ts
- yarn.lock
- Bump `xcode-ern` dependency version to `1.0.3` which implements the logic for supporting this new option flag.
> Add new option addAsTargetDependency to iOS addProject plugin directive

- docs/cli/publish-container.md
- ern-local-cli/src/commands/publish-container.ts
This PR update the `publish-container` command to make it more consistent with its alter ego `create-container`
- Remove mandatory `containerPath`. It is now an option. If not specified, the default path will be Electrode Native default container path (`~/.ern/containergen/out/[platform]`). This makes the command consistent with `create-container` which takes an option `outDir`, being the path where to generate the Container and if not specified will fallback to default Electrode Native container generation directory.
- Add `platform` option. This is needed because of `containerPath` being now optional. If no `containerPath` is specified, then the command needs to know which container path to use (basically `../out/android` or `../out/ios`). Good thing is that the `create-container` also …
> Update publish-container command

- ern-api-gen/.npmignore
- ern-api-impl-gen/.npmignore
- ern-cauldron-api/.npmignore
- ern-container-gen-android/.npmignore
- ern-container-gen-ios/.npmignore
- ern-container-gen/.npmignore
- ern-container-publisher-jcenter/.npmignore
- ern-container-publisher-maven/.npmignore
- ern-container-publisher/.npmignore
- ern-core/.npmignore
- ern-local-cli/.npmignore
- ern-runner-gen/.npmignore
Noticed that all of our Electrode Native packages published to NPM contain a lot of things that are not needed (such as `src` directory or `test` directory or even test coverage directories). 
This PR adds a `.npmignore` file to each Electrode Native package, so that all the non necessary things are not included in the npm package. This reduces the size of of Electrode Native packages, thus reducing overall size of Electrode Native installed versions and also potentially speeding up install (might not really be noticeable though, given that Electrode Native packages contribute maybe to 1% of overall packages size when accounting for node modules dependencies).
Please note that the `src` directory is excluded (`dist` -transpiled code- is the one that is included and needed at runtime), …
> Add npmignore to Electrode Native packages

- ern-local-cli/package.json
- ern-local-cli/src/commands/platform/config.ts
- yarn.lock
- The command now logs the available configuration keys in the command help :
```
➜ ern platform config
[v1000.0.0] [Cauldron: -NONE-]
ern platform config <key> [value]
Options:
--help  Show help                                                                                                                                                                                                       [boolean]
The following configuration keys are available :
logLevel        : Set the log level to use for all commands                     [trace|debug|info|error|fatal]
showBanner      : Show the Electrode Native banner when running commands        [true|false]
tmp-dir         : Temporary directory to use during commands execution          [string]
retain-tmp-dir  : Do not remove temporary directories …
```
> Improve platform config command

- ern-core/src/Platform.ts
- ern-core/src/config.ts
- global-cli/package.json
- global-cli/src/index.js
- global-cli/yarn.lock
Through `ERN_HOME` environment variable.
This is useful in a few contexts but mostly for CI env, as it allows to keep the whole `.ern` directory under the job workspace.
> Allow arbitrary directory for ern root

- ern-cauldron-api/src/CauldronApi.ts
Top level Container version is stored at the platform level, not at the native app version level.
This gets rid of unnecessary code and prevent potential bugs.
> Fix update of top level container version

- ern-core/package.json
- ern-core/src/FsCache.ts
- ern-core/src/MiniApp.ts
- ern-core/src/Platform.ts
- ern-core/src/index.ts
- ern-core/src/packageCache.ts
- ern-core/src/utils.ts
- ern-core/test/FsCache-test.ts
- ern-local-cli/src/commands/platform/config.ts
- yarn.lock
This PR introduces a simple caching mechanism to cache packages used during Container generation (MiniApps, APIs & APIs implementations, native modules).
As a baseline, for a big sample production Container, if not changing anything in the Container but just calling `cauldron regen-container`, time to generate a Container goes from ~10min to ~6min (~40% decrease). This is the ideal scenario, with all packages versions being cached. 
Speed gains decrease linearly with the number of non-cached packages versions.
The cache has a default size of 2GB (for this big sample production Container, all packages at a specific version represent ~1GB, so this leaves us room to cache a few different versions). The package cache max size is configurable through `platform config max-package-cache-size`. …
> Cache packages to boost Container generator speed

- ern-local-cli/src/commands/code-push/patch.ts
- ern-local-cli/src/commands/code-push/promote.ts
- ern-local-cli/src/commands/code-push/release.ts
To avoid this kind of cryptic error messages :
```
$ ern code-push patch -l v2 --deploymentName Production -r 10
[v0.20.0] [Cauldron: -NONE-]
An error occurred: Cannot read property 'getAllNativeApps' of undefined
```
```
$ ern code-push patch -l v2 --deploymentName Production -r 10 --descriptor test:android:3.7.0
[v0.20.0] [Cauldron: -NONE-]
✖ Cannot read property 'isDescriptorInCauldron' of undefined
An error occurred: Cannot read property 'isDescriptorInCauldron' of undefined
```
> Fail code-push commands if there is no active cauldron

- ern-container-publisher-git/src/index.ts
- ern-container-publisher-jcenter/src/index.ts
- ern-container-publisher-maven/src/index.ts
- ern-container-publisher/src/publishContainer.ts
- ern-container-publisher/src/types/ContainerPublisherConfig.ts
Add `ernVersion` to `ContainerPublisherConfig` type.
This way, publishers modules can know the version of Electrode Native in use and react accordingly if they don't support the version, or need to handle things differently based on the version of Electrode Native.
Also cleanup some unused imports.
> Add ernVersion to Container Publisher config

- docs/cli/publish-container.md
- ern-local-cli/src/commands/publish-container.ts
Allow `--config/-c` value to be the path to a json file holding the publisher configuration.
Given that publishers configuration are relatively light -as of current publishers-, this is not really needed. 
That being said, the `transform-container` upcoming command will be very similar in term of options to the `publish-container` command, and transformers config can be quite large, making it more convenient to be stored in a file rather than provided on the command line. If the config of `transform-container` can be provided as a file, so should the config of `publish-container`, for command options consistency.
> Allow config from file for publish-container command

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronApiFactory.ts
- ern-cauldron-api/src/EphemeralFileStore.ts
- ern-cauldron-api/src/GitFileStore.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
Instead of having to work with multiple `GitFileStore` instances, one for each top level directory (`yarnlocks`, `bundles` ..), only keep a single `GitFileStore`, not bound to a specific directory.
This makes things leaner, easier and more flexible as there is no more need to update the `ern-cauldron-api` module to add a new file store directory to Cauldron. 
Before this change, if a new store directory was needed in Cauldron, one would need to instantiate a new `GitFileStore` and update the constructor of `CauldronApi` to pass this file store. Also would need some work in `CauldronApi` class.
For now there is no methods exposed on `CauldronApi` class to create and access arbitrary store directories. This work will be done in a different PR.
This refactoring and subsequent work around …
> Improve Git file store

- ern-container-transformer/.npmignore
- ern-container-transformer/README.md
- ern-container-transformer/package.json
- ern-container-transformer/src/getTransformer.ts
- ern-container-transformer/src/index.ts
- ern-container-transformer/src/transformContainer.ts
- ern-container-transformer/src/types/ContainerTransformer.ts
- ern-container-transformer/src/types/ContainerTransformerConfig.ts
- ern-container-transformer/src/types/index.ts
- ern-container-transformer/tsconfig.release.json
- ern-core/src/Platform.ts
Very similar approach and code as for `ern-container-publisher`.
Will generalize most of the code of these two packages through refactoring at some point.
There is only one transformer currently available (in dev only, not published to npm yet) : the [iOS Build Config Transformer](https://github.com/electrode-io/ern-container-transformer-build-config)
Potential transformers to follow : Script / iOS Project.
Also might have some transformers for Android Containers at some point (to patch dependencies versions, or other utilities).
`transform-container` command will be introduced in a different PR.
Same goes for Cauldron support.
> Introduce ern-container-transformer package

- ern-local-cli/src/commands/platform/config.ts
whitelist codePushAccessKey as a valid config
`ern platform config codePushAccessKey YOUR_CODE_PUSH_ACCESS_KEY` results in 
```An error occurred: Configuration key codePushAccessKey does not exists. Did you mean logLevel ?```
> Whitelist codePushAccessKey as a valid config key

- docs/cli/publish-container.md
Remove `-p` alias for `--platform` as it is already used for `--publisher`
> Fix publish-container documentation

- ern-local-cli/src/commands/cauldron/add/publisher.ts
- ern-local-cli/src/commands/publish-container.ts
- ern-local-cli/src/commands/transform-container.ts
- ern-local-cli/src/lib/utils.ts
Rename `--config/-c` option of `publish-container`/`transform-container` and `cauldron add publisher` commands, to `--extra/-e` for consistency with the name of the object (`extra`) stored in Cauldron or passed programmatically to `publish` / `transform` methods.
Also, for consistency as well, allow `--extra/-e` to be a path to a file containing the extra configuration, for the `cauldron add publisher` command (to be on par with `publish-container` and `transform-container` commands).
**For release notes : This is a breaking change to the following commands**
- publish-container
- transform-container
- cauldron add publisher
**After release task**
- Update the README of the publishers and transformers accordingly.
> Update publisher and transformer extra config option name

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/EphemeralFileStore.ts
- ern-cauldron-api/src/GitFileStore.ts
- ern-cauldron-api/src/types/ICauldronFileAccess.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-core/src/fileUtil.ts
- ern-local-cli/src/commands/cauldron/add/file.ts
- ern-local-cli/src/commands/cauldron/del/file.ts
- ern-local-cli/src/commands/cauldron/update/file.ts
Add support to store arbitrary files in Cauldron. 
This PR introduces three new cauldron subcommands :
- `ern cauldron add file`
- `ern cauldron update file`
- `ern cauldron delete file`
For example, running `ern cauldron add file /Users/username/test.json data/json/test.json` will add the `test.json` in the Cauldron in the `data/json` directory from the root of the Cauldron (creating the directori(es) if needed).
First use case for this will probably be to store publishers and/or transformers configurations (as transformers configurations can grow quite big and bloat main cauldron document, also better to keep them separate for easier management). Also for example the planned `script` transformer will allow the execution of arbitrary scripts which can get quite big (fat-binary for iOS …
> Cauldron file system

- ern-container-gen-android/.npmignore
`.npmignore` was configured to ignore all `src` directories instead of top level `src` directory only.
This caused a big issue for Android Container Generator, as the Java hull code is kept in a directory named ... `src`. 
This hull src directory was therefore not packaged, leading to failure during Android Container Generation.
> Fix ern-container-gen-android .npmignore

- ern-local-cli/src/lib/utils.ts
Because Container publisher name can include a specific version of the publisher, fix a bug that was not setting the default config in the later case, as it was just checking for the exact publisher name and not a publisher name with a specific version set.
i.e if the publisher name is set to `maven` in Cauldron, default maven publisher config is properly set. However if publisher name is set to `maven@1.0.0` then default maven publisher config was not applied.
> Fix default config values for Cauldron publishers

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/index.ts
- ern-cauldron-api/src/util.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/util-test.ts
Update Cauldron file access functions to support Cauldron file paths prefixed by new `cauldron://` file uri scheme.
This allows to build new features that can reference files stored in Cauldron using the `cauldron://` scheme, to properly distinguish a path to a file stored in Cauldron v.s a local file path. 
i.e `cauldron://dir/file.json` is the path to a file named `file.json` located in the `dir` directory in Cauldron, whereas `dir/file.json` indicate a local path to a file name `file.json` in the `dir` directory relative to the current pwd.
> Add cauldron file uri scheme support

- ern-local-cli/src/lib/Ensure.ts
- ern-local-cli/src/lib/utils.ts
- ern-local-cli/test/Ensure-test.js
- ern-local-cli/test/utils-test.js
Add the following new guard functions to `Ensure` / `logErrorAndExitIfNotSatisfied` :
- `pathExist` (check if a given path exists)
- `isFilePath` (check if a given path is a path to a file)
- `isDirectoryPath` (check if a given path is a path to a directory)
Can be used in a few places but will be use to improve recent new commands `cauldron add file` / `cauldron update file`, in a separate PR.
> Add a few new guard functions

- docs/cli/cauldron/add/publisher.md
- docs/cli/publish-container.md
- docs/cli/transform-container.md
- ern-local-cli/src/commands/cauldron/add/publisher.ts
- ern-local-cli/src/commands/publish-container.ts
- ern-local-cli/src/commands/transform-container.ts
- ern-local-cli/src/lib/utils.ts
Update the following commands 
- `cauldron add publisher`
- `publish-container`
- `publish-transformer`
so that the publisher/transformer extra config can be a path to a configuration file stored in Cauldron (using the `cauldron://` file uri scheme).
Update documentation of these commands.
> Extra config from cauldron file

- ern-container-gen-ios/src/hull/ElectrodeContainer.xcodeproj/xcshareddata/xcschemes/ECDevice.xcscheme
This scheme is needed for the Fat Binary script which will be moved to a transformer soon.
It is duplicated from the ElectrodeContainer scheme with the difference that the default run configuration is release (instead of debug).
iOS system tests fixture donot need to be regenerated (ran iOS Container system tests locally without any issue).
> Add ECDevice scheme to iOS Container

- ern-api-impl-gen/package.json
- ern-container-gen-ios/package.json
- ern-container-gen/package.json
- ern-core/package.json
- ern-core/src/Manifest.ts
- ern-core/src/iosUtil.ts
- yarn.lock
This is needed for Fat Binary proper support and is also more handy for some other use cases.
This feature requires `xcode-ern` version `1.0.8`, so the version of this dependency has been adequately bumped.
> Expose API swift files as public headers in ElectrodeContainer

- docs/cli/platform/config/set.md
- ern-core/src/config.ts
- ern-local-cli/src/commands/platform/config/set.ts
- ern-local-cli/src/lib/Ensure.ts
- ern-local-cli/src/lib/utils.ts
- ern-local-cli/test/utils-test.js
unit test for platform config command and refactor
- make `<value>` mandatory
- refactor logic for checking validity of whitelisted `key` to `Ensure`
- unit test supported `config` & test for unsupported key
> unit test for platform config command and refactor

- ern-local-cli/src/index.ts
Turn `shelljs` silent for all log levels but `trace` and `debug`, to make sure that log output is not polluted for common user log levels.
This gets rids of the annoyings 
pwd
pwd
that were logged when running commands with the default info log level.
> Make shell silent for some log levels

- ern-api-gen/package.json
- ern-api-gen/src/CodegenOperation.js
- ern-api-gen/src/DefaultCodegen.js
- ern-api-gen/src/DefaultGenerator.js
- ern-api-gen/src/auth/AuthParser.js
- ern-api-gen/src/java/TreeMap.js
- ern-api-gen/src/java/javaUtil.js
- ern-api-gen/src/languages/AndroidClientCodegen.js
- ern-api-gen/src/languages/ERNMixin.js
- ern-api-gen/src/languages/JavascriptClientCodegen.js
- ern-api-gen/src/languages/SwiftCodegen.js
- yarn.lock
This PR removes the dependency on [collections](https://github.com/montagejs/collections) from `ern-api-gen`.
This dependency was leading to some weird issues with the standard output stream (noticed part of some work in progress). After investigation it is probably due to the fact that this library is altering some of JavaScript core types (`Array`, `Function`, `Object`, `RegEx`) through [shims](https://github.com/montagejs/collections/blob/master/shim.js). For example, adding the `add` function on the `Array` prototype.
Altering core JS objects is never a good idea. Very risky especially in large codebases. If it can be avoided it should.
`ern-api-gen` was only requiring this dependency to use the `TreeMap `data structure from it.
Found a good alternative implementation of this data …
> Get rid of dependency on collections in ern-api-gen

- ern-core/package.json
- ern-local-cli/package.json
- ern-local-cli/src/index.ts
- yarn.lock
Time taken by tasks was only logged for non `debug`/`trace` log levels (the ones using spinners).
This PR updates `kax` which now allows to log time taken by tasks when using `KaxSimpleRenderer` (the renderer used for `debug`/trace` levels.
> Add time taken by tasks for debug and trace log levels

- package.json
- yarn.lock
- Bump TypeScript version to [3.0.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html)
- Bump associated typescript utilities to latest version
> Bump TypeScript version

- ern-api-impl-gen/src/ApiImpl.ts
- ern-api-impl-gen/src/generators/android/ApiImplAndroidGenerator.ts
- ern-api-impl-gen/src/generators/js/ApiImplJsGenerator.ts
- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-ios/src/IosGenerator.ts
- ern-container-gen/src/bundleMiniApps.ts
- ern-container-gen/src/generateMiniAppsComposite.ts
- ern-container-gen/src/reactNativeBundleAndroid.ts
- ern-container-gen/src/reactNativeBundleIos.ts
- ern-core/src/MiniApp.ts
- ern-core/src/android.ts
- ern-core/src/iosUtil.ts
- ern-local-cli/src/commands/list/dependencies.ts
- ern-local-cli/src/lib/utils.ts
Replace usage of `cd` with `pushd/popd` combo.
`cd` is pretty bad as it can lead to side effects hard to debug, so it's better to use `pushd` to enter a directory and then `popd` once work in directory is complete.
> Replace all cd commands with pushd/popd

- ern-core/src/nativeDependenciesLookup.ts
- ern-core/test/fixtures/.gitignore
- ern-core/test/fixtures/nativeDependenciesLookup/@scoped-pkgs/nested/node_modules/pkg-native-e/package.json
- ern-core/test/fixtures/nativeDependenciesLookup/@scoped-pkgs/nested/package.json
- ern-core/test/fixtures/nativeDependenciesLookup/@scoped-pkgs/pkg-native-a/package.json
- ern-core/test/fixtures/nativeDependenciesLookup/@scoped-pkgs/pkg-native-b/package.json
- ern-core/test/fixtures/nativeDependenciesLookup/pkg-native-c/package.json
- ern-core/test/fixtures/nativeDependenciesLookup/pkg-native-d/package.json
- ern-core/test/nativeDependenciesLookup-test.ts
Refactor the native dependencies lookup algorithm to improve it so that it can also detect native dependencies packages that are not at the top level of the directory structure, but nested in other packages (sub node_modules directory).
For example, given the path `packageA/node_modules/nativePackageB` to a package containing native mobile code (nativePackageB), the new algorithm properly account for `nativePackageB` whereas previous algorithm would not have.
Also add some minimal initial tests for the nativeDependencyLookup source file.
> Improve native dependencies lookup

- ern-api-impl-gen/package.json
- ern-container-gen-ios/package.json
- ern-container-gen/package.json
- ern-core/package.json
- yarn.lock
Bump `xcode-ern` version from `1.0.9` to `1.0.10` as it contains a fix for the `addFramework` plugin injection directive, which was leading to `.` to be added to the Frameworks Search Path of the ElectrodeContainer, multiple times, once for every framework added.
> Bump xcode-ern version

- ern-core/src/MiniApp.ts
- system-tests/fixtures/constants.js
- system-tests/tests/misc.js
Looks like `ern add` command was pretty buggy, but unnoticed because of no proper tests.
This PR fixes the command and add a couple system tests for it.
> Fix ern add command

- ern-container-gen/src/generateContainer.ts
- ern-container-gen/src/getContainerMetadata.ts
- ern-container-gen/src/types/ContainerGenResult.ts
- ern-container-gen/src/types/ContainerGeneratorConfig.ts
- ern-local-cli/src/commands/cauldron/regen-container.ts
- ern-local-cli/src/lib/container.ts
- ern-local-cli/src/lib/utils.ts
Improves Container generation speed when no native dependencies have changed compared to previous generation. If that is the case, only the JS bundle will be regenerated.
This feature does not apply for the `cauldron regen-container` command, given that this command is meant to fully regenerate a container even if nothing has changed within the Container (mostly of use in case of invalid plugin injection configuration).
Here are some performance metrics, for a complex reference Container :
- Full generation : 17 minutes
- Using cached packages feature (EN 0.21) : 11 minutes
- Using cache packages + this PR : 8 minutes
Please note that as for cached packages features, the directory of the previous generated container (`~/.ern/containergen` by default, or custom directory if modified …
> Only regenerate JS bundle when no native dependencies changed

- ern-api-impl-gen/resources/ios/apiController.mustache
For Swift 4 compatibility, all functions that needs to be invoked from objc, needs to be marked with 
mark with `@objc`, or it will not generate class function in Swift bridge header.
The `register` func in the generated `Controller` class does not have the `@objc` so it leads to an issue when trying to invoke it (with XCode 9.3) : 
Fix is just to add the `@objc` to the func.
Just updated the template accordingly. Also compatible with Swift < 4.
> Update iOS API Impl Generator for Swift 4 compatibility

- ern-local-cli/src/lib/container.ts
Fix invalid default output path for `runLocalContainerGen`. 
It was using `~/.ern/containergen` instead of `~/.ern/containergen/out/ios` or `~/.ern/containergen/out/android`.
This bug was only impacting Containers created locally through `create-container --minapps` command use (without providing an explicit out path). 
For Containers generated from Cauldron, the default path is the proper one.
> Fix default local Container Generator out path

- ern-local-cli/src/lib/utils.ts
Fix a bug in `runMiniApp` func (used by `run-ios` and `run-android` commands) that was leading to the `dev` flag to be still turned on in Runner configuration, when using `run-ios`/`run-android` commands with more than one MiniApp (as done in Getting Started guide). This is causing the dev mode to be enabled, therefore failing Getting Started on iOS when running both MiniApps (MovieList/MovieDetails) together, as React Native iOS will load the bundle from packager if dev mode is enabled and not fallback to the bundle stored in the binary as it is the case for Android.
Because there are multiple MiniApps in the Runner, Electrode Native does not launch a packager but rather creates a bundle stored in the binary.
The bugged code was not considering the local MiniApp in addition to the …
> Fix Runner config dev mode with multiple MiniApps

- ern-container-gen/src/generateContainer.ts
As we want to make sure that potential changes of a Container structure / code between different Electrode Native versions are properly propagated during next Container generation (otherwise only bundle would be regenerated and Container native project left untouched, which could lead to issues).
> Only peform partial Container generation if running same ern version

- setup-dev.js
There is no need to run `npm run rebuild` (which transpile every ern module) anymore for running Electrode Native development version (1000.0.0).
Building (transpiling) is now only needed to perform Electrode Native releases.
Removing this extra unecessary step from `setup-dev` as it was taking unnecessary time to run.
> Improve setup-dev script

- ern-container-publisher/src/getPublisher.ts
- ern-container-publisher/src/publishContainer.ts
- ern-container-transformer/src/getTransformer.ts
- ern-container-transformer/src/transformContainer.ts
- ern-core/src/ModuleFactory.ts
- ern-core/src/PackagePath.ts
- ern-core/src/index.ts
- ern-core/test/ModuleFactory-test.ts
- ern-core/test/fixtures/ModuleFactory/moduleWithSrc/src/index.js
- ern-core/test/fixtures/ModuleFactory/moduleWithoutSrc/index.js
Refactor `getTransformer` and `getPublisher` (these methods were close duplicates) by introducing a new class `ModuleFactory` in `ern-core` which generalize the duplicated logic.
By the same occasion refactor the code to split it into smaller granular functions and unit test it fully.
> Refactor publishers and transformers factories

- ern-local-cli/src/lib/utils.ts
- ern-local-cli/test/utils-test.js
This function was getting too big making it harder to grasp and unit test properly.
Extracted (created) the following smaller functions out of it :
- runContainerPublishers 
- runContainerTransformers
- getDefaultExtraConfigurationOfPublisherFromCauldron
> Explode performContainerStateUpdateInCauldron function

- ern-container-gen/src/generateContainer.ts
Fix the following kind of error :
```
✖ runCauldronContainerGen failed: Error: Unclosed tag at 29169
✖ [performContainerStateUpdateInCauldron] An error occurred: Error: Unclosed tag at 29169
✖ An error occurred: Unclosed tag at 29169
```
experienced when using `regen-container` under certain circumstances.
> Fix unclosed tag error when using regen-container

- docs/cli/platform/config/set.md
- ern-core/src/MiniApp.ts
- ern-core/src/utils.ts
- ern-local-cli/src/lib/constants.ts
Remove `EXPERIMENTAL` status of package cache feature now that it has been battle tested by multiple users without any issue.
Also, package cache feature will now be enabled by default. Users can still opt out from it if desired, through configuration, but given that this feature greatly speeds up container generation without any drawbacks, there is no more reason to have it disabled by default.
> Enable package cache by default

- ern-cauldron-api/package.json
- yarn.lock
Fix `error joi@13.7.0: The engine "node" is incompatible with this module. Expected version ">=8.9.0"` when trying to install Electrode Native with a Node version lower than `8.9.0` ... by downgrading  the version of `joi` used  by Electrode Native. Given that Electrode Native support Node 6+, it should not contain any dependency version that impose a node engine version constraint > Node 6.
[joi v12.0.0 requires node engine >= 4.0.0](https://github.com/hapijs/joi/blob/v12.0.0/package.json#L14)
[joi v13.0.0 requires node engine >= 8.4.0](https://github.com/hapijs/joi/blob/v13.0.0/package.json#L14)
> Downgrade joi version

- ern-core/src/getDefaultMavenLocalDirectory.ts
- ern-core/src/index.ts
- ern-local-cli/src/commands/run-android.ts
- ern-local-cli/src/commands/run-ios.ts
- ern-orchestrator/src/buildIosRunner.ts
- ern-orchestrator/src/generateContainerForRunner.ts
- ern-orchestrator/src/getRunnerGeneratorForPlatform.ts
- ern-orchestrator/src/index.ts
- ern-orchestrator/src/launchOnDevice.ts
- ern-orchestrator/src/launchOnSimulator.ts
- ern-orchestrator/src/launchRunner.ts
- ern-orchestrator/src/runMiniApp.ts
**Refactoring**
- Extract each function contained in `ern-orchestrator` `utils.ts` in its dedicated source file.
- Remove `utils.ts` from `ern-orchestrator`
> Explode ern-orchestrator utils

- ern-core/src/Platform.ts
- ern-local-cli/src/commands/publish-container.ts
- ern-local-cli/src/commands/transform-container.ts
- ern-orchestrator/src/container.ts
- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
- ern-orchestrator/src/runMiniApp.ts
Make use of Container Generator Directory from the `Platform` utility class, rather than manually building it, to guarantee path consistency and avoid duplication.
> Avoid manually building container generator directory

- docs/GLOSSARY.md
- docs/cli/cauldron/add/miniapps.md
- docs/cli/cauldron/regen-container.md
- docs/platform-parts/cauldron/structure.md
- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/types/CauldronContainer.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-core/src/GitManifest.ts
- ern-core/src/gitCli.ts
- ern-core/src/index.ts
- ern-core/src/utils.ts
- ern-core/test/Utils-test.ts
- ern-local-cli/src/commands/cauldron/regen-container.ts
- ern-util-dev/fixtures/default-cauldron-fixture.json
This PR adds a new feature to Electrode Native, namely `branch tracking`.
While it is currently possible to add MiniApps as git paths in the Container of a native application version in the Cauldron, one of the problem is that when adding a MiniApp as a reference to a git branch (mutable), the information of what's exactly inside a given Container version is lost, thus contradicting the purpose of the Container structure stored in Cauldron meant to precisely reflect the content of the Container. For example, adding a MiniApp as `https://github.com/electrode-io/MovieListMiniApp.git#master` will work, but unfortunately it makes it impossible to know (without some efforts) up to which commit on `master` is included in the Container. All that one can know is that the Container contains …
> Introduce MiniApp git branch tracking feature

- ern-container-gen-ios/src/hull/Config/ElectrodeContainer-Debug.xcconfig
- ern-container-gen-ios/src/hull/Config/ElectrodeContainer-QADeployment.xcconfig
- ern-container-gen-ios/src/hull/Config/ElectrodeContainer-Release.xcconfig
- ern-container-gen-ios/src/hull/Config/ElectrodeContainerTests-Debug.xcconfig
- ern-container-gen-ios/src/hull/Config/ElectrodeContainerTests-QADeployment.xcconfig
- ern-container-gen-ios/src/hull/Config/ElectrodeContainerTests-Release.xcconfig
Revert removal of `HEADERS_SEARCH_PATHS` from iOS Container that was done in https://github.com/electrode-io/electrode-native/pull/937
Not having this search path was causing issues during Xcode archiving for our native application, not being able to find some header files for some RCT modules.
That being said, having this header search path is causing build issue with latest React Native version (this is a know React Native issue). We will figure out how to properly handle latest React Native version issue prior to next Electrode Native release.
> Add back headers search paths to iOS Container

- docs/cli/cauldron/add/jsapiimpls.md
- docs/cli/cauldron/add/miniapps.md
- docs/cli/cauldron/batch.md
- docs/cli/cauldron/update/jsapiimpls.md
- docs/cli/cauldron/update/miniapps.md
- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/types/CauldronContainer.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-local-cli/src/commands/cauldron/add/dependencies.ts
- ern-local-cli/src/commands/cauldron/add/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/add/miniapps.ts
- ern-local-cli/src/commands/cauldron/batch.ts
- ern-local-cli/src/commands/cauldron/del/dependencies.ts
- ern-local-cli/src/commands/cauldron/del/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/del/miniapps.ts
- ern-local-cli/src/commands/cauldron/regen-container.ts
- ern-local-cli/src/commands/cauldron/update/dependencies.ts
- ern-local-cli/src/commands/cauldron/update/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/update/miniapps.ts
- ern-local-cli/src/lib/logErrorAndExitIfNotSatisfied.ts
- ern-orchestrator/src/Ensure.ts
- ern-orchestrator/test/Ensure-test.js
- ern-orchestrator/test/fixtures/common.js
Similar work than what was done for MiniApps in https://github.com/electrode-io/electrode-native/pull/945
Also include some refactoring of CauldronApi to clean things up and remove quite some duplication 
and update the following commands ...
- `cauldron add miniapps`
- `cauldron update miniapps`
- `cauldron add jsapiimpls`
- `cauldron update jsapiimpls`
- `cauldron batch`
... to restrict the possible types of paths that can be used, to the ones supported by Electrode Native, in order to make sure that it's not possible to add an unsupported path type that would create issues down the line.
> Add branch tracking feature for JS API Implementations

- ern-local-cli/src/commands/publish-container.ts
- ern-local-cli/src/commands/transform-container.ts
- ern-local-cli/src/lib/logErrorAndExitIfNotSatisfied.ts
- ern-orchestrator/src/Ensure.ts
- ern-orchestrator/test/Ensure-test.js
To have a clear error message rather than an obscure one, if user provided `--containerPath` does not point to a directory that holds a Container project.
> Update publish/transform container commands with container path validity check

- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
Follow up of https://github.com/electrode-io/electrode-native/pull/949 (forgot to regenerate Android Container fixture part of this PR) ...
Will automate fixture regeneration whenever iOS/Android Container hull is changing ... given that we forget to regenerate container fixtures almost 100% of the time 😞
> Regenerate Android Container system test fixture

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-local-cli/src/commands/cauldron/batch.ts
- ern-local-cli/src/commands/cauldron/del/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/del/miniapps.ts
- ern-local-cli/src/lib/emptyContainerIfSingleMiniAppOrJsApiImpl.ts
- ern-local-cli/src/lib/index.ts
- ern-local-cli/test/emptyContainerIfSingleMiniAppOrJsApiImpl-test.ts
Fix the following commands:
- `cauldron del miniapps`
- `cauldron del jsapiimpls`
- `cauldron batch` *(when removing miniapps or jsapiimpls)*
That were failing if ever the MiniApp or JS API Implementation to remove from the Container was the only one remaining in the Container. 
Problem was that Electrode Native wasn't properly handling this scenario. It was just removing the MiniApp or JS API Implementation and then was regenerating a new Container. However because there was no MiniApps or JS Api Implementations left in the Container, it was failing to properly regenerate a Container.
This PR fixes this specific fringe scenario. If the MiniApp or JS API Implementation to remove is the only one left in the Container, Electrode Native will just empty the target Container in Cauldron (reset …
> Fix cauldron object removal in specific context

- ern-api-gen/src/DefaultCodegen.js
- ern-api-gen/src/DefaultGenerator.js
- ern-api-gen/src/java/File.js
- ern-api-gen/src/java/ServiceLoader.js
- ern-api-gen/src/languages/AndroidClientCodegen.js
- ern-api-gen/src/languages/JavascriptClientCodegen.js
- ern-api-gen/test/CodegenConfigurator-test.js
- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-core/src/nativeDependenciesLookup.ts
- ern-core/test/nativeDependenciesLookup-test.ts
- ern-runner-gen-ios/test/IosRunnerGenerator-test.ts
Contains various fixes for Windows in different Electrode Native modules (unit tests were failing on Windows). Fixes are for the most part around file system paths that were not properly built for cross-platform usage.
All unit tests are now ✅ when ran on Windows/Linux/Mac.
System Tests are still ✅ when ran on Linux/Mac. Some issues on Windows due to fixtures comparaison which does not properly work on Windows (still looking into a solution), but all non fixture based ST are passing.
> Miscellaneous Windows fixes

- ern-local-cli/src/commands/code-push/release.ts
``` return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
ern-local-cli/src/commands/code-push/release.ts(196,9): error TS2345: Argument of type '{ codePushIsMandatoryRelease: boolean | undefined; codePushRolloutPercentage: number | undefined; force: boolean; pathToYarnLock: string | undefined; skipConfirmation: boolean | undefined; targetBinaryVersion: string | undefined; }' is not assignable to parameter of type '{ force?: boolean | undefined; codePushIsMandatoryRelease?: boolean | undefined; codePushRolloutPercentage?: number | undefined; pathToYarnLock?: string | undefined; targetBinaryVersion?: string | undefined; }'.```
> remove skipConfirmation from performCodePushOtaUpdate as unused

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/schemas.ts
- ern-cauldron-api/src/upgrade-scripts/1.0.0-2.0.0.ts
- ern-cauldron-api/src/upgrade-scripts/scripts.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/fixtures/cauldron-0.0.0.json
- ern-cauldron-api/test/fixtures/cauldron-2.0.0.json
- ern-cauldron-api/test/upgrade-scripts-test.ts
- ern-cauldron-api/test/util-test.ts
Associated to Cauldron schema changes introduced in https://github.com/electrode-io/electrode-native/pull/945
Because we added two new arrays `miniAppsBranches` and `jsApiImplsBranches` to the `container` object in Cauldron for git branches features, there is a need to make sure that users that are using git branches for MiniApps or JS API Implementations in the Cauldron won't have to move those to the new arrays by manually edition the Cauldron. Thus the need of new Cauldron schema version along with automated upgrade script.
> New Cauldron schema version 2.0.0

- ern-core/src/PackagePath.ts
Noticed that some users were using git paths without the `.git` suffix.
After testing it seems that this `.git` suffix is not needed for git paths, so it should not have to be enforced.
> Relax git PackagePath regular expressions

- ern-orchestrator/src/start.ts
- ern-orchestrator/test/start-test.ts
Skip all MiniApps that have been linked but do not exist on the workstation anymore, to avoid errors when running `ern start` command.
> Improve linked MiniApps resolution for start command

- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/index.ts
- ern-cauldron-api/src/types/CauldronNativeAppVersion.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
- ern-orchestrator/test/utils-test.js
Adds support of a new flag `detachContainerVersionFromRoot` to the `CauldronNativeAppVersion` type.
If this flag is present and set (`"detachContainerVersionFromRoot" : true`) for a given Native Application Version in Cauldron, then, Container versioning will be 'detached' (independent) from top level Container versioning. What this means in practice is that whenever the Container version of the native application is updated, it won't update the top level Container version.
For example, assuming we have a Cauldron with current top level Container version set to `1.0.5` and 3 versions of a native application defined, with only one having the `detachContainerVersionFromRoot ` flag set, as follow :
| Descriptor  | Container Version | detachContainerVersionFromRoot |
| ------------- | …
> Add detachContainerVersionFromRoot flag to Cauldron nap version

- ern-local-cli/src/commands/binarystore/add.ts
Use `pathExist` check instead of `isFilePath` because what we add to the binary store for iOS is a `.app` directory (which is not a file) v.s `.apk` for Android (which is a file).
So the command was working correctly for Android, but not for iOS.
> Fix binarystore add command for iOS

- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
- ern-orchestrator/test/utils-test.js
Force full container generation in case one or more MiniApps were added to the Container.
This is necessary because Electrode Native needs to regenerate/create some native files in the Container (for example MiniApp activities in the case of Android Container). 
Because Electrode Native was only regenerating the JS bundle in that specific context, the native updates were missing in the Container, leading to issues.
This fix ensure that a full Container generation is performed in case one or more MiniApps was added to the Container.
> Perform full container generation for new MiniApps

- ern-cauldron-api/src/CauldronRepositories.ts
`cauldron repo use` command was incorrectly working when provided with an invalid alias (alias that does not exist). This PR fixes this issue. `cauldron repo use` command will now properly fail in case it is used with an invalid cauldron alias.
Thanks @gmbharath12 for noticing this issue.
> Fix cauldron repo use command for invalid alias

- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-orchestrator/src/start.ts
For MiniApps that are specified as git branches in the Container, the  `start` command was creating a JS composite out of the commit SHAs frozen for the current Container version, rather than from the MiniApps branches. This is not really a desired behavior, as developers expect `start` to pick up the latest changes of all MiniApps (only for MiniApps specified as git branches).
This Pull Request establishes this expected behavior.
> Favor MiniApp git branches for start command

- docs/cli/transform-container.md
- ern-local-cli/src/commands/transform-container.ts
- ern-orchestrator/src/index.ts
`create-container` command, when used with `--descriptor` allows to locally create a Container based on the information matching the descriptor (native application version) stored in Cauldron.
However, the Container might not fully match the one of the native application, in case some transformers defined in Cauldron are to be applied on the Container. 
As of now, the only way was to manually provide any transformer to match the ones defined in Cauldron. 
With this PR, the `transform-container` command accept an optional `--descriptor`. If specified, all the transformers defined in Cauldron for the matching descriptor, will be applied for the local Container. This way the `transform-container` command is aligned with the `create-container` command.
Both commands can be chained to locally …
> Support locally running transformers defined in Cauldron

- .travis.yml
Due to version 0.57.5 of `react-native init` which depends on some dependency that is not compatible with Node 9, causing system tests runs on Travis CI to fail.
```
– An error occurred: Command failed: /home/travis/build/electrode-io/electrode-native/ern-core/node_modules/.bin/react-native init MiniAppSystemTest --version react-native@0.57.5 --skip-jest
– error sane@3.1.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*".
```
> Downgrade node version to 8 for Travis builds

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
- When a request is made from iOS to Javascript, Electrode Bridge should wait for React Native initialization and queue up the requests. It was improperly handled in Bridge. Time `dispatch_time_t` was incorrectly set when dispatching semaphore that caused this issue and couldn't wait until `dispatch_semaphore_signal` was fired.
- Detaching these operations in global queue instead of the main queue. Because we don't want to block the main thread.
- After React Native is initialized we dequeue all requests (FIFO). 
- Example showing iOS request ---> to JavaScript 
`[movieAPI.requests getMovieDetailWithMovieId:@"1" responseCompletionHandler:^(id  _Nullable data, id<ElectrodeFailureMessage>  _Nullable message) {
NSLog(@"Data %@", data);
}]` 
Credits to @belemaire 🥇 for the help 👍
> Fix queued requests issue in Bridge

- docs/cli/platform/config/set.md
- docs/platform-parts/cauldron/structure.md
- ern-cauldron-api/src/getActiveCauldron.ts
- ern-cauldron-api/src/types/Cauldron.ts
- ern-local-cli/src/commands/cauldron/config/del.ts
- ern-local-cli/src/commands/cauldron/config/get.ts
- ern-local-cli/src/commands/cauldron/config/set.ts
- ern-local-cli/src/commands/cauldron/upgrade.ts
- ern-orchestrator/src/constants.ts
- Add support of new Cauldron top level config key `requiredErnVersion`
- Value for this key can be a fixed version (for example `0.26.0`) or a valid version range as defined in the [semver](https://www.npmjs.com/package/semver) library (for example `0.26.x` or `>=0.26` or `0.26.0 - 0.28.0` ...)
- If this key is present in a Cauldron, it enforces a specific Electrode Native version (or range) to be used by the client connected to the Cauldron.
- If the user is not using a version satisfying the Cauldron requirement, any command that involves access to the Cauldron will fail and let the user know of the specific Cauldron requirement.
- Not enforced for `ern cauldron upgrade` and `ern cauldron config` commands.
- Version requirement can be bypassed in two ways :
- By setting the new local …
> Allow Cauldron to require an ern version

- ern-local-cli/src/commands/list/dependencies.ts
Make sure to run `yarn init` prior to `yarn add` to avoid command failure in case a `package.json` already exists up in the directory hierarchy.
> Fix list dependencies command

- docs/cli/cauldron/config/get.md
- docs/cli/cauldron/get/dependency.md
- docs/cli/cauldron/get/nativeapp.md
- docs/cli/list/dependencies.md
- ern-core/src/coloredLog.ts
- ern-local-cli/src/commands/cauldron/config/get.ts
- ern-local-cli/src/commands/cauldron/get/dependency.ts
- ern-local-cli/src/commands/cauldron/get/nativeapp.ts
- ern-local-cli/src/commands/list/dependencies.ts
- ern-local-cli/src/index.ts
Add `--json` option flag to the following commands :
- `cauldron config get`
- `cauldron get dependency`
- `cauldron get nativeapp`
- `list dependencies`
There is some special handling in the top level CLI implementation to disable all other console output in case this flag is set (no banner / no header and no logs what so ever), so that only the resulting formatted JSON output is written to the console. 
This is done because common use of the `--json` flag in CLI commands is to feed the result of the command to some other program. Having some banner / logs before the formatted JSON makes it more difficult to be parsed for consuming app.
> Add json option flag to some commands

- ern-runner-gen-ios/src/hull/ErnRunner.xcodeproj/project.pbxproj
- ern-runner-gen-ios/test/fixtures/simple-ios-runner/ErnRunner.xcodeproj/project.pbxproj
- when a new file is generated in `ErnRunner` project copyright is assigned to a person's name instead of organization name. 
- This PR fixes ^ issue
- Generate fixtures ?!
> Update organization name

- ern-core/src/MiniApp.ts
- ern-core/src/utils.ts
- ern-core/test/Utils-test.ts
Electrode Native should not cache MiniApps that are referencing a git branch, otherwise it will reuse the cached MiniApp even if there is new commits available.
Update `isGitTag` and `isGitBranch` method so that they return `false` instead of throwing an exception, if the package path is not git based or if the version is missing (for `isGitTag`).
> Do not cache MiniApps that are referencing a git branch 

- ern-orchestrator/src/start.ts
- ern-orchestrator/test/start-test.ts
Remove `node_modules` from the list of ignored watched directories when using `start` command.
This allow users to make modifications to any of the `node_modules` of a linked MiniApp and propagate changes immediately to packager, without having to re-run `ern start` command.
> Watch node_modules when using start command

- ern-cauldron-api/src/CauldronHelper.ts
- ern-local-cli/src/commands/publish-container.ts
- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
- ern-orchestrator/src/runContainerPublishers.ts
This PR updates the `performContainerStateUpdateInCauldron` function workflow, to publish raw Containers to git and work out of raw Containers instead of working out of regular Containers.
A raw Container is just a regular Container before any transformers have been applied to it. It is basically the pure untransformed output of the Container Generator.
Raw containers are published to a specific git branch `raw`. Also they are git tagged with the Container version suffixed by `-raw`. For example if Container version to be published is `1.2.3`, then two tags will be created : `1.2.3` for the regular/post-transform Container, and `1.2.3-raw` for the raw/pre-transform Container.
Storing pre-transformed Containers in addition to post-transformed Containers has two uses :
1. When working on, …
> Publish raw Containers to git

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/util.ts
Use uuid instead of file shasum as yarn lock filename (missing from #997).
> Use uuid for yarn lock instead of file shasum

- ern-container-gen/src/yarnLockUtils.ts
Fix a bug that was impacting MiniApps deltas computation for git based MiniApps, leading to MiniApps versions being misclassified as `new` instead of `same` or `upgraded`.
Issue was due to the direct use of the base path of the MiniApp (for example 
`git+ssh://git@github.com/foo/bar.git`) in the regular expression that was used to check for matches in the `yarn.lock` file.
However, this kind of string contains some characters that are reserved for regex (for example `+`, `.`) and therefore needed to be escaped properly.
This PR fixes this issue by making use of [the `escapeRegExp` utility function offered by lodash](
https://lodash.com/docs/4.17.11#escapeRegExp).
> Fix a bug in MiniApps delta computation for git miniapps

- ern-cauldron-api/src/CauldronApi.ts
Keep native application names/platforms/versions in sorted ascending order in Cauldron.
> Maintain sort order of Cauldron entries

- docs/cli/cauldron/update/miniapps.md
- ern-local-cli/src/commands/cauldron/update/miniapps.ts
Needed for internal CI workflow.
At code freeze, we use `update miniapps` command to update all of the MiniApps branches from `development` to `release/[platform]/[version]` but because the Container will have no changes (it's just a branch cut off) it won't be regenerated nor published by default.
We however want to be able to publish it, because at this point we need to publish the first release version of the Container (promotion).
> Add publishUnmodifiedContainer option to update miniapps command

- ern-core/src/utils.ts
- ern-core/test/coreutils-test.ts
Update `isDependencyApi` and `isDependencyApiImpl` functions to throw a clear error instead of returning false in case the target api or api-impl is not found in the npm registry.
Returning false was leading to the following misleading error to be thrown and logged  :
`Error: Unsupported plugin. No configuration found in manifest for foo-api`
Now the error will instead  be`Cannot find foo-api in npm registry` which is exactly what the problem is.
> Throw instead of returning false if package does not exist

- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
Add support for new `subdir` option of git publisher.
See https://github.com/electrode-io/ern-container-publisher-git/pull/1 for reference.
> Add support for subdir option of git publisher

- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
- ern-container-gen/src/injectReactNativeVersionKeysInObject.ts
[ReactActivityDelegate](https://github.com/facebook/react-native/blob/v0.58.0-rc.2/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java) was updated in RN 0.58. 
Accessibility of `getContext` and `getPlainActivity` methods were changed from `private` to `protected`.
> Add support for React Native 0.58.0

- ern-core/src/MiniApp.ts
To avoid issues if a `package.json` already exist up the directory chain, we need to run `yarn init` before running `yarn add`.
> Fix MiniApp fromPackagePath function

- ern-orchestrator/src/Ensure.ts
add the GLOSSARY link for incorrect EN module name
> add the GLOSSARY link for incorrect EN module name

- ern-container-gen/src/generateMiniAppsComposite.ts
We need support for JSX source files for an internal team.
This is not the final solution, just a temporary workaround while waiting on a more proper design to allow custom `rn-cli.config.js` files to be used for the composite JS project.
> Add support for JSX source files

- ern-core/src/GitManifest.ts
Fix a bug that was causing plugin config lookup failure in case a plugin name was starting with same prefix (for example `appcenter` / `appcenter-crashes`)
```
Error: Unsupported plugin. No configuration found in manifest for [plugin]
```
> Fix manifest plugin config lookup

- docs/cli/start.md
- ern-local-cli/src/commands/start.ts
- ern-orchestrator/src/start.ts
Add a new option flag `--disableBinaryStore` to `ern start` command, to allow bypassing retrieval and install of binary from the binary store.
> Add disableBinaryStore option to ern start

- ern-core/src/android.ts
Fix issue that is not properly installing APK retrieved from Binary Store in case no emulator is running and one is launched through prompt.
> Fix ern start with apk when no emulator is running

- ern-core/src/ErnBinaryStore.ts
Binary Store improvement
If APK that is inside the zip file is not conventionally named, installation on emulator/device will fail.
This PR just make sure that the APK is conventionally named, by renaming it to follow convention after extraction.
> Ensure that apk in zip file is properly named after extraction

- ern-container-gen/src/reactNativeBundleAndroid.ts
- ern-container-gen/src/reactNativeBundleIos.ts
Cleanup Container react native assets target directory of any files, before starting the bundler.
This is needed because when Container is generated with optimization that only regenerates the JS bundle, it will clone an existing Container version from Git, which already contains assets from a previous generation. In that case, it might be that there will be left over assets, that are not used anymore but will remain lingering around, potentially causing issues.
> Cleanup React Native assets target directory before bundling

- ern-container-gen/src/generateMiniAppsComposite.ts
Recent versions of react-native support typescript source files (`.ts`, `.tsx`) out of the box.
On recent versions of ern (I started with `v0.26`), typescript files worked fine, but they do not on the most recent version.
[This commit](https://github.com/electrode-io/electrode-native/commit/9c30e71190994e74b445fe6004e0049cb0bc609c) added overrides to the RN config, and caused typescript files to not be resolved.
So, this commit just adds ts/tsx files back into the resolved extensions.
Looks like 'backlog' ticket #770 could be closed out due to the work inside RN.
---
Thanks for this fantastic project -- it's incredible just how much surface area is covered by ERN.
Let me know if you have any comments -- happy to refactor/document/test as needed to get this change incorporated :smiley:
> Typescript file support

- docs/cli/code-push/release.md
- ern-local-cli/src/commands/code-push/release.ts
Update `code-push release` command to allow CodePush of packages using git paths.
This was a historical technical restriction that does not apply anymore.
> Add support to code push packages from git

- ern-core/src/utils.ts
Make sure that we log errors that are of Object type, instead of logging `[object Object]`
> Improve top level error logger

- ern-container-gen/src/reactNativeBundleIos.ts
Fix an issue introduced in `v0.29.2` causing iOS Container build to fail in case packaged MiniApp(s) were not containing any assets.
Fix https://github.com/electrode-io/electrode-native/issues/1064
> Fix iOS Container assets

- ern-container-gen/src/generateMiniAppsComposite.ts
- ern-core/src/YarnCli.ts
This PR adds initial Babel support for MiniApps.
Prior to this PR, any `.babelrc` file present in the root of a MiniApp was not considered during bundling. This was problematic for MiniApps that wanted to make use of some Babel plugins.
Unfortunately, proper support for Babel 7 requires a bit of hacking, because when we generate 
a `composite` bundle of multiple MiniApps, we can consider the composite as a 'virtual monorepo' composed of different MiniApps, therefore the .babelrc is not at the top level / root of the bundling working directory. With Babel 7 (RN >= 0.56.0) we need to make use of the [babelrcRoots](https://babeljs.io/docs/en/options#babelrcroots) option of Babel to specify 'whitelisted' directories containing `.babelrc` files to be processed (MiniApps typically), otherwise …
> Add initial Babel support

- ern-container-gen/src/generateContainer.ts
The modules order might actually be important in certain cases.
In our example `lottie-react-native` depends on `react-native` being built first, though when only resorting to alphabetical ordering we try to build `lottie-react-native` first.
This fix this particular issue, but maybe the order of dependencies problem should be taken further later? As an example for Lottie, `lottie-ios` should also be built before `lottie-react-native`. Luckily for this alphabetical works, but I could see how this might not stand the test of time and other plugins.
Maybe the information about the plugin could be made more public (that might actually already be the case in a cauldron?), and in this case the final user should be responsible for the sorting and the platform should only insure `react-native` …
> Fix react-native modules order

- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/container.ts
Add a new flag `bypassYarnLock` for both `containerGenerator` and `codePush` config objects in Cauldron.
Setting this flag to `true` will bypass `yarn.lock` usage for JS composite generation. 
It will still publish the composite `yarn.lock` to the Cauldron (for tracking purposes and to have a way to know all of the JS packages and versions that are included in any bundle), but won't make use of it to actually generate the composite, recreating a new one upon every generation.
If this flag is not set, it will default to `false` (current behavior).
> Add a new Cauldron config flag to bypass yarn.lock

- ern-container-gen/src/bundleMiniApps.ts
- ern-container-gen/src/reactNativeBundleAndroid.ts
- ern-container-gen/src/reactNativeBundleIos.ts
- Accept `dev` flag as a parameter rather than hardcoding it to false
- Remove `outDir` parameter check (enforced by TypeScript)
> Quick rework of reactNativeBundle functions

- ern-container-gen/src/bundleMiniApps.ts
- ern-container-gen/src/reactNativeBundleAndroid.ts
- ern-container-gen/src/reactNativeBundleIos.ts
- ern-core/src/ReactNativeCli.ts
Not used yet, but adding support to create source map along with bundle.
Will be of use for upcoming Sentry integration.
> Add internal support to generate source map with bundle

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
@deepueg Thanks for spotting the instanceManager not being able to resolve the react instance.
Credits to @deepueg 👍 for working together together on this issue.
https://github.com/Microsoft/react-native-code-push/blob/3144c916018fab077231e88d8718ad3a1cb0a7d8/docs/setup-android.md
Per the read me it explicitly suggests `CodePush.setReactInstanceHolder(mReactNativeHost)` that eliminates need of having a need for 
```@SuppressWarnings({"unused", "FieldCanBeLocal"})
protected ReactInstanceManager mReactInstanceManager;
```
Unlikely before it doesn't use reflection to resolve the react instance. We will clean up the internal native app's.
> implement ReactInstanceHolder to return instance manager 

- ern-cauldron-api/test/CauldronApi-test.ts
- ern-orchestrator/src/runContainerPublishers.ts
- ern-orchestrator/src/runContainerTransformers.ts
- ern-orchestrator/test/runContainerPublishers-test.ts
- ern-orchestrator/test/runContainerTransformers-test.ts
- ern-util-dev/fixtures/default-cauldron-fixture.json
Add support of a new `disabled` boolean property in `transformers`/`publishers` objects configured in Cauldron.
Setting this property to `true` will disable (bypass) the transformer or publisher, as illustrated below
```json
{
"name":"git",
"url":"git@github.com:user/myweatherapp-android-container.git",
"disabled": true
}
```
This allows for selective disablement of publishers and/or transformers in Cauldron, without having to remove the whole publisher/transformer configuration from Cauldron.
If the property is not present (default) or set to false, the transformer/publisher will be enabled.
> Allow to selectively disable transformers/publishers

- ern-container-gen/src/generateMiniAppsComposite.ts
In Rn 0.59.0 there is a version mismatch for `metro-react-native-babel-transformer` between [react-native](https://github.com/facebook/react-native/blob/v0.59.0/package.json#L185) which uses `0.51.0` and the new [community cli](https://github.com/react-native-community/react-native-cli/blob/v1.4.1/packages/cli/package.json#L39) introduced in 0.59.0, which uses `0.51.1`.
Because of this, there is two `metro-react-native-babel-transformer` modules that get installed, one at the root of `node_modules`, and another one in the `node_modules` of the community CLI.
Because the community CLI is ultimately the binary that is invoking metro for bundling, we need to patch the `metro-react-native-babel-transformer` of the community CLI, if it's present. Otherwise fallback to the top level one (which …
> Fix path of file to patch for babel with RN59

- docs/cli/cauldron/add/nativeapp.md
- docs/cli/cauldron/update/nativeapp.md
- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/schemas.ts
- ern-cauldron-api/src/types/CauldronNativeAppVersion.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-local-cli/src/commands/cauldron/add/nativeapp.ts
- ern-local-cli/src/commands/cauldron/update/nativeapp.ts
- ern-util-dev/fixtures/default-cauldron-fixture.json
Add a new optional string property `description` to native application version object stored in Cauldron.
Because we are starting to see some Electrode Native workflows that are making use of specific 'fake' native application versions to build different 'flavors' of containers, it can be useful to have a description string associated to these custom native application versions to describe what the version is used for.
- Updates `cauldron add nativeapp` command with new `description` option 
- Updates `cauldron update nativeapp` command with new `description` option 
**Breaking Change**
The `cauldron update nativeapp` command was defaulting `isReleased` flag to `true` if not provided. 
This was a mistake, especially now that the command can update one or more properties in target native …
> Add new description property to nap version in Cauldron

- ern-cauldron-api/src/CauldronApi.ts
Do not enforce a semver compliant version for native app versions in Cauldron.
Fixes https://github.com/electrode-io/electrode-native/issues/1082
> Fix app versioning for cauldron add nativeapp command

- ern-container-gen/src/reactNativeBundleIos.ts
Fixes https://github.com/electrode-io/electrode-native/issues/1092
> Fix missing iOS assets directory in Container

- ern-cauldron-api/src/CauldronHelper.ts
Improves `getPublisher` method, so that it properly returns the publisher from Cauldron, if a version is present in the string.
For example, if in Cauldron a publisher `name` is defined as `ern-container-publisher-git@^1.2.1` -legit-, this method would not have work when invoked as follow `getPublisher('ern-container-publisher-git')`, because of string comparison expecting exact match.
With this new implementation, because we are using `PackagePath` and ignoring version, the method will work as expected.
> Improve Cauldron getPublisher method

- ern-core/package.json
- yarn.lock
Fix `run-ios` command with`XCode 10.2`, not finding any device.
After investigation this is due to the `node-simctl` version used. Using version `4.0.2` is properly listing devices with `XCode 10.2`, also tested it with `XCode 10.1`.
> Bump node-simctl version

- docs/SUMMARY.md
- docs/cli/create-composite.md
- docs/cli/create-container.md
- ern-local-cli/src/commands/create-composite.ts
- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/container.ts
The current way to create a JS composite project is to use the `create-container` command along with the `--jsOnly` flag.
There is -at least- two problems with the current approach :
1. It creates confusion around platform concepts understanding, especially for new comers. 
The JS Composite is not a Container in itself, so why should one use a `create-container` command to create a Composite when they are not the same?
2. It makes the `create-container` command logic more complex to accommodate this specific option, also because of the fact that some options of the command can only be used when `--jsOnly` is present or the opposite (also on a most fundamental design note, the current command allows to `create a Container` OR `create a Composite`. When a single command can do two different …
> Add new create-composite command

- ern-orchestrator/src/buildIosRunner.ts
- ern-orchestrator/src/launchRunner.ts
- Return a `Promise` rather than `void` from `launchIosRunner` function so that in case of an error being thrown we don't end up with an ugly `UnhandledPromiseRejectionWarning`.
- Improve error message in case of iOS Runner build failure, by giving some suggestion to the user to help troubleshoot the build issue further (rather than just facing a bare xcbuild error code without any clue of what to do next).
**Before**
```
(node:31119) UnhandledPromiseRejectionWarning: Error: XCode xcbuild command failed with exit code 65.
at ChildProcess.xcodebuildProc.on.code (/Users/blemair/Code/electrode-native/ern-orchestrator/src/buildIosRunner.ts:33:30)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Socket.stream.socket.on …
```
> Improve iOS Runner build failure reporting

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-core/src/android.ts
- ern-core/src/index.ts
- ern-core/test/android-test.ts
- ern-runner-gen-android/src/AndroidRunnerGenerator.ts
Light refactoring to remove some duplication and verbosity.
Prep work for upcoming PRs.
> Light refactoring of android extra config

- ern-local-cli/src/commands/cauldron/update/miniapps.ts
In case the resolved SHAs of git based MiniApps are the same as the ones in current Container, we still want to update the Cauldron with the new versions of the MiniApps (for example updating from a SHA to a git tag) even if the Container is not re-generated.
> Improve cauldron update miniapps command

- docs/SUMMARY.md
- docs/cli/create-plugin-config.md
- ern-core/package.json
- ern-core/src/AndroidPluginConfigGenerator.ts
- ern-core/src/IosPluginConfigGenerator.ts
- ern-core/src/PluginConfigGenerator.ts
- ern-core/src/index.ts
- ern-core/test/AndroidPluginConfigGenerator-test.ts
- ern-core/test/fixtures/PluginConfigGenerator/android/dependencies/build.gradle
- ern-local-cli/src/commands/create-plugin-config.ts
- ern-local-cli/src/lib/askUserInput.ts
- ern-local-cli/src/lib/index.ts
- yarn.lock
Add a new `create-plugin-config` command which can be used to automatically generate plugin configuration files for the Manifest.
This command has to be run from within the root of a Manifest directory (most likely a clone Manifest repository). 
For example to add a plugin configuration for `react-native-foo` plugin version `1.2.3`,  the following command could be run in the root of a Manifest directory :
`ern create-plugin-config react-native-foo@1.2.3`
Assuming the plugin supports both iOS and Android, and that its configuration can be generated by the command, this will result in the following directories and files to be generated.
```
plugins/ern_v0.14.0+/react-native-foo_v1.2.3+/config.json
plugins/ern_v0.14.0+/react-native-foo_v1.2.3+/ReactNativeFooPlugin.java
```
This plugin …
> Add new create-plugin-config command

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/lib/build.gradle
- system-tests/fixtures/android-container/lib/build.gradle
Perform the following pre-processing for dependencies (declared by plugins) to be added in the Android Container as `implementation` statements :`
- Dedupe 
Multiple plugins might be using a same dependency (including version). This previously would have resulted into multiple `implementation` statements added for same exact dependency. 
- Align support library version
Electrode Native offers to choose a support library version to use for the Container, or use an internal default. Prior to this change, any support library (group `com.android.support`) used by a plugin would have been injected as such including version used by the plugin, resulting in different versions of the support library. 
- Keep highest versions
If a dependency is used by multiple plugins but with a different …
> Improve Android Container generator dependencies resolution

- ern-composite-gen/src/generateComposite.ts
- ern-composite-gen/src/miniAppsDeltasUtils.ts
- ern-local-cli/src/commands/create-composite.ts
- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/generateContainerForRunner.ts
Improve logs for Composite Generation and fix some Container generation logs.
Will probably ship in patch version `0.31.1` soon given that during Composite Generation no logs at all are displayed in `info` level in `0.31.0`, which is problematic as it might lead users to think the process is stalled.
> Improve Container and Composite generation logs

- ern-cauldron-api/src/BaseGit.ts
This way, even if the Cauldron was modified in some way during the execution of a command, the command won't fail with an error on `git push`, as long as the changes made are not conflicting with the changes made by the command.
For example, with this change, it is now possible to update configuration files in the Cauldron while a Cauldron Container Generation is running separately, without causing the container generation to fail in the end on git push.
> Rebase cauldron from upstream before pushing

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-local-cli/src/commands/cauldron/del/nativeapp.ts
Remove associated app configuration file if any exist when using `cauldron del nativeapp` command
> Remove app config when removing an app from Cauldron

- docs/cli/cauldron/add/nativeapp.md
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-local-cli/src/commands/cauldron/add/nativeapp.ts
Add a `--config` option to `cauldron add nativeapp` command, that can be used to set the configuration to use for this new native application version.
> Add config option to cauldron add nativeapp command

- ern-local-cli/src/commands/cauldron/add/nativeapp.ts
Fix `cauldron add nativeapp` command throwing exception in case no other version of the application was found in Cauldron.
> Fix cauldron add nativeapp command

- ern-core/src/createTmpDir.ts
Using `platform config set` command, it is possible to specify a custom temporary directory to be used by Electrode Native (`tmp-dir` config key).
Unfortunately, after setting a custom temporary directory, any subsequent commands trying to access the directory will fail with error `Error: ENOENT: no such file or directory`.
This PR just creates the temporary directory it it does not exist, to avoid running into this issue, and sparing the user to have to manually create the directory.
> Create temporary directory if it does not exist

- docs/GLOSSARY.md
- ern-core/src/PackagePath.ts
Due to the fact that `yarn` commands expect git ssh urls to be formatted in a specific way, it makes it more complicated to add a MiniApp from a GitHub repository as some url reformatting is required before using `ern` comamnds.
This PR adds support for GitHub SSH urls format, so that it is now possible to just copy/paste the git ssh url from GitHub, improving user experience.
Behind the scene, all that Electrode Native will do, is to transform the url to the proper format for internal use.
> Add support for GitHub SSH urls

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/types/CauldronNativeAppVersion.ts
- ern-cauldron-api/src/upgrade-scripts/2.0.0-3.0.0.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-orchestrator/src/syncCauldronContainer.ts
`detachContainerVersionFromRoot` is a config property so it should belong to a `config` object. 
However up until now it was incorrectly stored in native application version objects in Cauldron.
This PR corrects this and move this config property where it belongs, in a `config` object.
> Move detachContainerVersionFromRoot to config

- ern-core/src/GitManifest.ts
It should be possible for an override manifest repository, in its simplest form, to only contain a root `manifest.json` document without any `plugins` directory.
As of now this scenario is making Electrode Native throw the following error`ENOENT: no such file or directory, scandir '[...]/plugins` whenever trying to access the override manifest.
This PR fix this problem to allow override manifests without a `plugins` directory present.
> Allow override manifest without plugins directory

- ern-local-cli/src/lib/askUserForCodePushDeploymentName.ts
Use `getCodePushConfig` rather than `getConfig` for proper lookup (bubble up config levels)
> Fix code push deployment name config lookup

- ern-core/src/createTmpDir.ts
Do no check for `tmpDir` directory existence if this variable is `undefined` (when not explicitly set through `tmp-dir` config key)
> Fix createTmpDir when no tmp-dir config key is set

- docs/cli/cauldron/update/miniapps.md
- ern-local-cli/src/commands/cauldron/update/miniapps.ts
Add a way to update all MiniApps to a specific version, which can be of use to simplify workflows (mostly CI).
For example, if we want to update all MiniApps version in a Container to a specific release branch (`Release/1.3.0` for example). For example, the following command:
```
ern cauldron update miniapps git+ssh://git@github.com/foo/app-one.git#Release/1.3.0 git+ssh://git@github.com/foo/app-two.git#Release/1.3.0 git+ssh://git@github.com/foo/app-three.git#Release/1.3.0
```
Can now be simplified to :
```
ern cauldron update miniapps all --targetVersion Release/1.3.0
```
> Add a way to update all MiniApps to a specific version

- ern-cauldron-api/package.json
- ern-cauldron-api/src/schemas.ts
- ern-cauldron-api/src/util.ts
- yarn.lock
To get rid of following warnings when installing Electrode Native, due to the use of an older `joi` version.
```
warning ern-local-cli > ern-cauldron-api > joi@12.0.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning ern-local-cli > ern-cauldron-api > joi > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older …
```
> Bump joi dependency to latest version

- .huskyrc
- package.json
`precommit` hook in scripts got deprecated in recent [husky](https://github.com/typicode/husky) version, so doing it the [new way](https://github.com/typicode/husky#upgrading-from-014)
> Move precommit script to .huskyrc

- ern-composite-gen/src/Composite.ts
Fix a bug in the Composite class, causing MiniApps retrieved from the file system (rather than git or npm registry) to be improperly recognized as such, leading to multiple issues.
> Fix a bug with composite when dealing with fs MiniApps

- .gitattributes
Update `.gitattributes` by refining exclusions.
- Use `linguist-vendored` rather than `linguist-generated` so that we diffs will still show in GitHub for these files.
- Exclude only `system-tests/fixtures` rather than complete `system-tests` directory as this directory contains source files that should not be excluded.
- Add exclusions for more fixtures directories.
> Exclude fixtures from language statistics

- ern-core/src/GitManifest.ts
- ern-core/src/Manifest.ts
- ern-local-cli/src/commands/add.ts
- ern-local-cli/src/commands/create-api-impl.ts
- ern-local-cli/src/commands/create-api.ts
- ern-local-cli/src/commands/create-miniapp.ts
- ern-local-cli/src/commands/github/align-dependencies.ts
- ern-local-cli/src/commands/list/dependencies.ts
- ern-local-cli/src/commands/platform/plugins/list.ts
- ern-local-cli/src/commands/platform/plugins/search.ts
- ern-local-cli/src/commands/regen-api-impl.ts
- ern-local-cli/src/commands/regen-api.ts
- ern-local-cli/src/commands/upgrade-miniapp.ts
- ern-local-cli/src/lib/logErrorAndExitIfNotSatisfied.ts
- ern-orchestrator/src/Ensure.ts
Update all commands accepting a `--manifestId` option, to ensure that if a manifest id is provided, it exists in the Manifest(s) (master and/or override based on configuration).
Also improves logging when syncing Manifest(s) by showing a spinner while the sync is in progress (rather than stalling output).
> Ensure Manifest id exists in Manifest(s)

- ern-orchestrator/src/start.ts
Starting `FSEvents` watcher early on, seems to have side effects on some user workstations, causing failure to properly retrieve the binary from the binary store (if any).
While we are still investigating the cause, starting the watcher after retrieving the binary was confirmed to fix the issue. This is a temporary workaround to be shipped with 0.32 release.
> Update start logic

- ern-cauldron-api/src/upgrade-scripts/2.0.0-3.0.0.ts
Script was not properly converting top level Cauldron `containerGenerator` config if present.
> Fix Cauldron upgrade script

- ern-local-cli/src/index.dev.js
- ern-util-dev/bin/ern-mocha.js
- ern-util-dev/bin/ern-nyc.js
Use `tsnode/register` [transpileModule](https://www.npmjs.com/package/ts-node#cli-and-programmatic-options) to speed up transpilation for tests and ern dev version (1000.0.0).
> Use TypeScript transpileOnly flag for tests and dev

- ern-local-cli/src/lib/epilog.ts
- Fix CLI command documentation url for nested commands such as `cauldron repo list`
**Before (invalid)** 
https://native.electrode.io/v/v0.31/cli-commands/cauldron/repo/list.html
**After (valid)**
https://native.electrode.io/v/v0.31/cli-commands/cauldron-repo/list.html
- Fix CLI command documentation for url for dev platform version 1000.0.0, which should point to master documentation.
**Before (invalid)** 
https://native.electrode.io/v/v1000.0.0/cli-commands/create-container.html
**After (valid)**
https://native.electrode.io/cli-commands/create-container.html
> Fix CLI epilog documentation url

- ern-orchestrator/package.json
- ern-orchestrator/src/composite.ts
In case of mismatching native dependencies versions detected after composite generation (just before bundling), Electrode Native logs the following error :
```
✖ [syncCauldronContainer] An error occurred: Error: The following plugins are not using compatible versions : 
✖      react-native
```
While this log point out the problematic native dependencies names, it doesn't log from which MiniApps the conflict in version is coming from. This PR adds full dependency tree logging to identify precisely which MiniApp(s) are using mismatching native dependencies versions.
```
✖ └─ react-native@0.59.4 [0.59.4]
✖    ├─ MiniAppA@0.0.1 [0.0.1]
✖    ├─ MiniAppB@1.2.2 [1.2.2]
✖    ├─ MiniAppC@1.1.36 [1.1.36]
✖    └─ MiniAppD@1.3.1 [1.3.1]
✖ └─ react-native@0.59.8 [0.59.8]
✖    └─ MiniAppE@0.0.2 [0.0.2] …
```
> Improve logging of mismatching dependencies versions

- ern-container-gen-android/src/AndroidGenerator.ts
Some Android native modules are including native libraries (`.so` files) to be stored in the `jniLibs` directory of the Container.
Because this directory is not included in the directories to be excluded from Mustache processing, this is leading to Container generation failure when such native modules are included in the Container.
This PR adds `lib/src/main/jniLibs` directory to the list of Mustache exclusions.
> Do not mustache jniLibs when generating Android Container

- ern-orchestrator/src/runMiniApp.ts
To allow client to provide a custom `cwd`.
> Add cwd param to runMiniApp function

- ern-local-cli/src/commands/cauldron/add/miniapps.ts
Not used anywhere in function.
> Remove unused force option from add miniapps command

- ern-cauldron-api/src/CauldronHelper.ts
Give direct access to `CauldronApi` instance to `CauldronHelper` clients.
> Give access to CauldronApi from CauldronHelper

- ern-cauldron-api/src/CauldronApi.ts
Relax guard clause in `addPackageToContainer` method to only throw if no version is set for registry and git packages. 
Do not throw if there is no version set for a file system located package as it will always be the case. This allows proper adding  of file system located packages to Container.
> Relax rule for adding package to container

- ern-local-cli/src/commands/cauldron/del/miniapps.ts
It should be possible to remove a git or file based MiniApp from a Container, given that it is now possible (since a few versions already) to add git (or more recently, file based) MiniApps to a Container.
Remove the deprecated historical restriction from command so that this command also works for git/fs MiniApps.
> Relax cauldron del miniapps command

- ern-orchestrator/src/start.ts
Remove `react-native-electrode-bridge` dependency from linked package node_modules to avoid issue when multiple bridge instances are created.
> Remove react-native-electrode-bridge when using start

- docs/platform-parts/manifest/native-modules.md
- ern-core/src/Manifest.ts
- ern-core/src/iosUtil.ts
Related to https://github.com/electrode-io/electrode-native-manifest/pull/114
> Add new setBuildSettings directive for iOS plugin configuration

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/types/CauldronNativeAppVersion.ts
Add new `getCodePushEntries` method overload to `CauldronApi`, to retrieve all of the Code Push entries across deployment names, and not limited to a specific deployment name.
> Add getCodePushEntries method overload

- ern-container-gen-android/src/AndroidGenerator.ts
addresses #1060 
Rebased the old POC up to master -- figured I'd create the PR to help discussion.
With [iOS's plugin processing](https://github.com/electrode-io/electrode-native/blob/8756615e1fae55b10a8de47c079a9db72de4f11f/ern-core/src/iosUtil.ts#L37), the 'hull filling' happens first. In android, it seems to happen [after the plugin processing](https://github.com/electrode-io/electrode-native/blob/master/ern-container-gen-android/src/AndroidGenerator.ts#L246), so we need to defer the replacements.
The `fs` use and replacement function was lifted from the iOS implementation, but was then wrapped in an `async` function side-effect creator for later processing. **This is probably inefficient**, but I held back on optimizations, pending discussion.
> WIP: Android `replaceInFile`

- docs/cli/cauldron/repo/add.md
- ern-cauldron-api/src/CauldronRepositories.ts
- ern-local-cli/src/commands/cauldron/repo/add.ts
Local Cauldrons support was kind of clumsy.
The fact that one had to use `local` as the Cauldron url was awkward, and on top of that all local Cauldrons were kept in `~/.ern/local-cauldrons` which was not very flexible.
This PR removes the special `local` url value handling. `url` can now be a path to a remote repository, or a path to any local directory. If a local directory path is used, and the directory does not contain a git repository (i.e `.git` directory), it will be created.
This change makes the command `cauldron repo add` more coherent while also improving flexibility as it is now possible to add a local cauldron using any local directory.
**For release notes**
**This is a breaking change**
> Improve local cauldrons support

- ern-core/src/GitManifest.ts
- ern-core/src/Manifest.ts
Making it easier to work on plugin configuration, as any changes to the local manifest directory being used, won't be overwritten by a force sync to remote repo any time manifest is accessed.
> Add support for local override manifest

- ern-cauldron-api/src/CauldronHelper.ts
When using `cauldron add nativeapp` command with the `--copyFromVersion` option, the command will misbehave if the version to copy from does not exist in the Cauldron.
Indeed, it will add the new native application version in the Cauldron, with nothing in it and then throw an error, which is not the desired behavior. We don't want the command to create the native application version in Cauldron in that case. 
This PR fixes this problem
> Fix cauldron add nativeapp with unexisting version to copy from

- system-tests/fixtures/constants.js
- system-tests/tests/misc.js
- system-tests/utils/afterAll.js
Use a local cauldron (created in a temporary directory) for system tests, rather than relying on a remote cauldron (in GitHub). This has two benefits :
- Speeds up the system tests, as we get rid of the incurred lag of working with remote repository.
- No need to publicly expose any credentials or token (more secure).
> Use a local cauldron for system tests

- ern-api-impl-gen/src/ApiImpl.ts
- ern-container-gen-android/src/AndroidGenerator.ts
- ern-core/src/iosUtil.ts
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/package.json
Two things in this PR related to native api implementations.
1. For Android, only copy the api implementation source in the Container (before this change, the bridge + api source code was injected in the Container). No changes for IOS because it was already behaving correctly by only injecting API Implementation source files in the Container.
2. A `pluginConfig` object is now added to the `ern` object in the `package.json` of the native api implementation project. This gives access to all plugin injection configuration directives, such as `dependencies` / `copy` / `permissions`, to add dependencies or permissions used by the native api implementation, to the Container, in the exact same way as it's done for native modules injection. If no `pluginConfig` object is found in the `ern` …
> Add injection configuration support for native api impls

- ern-local-cli/src/commands/binarystore.ts
- ern-local-cli/src/commands/cauldron.ts
- ern-local-cli/src/commands/cauldron/add.ts
- ern-local-cli/src/commands/cauldron/config.ts
- ern-local-cli/src/commands/cauldron/del.ts
- ern-local-cli/src/commands/cauldron/get.ts
- ern-local-cli/src/commands/cauldron/repo.ts
- ern-local-cli/src/commands/cauldron/update.ts
- ern-local-cli/src/commands/code-push.ts
- ern-local-cli/src/commands/github.ts
- ern-local-cli/src/commands/list.ts
- ern-local-cli/src/commands/platform.ts
- ern-local-cli/src/commands/platform/config.ts
- ern-local-cli/src/commands/platform/plugins.ts
- ern-local-cli/src/index.dev.js
- ern-local-cli/src/index.ts
If a user has the `NODE_ENV` globally defined and set to `development`, or is running `NODE_ENV=development ern` then `ern` will fail, because we use the `NODE_ENV` variable internally for Electrode Native development, to transpile TypeScript files on the fly rather than using pre-transpiled sources.
This result in an error such as 
```
SyntaxError: Unexpected token export
at createScript (vm.js:80:10)
```
because the release versions of Electrode Native are already pre-transpiled.
The `NODE_ENV` variable is widely used conventionally, so to avoid running into such issue, this PR replace `NODE_ENV` with `ERN_ENV` variable name.
> Fix use of NODE_ENV

- ern-container-gen-android/src/AndroidGenerator.ts
root path from api impl native path is `lib`, not `src`
> Fix android api native impl copy path

- ern-core/src/ios.ts
Fixes 
```
An error occurred: Cannot set property 'deviceId' of undefined
```
after selecting an iOS simulator to launch.
Has been reported by a user, and is due to the fact that if for some reason `iOSDeviceConfig` object is not present in `.ernrc`, `ernConfig.getValue` will return `undefined` (if no other default value specified). Later on in the code we do `deviceConfig.deviceId = [...]` leading to the error being thrown.
The fix is just to return `{}` empty object as default value, rather than `undefined` if `iOSDeviceConfig` object is missing from `.ernrc`
> Fix iOS simulator selection

- ern-orchestrator/test/start-test.ts
While running EN full unit test suite on Windows, noticed that a few tests were breaking (as usual due to the path separator being different on Windows). 
This PR fixes that, so that all unit tests are now properly passing on Windows.
> Fix some unit tests on Windows

- ern-container-gen/package.json
Not used anymore since `ern-container-gen-android` and `ern-container-gen-ios` packages were created.
> Remove copyFiles directive from ern-container-gen

- azure-pipelines.yml
- azure/templates/unit-tests.yml
- package.json
- Create a template to avoid step duplication for each agent pool.
- Split install/build steps into two distinct steps.
- Use yarn rather than npm for all steps.
- Update display name of all steps.
- Add new build script to npm scripts to only run `lerna run build` (as `lern clean` and `lerna bootstrap` are unnecessary for fresh setup .. bootstrap is not even needed anymore because of the use of yarn workspaces, will remove it later) .
> Update Azure pipeline for unit tests

- azure-pipelines.yml
- azure/templates/unit-tests.yml
- ern-core/src/Platform.ts
- ern-core/test/Platform-test.ts
- ern-core/test/fixtures/common.js
- ern-util-dev/bin/ern-mocha.js
- package.json
- yarn.lock
This PR updates our unit test setup along with azure pipeline configuration, to enable azure test reporting for Electrode Native unit tests.
Test reports will now be generated whenever a build that runs unit tests is triggered (whenever a PR is opened for example), they are generated for both Windows/Linux and MacOS. For example the screenshot below shows a test report with one test failure on Windows only.
> Add unit test reporting to azure pipeline

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
This adds two new convenience method for iOS container. 
```
/**
Returns a react native miniapp (from a JSBundle) inside a view controller.
@param name The name of the mini app, preferably the same name as the jsbundle
without the extension.
@param properties Any configuration to set up the mini app with.
@return A UIViewController containing the view of the miniapp.
*/
- (UIView *)miniAppViewWithName:(NSString *)name
properties:(NSDictionary * _Nullable)properties;
/**
Call this to update an RCTRootView with new props. Calling this with new props will cause the view to be rerendered.
Request will be ignored if the returned view is not an RCTRootView instance.
*/
- (void) updateView: (UIView *) view withProps:(NSDictionary *) newProps;
```
> Ios container update

- ern-core/src/ReactNativeCli.ts
Noticed some issues with caching of `.babelrc` for MiniApps relying on a Babel setup, due to the fact that we do not use the `--reset-cache` option when we are creating a bundle through `react-native bundle`.
This PR adds the `--reset-cache` option to `react-native bundle`, so that we don't run into any such metro caching issue.
Workaround for users experiencing issues related to metro caching when creating Containers, while waiting for next release is to manually clear the metro cache through `rm -rf $TMPDIR/metro-cache`
> Use --reset-cache option when calling react-native bundle

- ern-composite-gen/src/generateComposite.ts
Fix an issue with new `yarn resolutions` feature, that would overwrite patched files in `node_modules` as it runs `yarn install` after the files are patched :(
> Fix yarn resolutions

- docs/cli/code-push/promote.md
- ern-local-cli/src/commands/code-push/promote.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/test/codepush-test.ts
- ern-util-dev/fixtures/default-cauldron-fixture.json
Introducing new `--reuseReleaseBinaryVersion` option to `codepush promote` command.
This flag is mutually exclusive with `--targetBinaryVersion`.
If set, it will reuse the version present in the `appVersion` field of the CodePush metadata entry/entries associated to the/each release(s) to promote (`targetBinaryVersion` that was/were used to perform the initial release)
Closes https://github.com/electrode-io/electrode-native/issues/1229
> New codepush promote option to reuse relase binary version

- .huskyrc
It is unfortunately common of developers (myself included) not to run a build and unit tests before pushing a branch to the remote.
Because of this, we frequently see PRs checks failing because of some TypeScript type checking or transpilation issue, or some unit test failing.
For this reason, and to drastically reduce the number of PRs failing checks, this PR adds a `pre-push` commit hook (run whenever using `git push`), which will run a build of Electrode Native (to catch any TypeScript related issue) followed by a run of all unit tests (to catch any failing unit tests) before pushing to the remote.
> Add some git pre-push checks

- ern-core/src/GitHubApi.ts
As indicated in these release notes, https://github.com/octokit/rest.js/issues/620#issuecomment-497024159, `getCommitRefSha` function of Octokit is now deprecated and will be removed in a future version.
This PR replace the use of `getCommitRefSha` with `getCommit`.
> Address deprecated octokit function

- ern-local-cli/src/commands/create-composite.ts
If there is no resolved `compositeGenerator` generator config found in Cauldron when running the `create-composite` command, it will throw an error because `compositeGenConfig` will end up being undefined :( 
This PR fixes this issue.
> Fix create-composite command when no config exist

- system-tests/fixtures/android-container/container-metadata.json
- system-tests/fixtures/constants.js
- system-tests/fixtures/ios-container/container-metadata.json
https://github.com/electrode-io/MovieListMiniApp/tree/v0.0.33
```
[ == MISMATCHING NATIVE DEPENDENCIES ==]
✖ ├─ react-native-electrode-bridge@1.5.17 [1.5.17]
✖ │  └─ movielistminiapp@0.0.32 [0.0.32]
✖ └─ react-native-electrode-bridge@1.5.x [1.5.19]
✖    ├─ react-native-ernmovie-api@0.0.11 [0.0.11]
✖    │  └─ movielistminiapp@0.0.32 [0.0.32]
✖    └─ react-native-ernnavigation-api@0.0.5 [0.0.5]
✖       └─ movielistminiapp@0.0.32 [0.0.32]
✖ 
✖ runLocalCompositeGen failed: Error: The following plugins are not using compatible versions : 
✖      react-native-electrode-bridge
[ Generating Composite locally (Failed) ]
✖ An error occurred: The following plugins are not using compatible versions : 
✖      react-native-electrode-bridge
```
> [system test] upgrade the movielistminiapp to 0.0.33

- docs/cli/run-ios.md
- docs/cli/start.md
- ern-core/src/ReactNativeCli.ts
- ern-core/src/getLocalIp.ts
- ern-core/src/index.ts
- ern-local-cli/src/commands/run-ios.ts
- ern-local-cli/src/commands/start.ts
- ern-orchestrator/src/runMiniApp.ts
- ern-orchestrator/src/start.ts
- ern-orchestrator/test/runMiniApp-test.ts
Auto resolve local machine IP for `run-ios` command so that it is not necessary to manually find IP of machine to provide it to the `--host` option of `run-ios`.
If `--host` option is set on the command line, the value provided will still be used rather than the auto resolved one.
Also adding `host`/`port` options support to `ern start`
> Auto resolve host ip for run-ios command

- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
refactor how ReactRootViews are managed inside ElectrodeActivitydelegate.
Older implementation used to create one view per react component and update the props if a new create request comes in. This results in many issues when one activity tries to create multiple views for the same component during a feature flow.
The new implementation will create a new instance each time createReactRootView is called. Deprecated the old methods to keep the backward compatibility.
> Update root view creation

- ern-core/src/injectReactNativeVersionKeysInObject.ts
- ern-runner-gen-android/src/hull/app/build.gradle
Fix Android Runner generator so that it creates a proper `build.gradle` when used with versions of React Native < 0.59 that don't have 64bit support.
> Fix Android runner generator for pre 64bit generation

- ern-core/package.json
- ern-core/src/GitHubApi.ts
- ern-orchestrator/package.json
- yarn.lock
To get rid of this kind of error
```
{ Deprecation: [@octokit/rest] octokit.repos.updateFile() has been renamed to octokit.repos.createOrUpdateFile() (2019-06-07)
10:12:11     at Object.deprecatedEndpointMethod [as updateFile] (/ern/versions/0.35.0/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:50:28)
10:12:11     at GitHubApi.<anonymous> /.ern/versions/0.35.0/node_modules/ern-core/src/GitHubApi.ts:208:31)
10:12:11     at Generator.next (<anonymous>)
10:12:11     at fulfilled (/.ern/versions/0.35.0/node_modules/ern-core/dist/GitHubApi.js:4:58)
10:12:11     at <anonymous>
10:12:11     at process._tickCallback (internal/process/next_tick.js:182:7) name: 'Deprecation' }
```
> Replace deprecated octokit method with new one

- ern-core/src/Manifest.ts
Requalify error log to warning, as it is actually not causing any problem in most cases and wrongly leading users to thinking something went wrong.
We should add a strict mode to actually throw error if no configuration is found in manifest for some plugins.
> Requalify error log to warning

- ern-composite-gen/src/Composite.ts
- ern-orchestrator/src/container.ts
- ern-orchestrator/src/syncCauldronContainer.ts
Ensures that only native dependencies that are actually injected in the Container are reported in the Cauldron `nativeDeps` array.
> Fix dependencies sync with Cauldron

- ern-orchestrator/src/container.ts
Resolve native dependencies to be injected in a locally generated Container in the same way that is now done for Containers generated from Cauldron.
> Align local container generation with cauldron one

- ern-core/src/nativeDependenciesLookup.ts
Fix this error when using `run-ios` or `run-android` commands 
```
✖ runLocalCompositeGen failed: Error: Cannot find module 
'/var/folders/mp/sgcm53dd33b348tm65vwc6_8kv5xkh/T/tmp-
79821uaWi2yRFZMX4/node_modules/[..]/ios/build/Debug-
iphonesimulator/ElectrodeContainer.framework/assets/node_modules/[...]/package.json'
```
> Fix issue impacting run-ios and run-android

- ern-core/src/Platform.ts
- ern-core/test/Platform-test.ts
Fix an issue in local CLI installation (when using `ern platform use` or `ern platform install` commands) that could lead in failed local CLI installations depending on the Node version used.
> Fix electrode native local cli install

- docs/platform-parts/container/container-integration.md
- ern-composite-gen/src/generateComposite.ts
- ern-container-gen-android/package.json
- ern-container-gen-android/src/AndroidGenerator.ts
Update Composite and Container generators for proper support of React Native 0.60.
**Composite generator update**
- For React Native 0.60, the react-native dependency need to be present inside the `dependency` object of the composite package.json. Otherwise metro bundler will complain.
Adding `react-native` dependency in composite package.json was only done if react-native-code-push native module was detected, as it had a similar requirement. 
However some other things were done in `patchPackageJsonForCodePush` function, for example setting `name` and `version` fields of package.json. This is not needed anymore though because composite generator have moved to use `yarn init` a while back, which already sets these fields. Because the `react-native` dependency needs to be set in composite …
> Add initial React Native 0.60 support for Android

- ern-core/package.json
- ern-core/yarn.lock
- yarn.lock
This updates `gradle-to-js` to `2.0.0`. I manually checked and did not find any breaking changes compared to `1.2.1`:
https://github.com/ninetwozero/gradle-to-js/compare/v1.2.0...v2.0.0
Also there were some unrelated pending updates to `ern-core/yarn.lock` - I put them in a separate commit for better visibility.
> Update gradle-to-js to 2.0.0

- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- ern-core/src/injectReactNativeVersionKeysInObject.ts
React Native 0.60.1 introduced Hermes support.
One issue (that looks like a bug in React Native, introduced in 0.60.1 and still present in 0.60.5) is that `SoLoader.loadLibrary` method is called before `SoLoader.init` was called, resulting in a `java.lang.RuntimeException: SoLoader.init() not yet called` exception crashing the app.
This is due to a kinda chicken and egg problem, where `ReactInstanceManager` constructor calls [`initializeSoLoaderIfNecessary`](https://github.com/facebook/react-native/blob/v0.60.1/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L220) to actually call `SoLoader.init`, but in `ReactInstanceManagerBuilder`, which creates a new instance of `ReactInstanceManager`, a call to [`getDefaultJSExecutorFactory`](https://github.com/facebook/react-n …
> Update Android Container for rn>=0.60.1 support

- ern-orchestrator/src/launchRunner.ts
- ern-orchestrator/src/runMiniApp.ts
- ern-orchestrator/test/launchRunner-test.ts
- ern-orchestrator/test/runMiniApp-test.ts
- ern-runner-gen-android/src/AndroidRunnerGenerator.ts
- ern-runner-gen-android/src/hull/app/build.gradle
- ern-runner-gen-android/src/hull/app/src/main/AndroidManifest.xml
- ern-runner-gen-android/src/hull/app/src/main/java/com/walmartlabs/ern/miniapp/MainActivity.java
- ern-runner-gen-android/src/hull/app/src/main/java/com/walmartlabs/ern/miniapp/MainApplication.java
- ern-runner-gen-android/src/hull/app/src/main/java/com/walmartlabs/ern/miniapp/RunnerConfig.java
- ern-runner-gen-android/src/hull/app/src/main/res/values/strings.xml
- ern-runner-gen-android/test/AndroidRunnerGenerator-test.ts
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/AndroidManifest.xml
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/java/com/walmartlabs/ern/myminiappa/MainActivity.java
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/java/com/walmartlabs/ern/myminiappa/MainApplication.java
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/java/com/walmartlabs/ern/myminiappa/RunnerConfig.java
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/res/values/strings.xml
- ern-runner-gen/src/types/LaunchRunnerConfig.ts
This PR adds the enhancement #1296  for Android. 
With this change, when `ern run-android` command is executed, instead of creating an `ErnRunner` app it will create a MiniApp specific runner app. Also, the container dependency will be named based on the mini app. 
Old Runner vs New Runner
<p align="center">
</p>
> Multi runner android

- ern-api-gen/resources/swift/libraries/ern/api.mustache
- ern-api-gen/resources/swift/libraries/ern/apirequests.mustache
I'm trying to get the models/types in the generated Swift API client. This seems to do the trick. However, I am no Swift-developer so there might be a better way to do this 😛 . Is it possible to define some generics on the `ElectrodeBridgeResponseCompletionHandler` so we can avoid the casting from Any? -> MyModel ?
Issue: https://github.com/electrode-io/electrode-native/issues/1292
> Swift: Include type on responseCompletionHandler

- ern-runner-gen-ios/src/hull/ErnRunner/ViewController.m
- ern-runner-gen-ios/test/fixtures/simple-ios-runner/ErnRunner/ViewController.m
chgne Hull project because we updated NavigationAPIImpl, and regen fixture
> deprecating `finishedCallBack`, use `finish` to get a json

- system-tests/tests/create-api-base-fixture.js
- system-tests/tests/create-api-complex-fixture.js
- system-tests/tests/create-api-impl-js-fixture.js
- system-tests/tests/create-api-impl-native-fixture.js
- system-tests/tests/create-container-android-fixture.js
- system-tests/tests/create-container-ios-fixture.js
- system-tests/utils/sameDirContent.js
- Improve system tests runner implementation to allow excluding directories in addition to files, using built-in `excludeFilter` of [dir-compare](https://github.com/gliviu/dir-compare) library.
- Exclude `ElectrodeContainer/Libraries` from iOS Container system tests and `ElectrodeApiImpl/Libraries` from iOS API impl system tests (see https://github.com/electrode-io/electrode-native/pull/1307#issue-316123349 for motivation).
> Exclude iOS Container Libraries directory from system tests

- ern-core/package.json
- ern-core/yarn.lock
- ern-local-cli/package.json
- ern-local-cli/yarn.lock
- yarn.lock
A quick minor update `yazl` to `2.5.1`. This update can be performed independently of #1304, and will remove several lines from that PR once rebased.
> Update yazl to 2.5.1

- ern-composite-gen/src/generateComposite.ts
Fix an issue noticed when using `fetch` with React Native 60, resulting in the following error (`EventTarget.apply is not a function`) :
After investigation it is due to [event-target-shim](https://github.com/mysticatea/event-target-shim) `.mjs` file to be imported rather than the `.js` file ([these two files are exposed in dist](https://github.com/mysticatea/event-target-shim/tree/master/dist)). For some unknown reason yet, the `.mjs` source is leading to this error. 
This PR just updates the metro resolver configuration, updating the `sourceExts` array to give `.js` files precedence over `.mjs` files. This way when the metro resolver has to resolve a file and has a choice between the two extensions, it will pick the `.js` one over the `.mjs` one.
This fixes the issue noticed with …
> Update metro resolver sourceExts config

- system-tests/tests/create-api-impl-native-fixture.js
Not sure how this one slipped through the tests... 😉
> Fix system-tests excludeFilter array

- README.md
chore: change the badge to point to azure pipeline
> chore: change the badge to point to azure pipeline

- ern-core/src/Platform.ts
- ern-core/test/Platform-test.ts
Update `Platform.versions` method so that it returns versions in sorted ascending order.
Done in case we have to publish a patch version for an older ern version than current minor version line. This shouldn't happen as we don't offer patch support for such versions, but there could be exceptions to this rule.
If this ever happens, there will be a problem with `ern platform use latest` command, which just pop the latest element from the versions array returned by `npm info` command. Problem is that this command will return the versions ordered by publication time, meaning that if latest version is `0.38.0` and we publish `0.30.1`, then, `ern platform use latest` command will install `0.30.1` which is not the expected behavior.
> Sort platform versions

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
- Instead of exposing RCTRootView, we expose just the size flexibility. 
-  This is an enum to define size flexibility type of the root view. If a dimension is flexible, the view will recalculate that dimension so the content fits. After a recalculation, `rootViewDidChangeIntrinsicSize` method of the RCTRootViewDelegate will be called.
> Expose size flexibility of RCTRootView

- docs/cli/binarystore/add.md
- docs/cli/binarystore/get.md
- docs/cli/binarystore/remove.md
- docs/cli/start.md
- ern-core/src/ErnBinaryStore.ts
- ern-core/test/ErnBinaryStore-test.ts
- ern-local-cli/src/commands/binarystore/add.ts
- ern-local-cli/src/commands/binarystore/get.ts
- ern-local-cli/src/commands/binarystore/remove.ts
- ern-local-cli/src/commands/start.ts
- ern-orchestrator/src/start.ts
This feature was requested by an internal team but could be of use for any teams making use of [Electrode Native Binary Store](https://github.com/electrode-io/electrode-native-binarystore) along with [ern start](https://native.electrode.io/cli-commands/start) command.
This feature allows to upload a specific binary version to a binary store, using different 'flavors'. 
For example, a team might run different native builds (`Prod`/`Dev`/`Staging`...) of a native application for a single version, while users of `ern start` might want to start a specific binary version flavor.
Prior to this new feature, only one binary could be stored per version in a binary store making things more complex, because in order to get a similar behavior, users would have to create multiple versions in cauldron …
> Binary store flavor

- system-tests/regen-fixtures.js
Ensure that system tests regeneration is performed using development platform version (1000.0.0).
> Use dev platform version to regenerate system test  fixtures

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
Adding a new method to expose `RCTRootViewDelegate ` to native app so that it could use it to update the mini app's view frame or height / width constraint layout accordingly. 
`-rootViewDidChangeIntrinsicSize:` will be called by React Native after the mini app's root view's intrinsic content size is changed.
> Expose React Native delegate

- docs/cli/bundlestore.md
- docs/cli/bundlestore/create.md
- docs/cli/bundlestore/delete.md
- docs/cli/bundlestore/upload.md
- docs/cli/bundlestore/use.md
- docs/cli/platform/config/del.md
- docs/cli/platform/config/get.md
- docs/cli/platform/config/set.md
- ern-cauldron-api/src/CauldronHelper.ts
- ern-core/src/BundleStoreEngine.ts
- ern-local-cli/src/commands/bundlestore/create.ts
- ern-local-cli/src/commands/bundlestore/delete.ts
- ern-local-cli/src/commands/bundlestore/upload.ts
- ern-local-cli/src/commands/bundlestore/use.ts
- ern-local-cli/src/lib/logErrorAndExitIfNotSatisfied.ts
- ern-orchestrator/src/Ensure.ts
- ern-orchestrator/src/constants.ts
Keep bundle store server host info in Cauldron rather than locally (as done for sourcemap and binary store). This way, users won't have to manually set the bundle store host locally on their workstation in order to use it, but will automatically have access to the bundle store server associated to the cauldron they are currently connected to.
> Move bundle store host config to Cauldron

- ern-orchestrator/package.json
- ern-orchestrator/src/start.ts
- ern-orchestrator/test/start-test.ts
- Remove MiniApps `node_modules` from file watch (big CPU gain, less resource consumption).
- Only copy MiniApps non hoisted `node_modules` rather than the whole `node_modules` directory (big speed up on copy operation).
> Improve performance of start command

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/build.gradle
- ern-container-gen-android/src/hull/lib/src/main/AndroidManifest.xml
- ern-container-gen/src/generatePluginsMustacheViews.ts
Fix issue with custom Android permissions and repositories configured in native api implementation package.json, not being injected in the generated Container.
Fixed through a quick small refactoring, centralizing plugin configuration inject in AndroidGenerator but also taking care of deduping repositories/permissions which was not done previously (small cherry on the cake in addition to the fix ;)).
> Fix android native api implementation config

- ern-local-cli/src/commands/start.ts
- ern-local-cli/src/lib/logErrorAndExitIfNotSatisfied.ts
- ern-orchestrator/package.json
- ern-orchestrator/src/Ensure.ts
Check if a metro server is already running on target host/port before proceeding with `start` command execution, and fail the command immediately if a server is already running.
The `start` command can take quite a while to run, especially with many MiniApps, and it only used to log a warning at the end of command run in case a packager was already running, which is quite painful because for this command there is no point in having a packager already running, so it usually meant killing the packager and running the command again :(
> Fail start command if metro server is already running

- docs/guides/multi-miniapps-debug.md
Quick update to make `ern link` required rather than optional.
> Update multi MiniApps debug guide

- ern-orchestrator/src/runMiniApp.ts
- ern-orchestrator/test/runMiniApp-test.ts
This is to fix an issue when the previously generated miniapps tries to execute `ern run-android` command, the container name was not reflecting the one in `build.gradle` causing a build failure.
> Fix runner backcompatibility

- ern-composite-gen/package.json
- ern-composite-gen/src/cleanupCompositeDir.ts
- ern-composite-gen/src/generateComposite.ts
- ern-orchestrator/package.json
- ern-orchestrator/src/start.ts
- ern-orchestrator/test/start-test.ts
- yarn.lock
Only copying non hoisted packages of MiniApp(s) over to composite rather than the whole node_modules directory of the MiniApp was a mistake, as it could result in some missing packages at runtime under certain contexts.
This PR goes back to the old way (pre 0.38.0) of copying the whole node_modules directory of linked MiniApp(s) to the composite, fixing the issue (at the cost of start command taking longer to run). Also includes a quick refactoring and adding more logs (spinner) improving UX of the command.
> Fix an issue with start command for linked MiniApps

- ern-orchestrator/src/start.ts
Fix an issue with `start` command impacting some users. 
This issue causes metro packager to fail with `Unable to resolve module` error when using `start` with linked MiniApps, under some circumstances.
Root cause of the issue is that some directories of linked MiniApps that should be copied over to the composite, are not properly copied over due to an invalid directory exclusion filtering regex.
This PR fixes the issue by fixing the invalid regex. Previous regex would incorrectly lead to excluding some directories such as `[...]node_modules/react-native-foo-bar/` because it was matching the `node_modules/react-native` regex. 
At the same time, this PR also add the `.git` directory to the directory exclusion list as it is not necessary to copy it over to the composite (also improving …
> Fix issue with ern start directories exclusion

- ern-container-gen/src/copyRnConfigAssets.ts
- ern-container-gen/test/copyRnConfigAssets-test.ts
- ern-container-gen/test/fixtures/CompositeWithRnConfigs/modules/package-d/fonts/fakefont3.ttf
- ern-container-gen/test/fixtures/CompositeWithRnConfigs/modules/package-d/react-native.config.js
Container generator only copies font assets declared through `react-native.config.js` of [dependencies](https://github.com/react-native-community/cli/blob/master/docs/dependencies.md) packages types, but was not accounting for any font assets declared in `react-native.config.js` of [project](https://github.com/react-native-community/cli/blob/master/docs/dependencies.md) package types (for example MiniApps themselves).
Fixes https://github.com/electrode-io/electrode-native/issues/1348
> Fix fonts assets copy for react native projects

- ern-core/src/GitHubApi.ts
Rename `commit_sha` to `ref`, addressing the following runtime warn log :
```
Deprecation: [@octokit/rest] "commit_sha" parameter is deprecated for ".repos.getCommit()". 
Use "ref" instead
```
> Rename octokit deprecated parameter

- docs/cli/create-container.md
- docs/cli/run-android.md
- docs/platform-parts/container/container-integration.md
- ern-api-impl-gen/hull/android/lib/build.gradle
- ern-container-gen-android/src/hull/lib/build.gradle
- ern-core/src/android.ts
- ern-core/test/android-test.ts
- ern-runner-gen-android/src/AndroidRunnerGenerator.ts
- ern-runner-gen-android/src/hull/app/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/java/com/walmartlabs/ern/dummy/MainActivity.java
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/java/com/walmartlabs/ern/dummy/MainApplication.java
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/src/main/java/com/walmartlabs/ern/dummy/RunnerConfig.java
- ern-runner-gen-android/test/regen-fixtures.ts
- system-tests/fixtures/android-container/lib/build.gradle
- system-tests/fixtures/api-impl-js/ReactNativeErnmovieApiImplJs/yarn.lock
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/lib/build.gradle
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/yarn.lock
The PR introduces a way for the user to pass the compile Options.
For a plugin such as https://github.com/react-native-community/react-native-webview, where it specifically need JAVA 8 constructs. Also verified it's standard with core `react native` project 
```
java:25: error: incompatible types: List<RNCWebViewManager> cannot be converted to List<ViewManager>
15:39:07     return Collections.singletonList(new RNCWebViewManager());
```
> ability to pass compileOptions via android config

- ern-local-cli/src/commands/cauldron/batch.ts
Had to use `batch` command and had bad surprise that it was not supporting git based MiniApps.
Looks like we missed updating the command when we added git/fs support to other cauldron access commands. This PR fixes this issue by removing the restrictions.
> Remove path restrictions from batch command

- docs/cli/link.md
- docs/cli/link/add.md
- docs/cli/link/rm.md
- docs/cli/start.md
- docs/guides/multi-miniapps-debug.md
- docs/overview/ern-workflow.md
- ern-local-cli/src/commands/link.ts
- ern-local-cli/src/commands/link/add.ts
- ern-local-cli/src/commands/link/rm.ts
- ern-local-cli/src/commands/unlink.ts
Deprecate `ern link` and `ern unlink` commands and replace them with new `ern link add` / `ern link rm` subcommands.
These new commands are functionally equivalent to the deprecated ones. 
Done as a first step to extend `ern link` with additional features (planned for 0.39 release), which will involve the introduction of new `ern link` subcommands. In that context, grouping all `link` related commands is meaningful and much needed.
> Replace link and unlink commands with new ones

- ern-container-gen-android/src/AndroidGenerator.ts
encountered "Cannot read property 'push' of undefined" when generate a android container
> fix a bug on customPermissions

- ern-api-gen/src/generateProject.ts
- system-tests/fixtures/api/ComplexApi/schema.json
- system-tests/fixtures/api/TestApi/schema.json
- system-tests/fixtures/api/complexapi-schema.json
- system-tests/fixtures/api/testapi-schema.json
The entire generated `schema.json` file was one indentation level off, had a leading empty line, and whitespace errors on the last line. This fixes it.
> Fix formatting of generated api schema

- ern-core/package.json
- ern-core/src/GitHubApi.ts
- ern-orchestrator/package.json
- yarn.lock
Set `octokit/rest` to fixed `16.33.1` version to avoid an ongoing issue with `ern github` subcommands failing with such errors :
```
An error occurred: [BRANCH_NAME] is not a valid git ref of [GITHUB_REPO_URL]
```
Issue is impacting some users (and our CI jobs), so will release `0.38.7` with this fix while looking more closely as to why `16.34.0` of `octokit/rest` broke things.
> Set octokit to fixed version

- ern-cauldron-api/src/CauldronRepositories.ts
- ern-cauldron-api/src/getActiveCauldron.ts
- ern-core/src/BundleStoreEngine.ts
- ern-core/src/Manifest.ts
- ern-core/src/MiniApp.ts
- ern-core/src/Platform.ts
- ern-core/src/android.ts
- ern-core/src/config.ts
- ern-core/src/createProxyAgent.ts
- ern-core/src/createTmpDir.ts
- ern-core/src/deviceConfig.ts
- ern-core/src/getCodePushInitConfig.ts
- ern-core/src/ios.ts
- ern-core/src/packageCache.ts
- ern-core/test/Platform-test.ts
- ern-core/test/android-test.ts
- ern-core/test/ios-test.js
- ern-local-cli/src/commands/bundlestore/create.ts
- ern-local-cli/src/commands/bundlestore/delete.ts
- ern-local-cli/src/commands/bundlestore/use.ts
- ern-local-cli/src/commands/platform/config/del.ts
- ern-local-cli/src/commands/platform/config/get.ts
- ern-local-cli/src/commands/platform/config/list.ts
- ern-local-cli/src/commands/platform/config/set.ts
- ern-local-cli/src/index.ts
- ern-orchestrator/src/Ensure.ts
- ern-orchestrator/src/start.ts
- ern-orchestrator/test/start-test.ts
Quick refactoring, only renaming some methods because current method names are making my eyes bleed. 
Keep them short and consistent :
`getValue` => `get`
`setValue` => `set`
`deleteConfig` => `del`
> Rename some methods of ErnConfig class

- ern-core/src/BinaryStore.ts
- ern-core/src/ErnBinaryStore.ts
- ern-core/test/ErnBinaryStore-test.ts
- package.json
- yarn.lock
Use [got](https://github.com/sindresorhus/got) to issue HTTP requests to the Binary Store server, rather than running `curl` commands. [got](https://github.com/sindresorhus/got) is being used for the Bundle and SourceMap store clients, only the Binary store was relying on `curl` making it less cross-platform (windows does not have `curl` pre installed). 
Add a dev dependency on [nock](https://github.com/nock/nock) to improve unit tests of binary store (will also be used to improve unit tests of other pieces of code making HTTP requests)
> Replace curl with got for binary store

- docs/cli/platform/config/del.md
- docs/cli/platform/config/get.md
- docs/cli/platform/config/set.md
- ern-core/src/ErnBinaryStore.ts
- ern-orchestrator/src/constants.ts
Make binary store http client on par with bundle and source map store clients by adding configurable proxy support to it.
> Add proxy support to binary store client

- README.md
- ern-core/src/MiniApp.ts
- ern-core/src/Platform.ts
Fixes https://github.com/electrode-io/electrode-native/issues/1394
CocoaPods is a requisite for iOS RN applications, starting with React Native 0.60.
Even though Electrode Native does not need CocoaPods even with React Native 0.60, due to a different way to retrieve native modules, the fact that `create-miniapp` command relies on `react-native init` command under the hood (which has a health check for CocoaPods availability) causes the command to stall if CocoaPods is not installed.
This PR fixes the issue with `create-miniapp` command, by throwing a clear error message if CocoaPods is not installed on the machine running the command (and iff machine is a Mac and RN version >= 0.60).
While there is no need as of now to update other commands such as `run-ios` with this new guard, because …
> Ensure CocoaPods is installed if needed

- ern-composite-gen/src/generateComposite.ts
- ern-composite-gen/test/compositegen-test.ts
Add a guard clause to `generateComposite` function to make sure that at least one MiniApp or JS API implementation is provided to the function.
Closes https://github.com/electrode-io/electrode-native/issues/1396
While this PR guarantees that any command that generates a composite during its execution, will fail with a clear enough error message, all the involved commands should ideally fail before reaching this guard clause with an even clearer error message related to the command being ran.
> Add guard clause to generateComposite

- ern-core/test/mocha-root-level-hooks.ts
- ern-util-dev/bin/ern-mocha.js
Unit tests run output can get very messy in the terminal, because logging is still happening at default levels, which causes test result outcome to be intertwined with all of the logging done by the unit of code under test.
This PR disable all the various loggers used in the code base, before running any test suite. This is achieved through a mocha global (root level) `before` hook that is loaded prior to running a module test suite and disable `shell`/`log` and `kax` loggers.
Extract of test run with messy output prior to this PR :
```
installPlatform
✓ should throw if the platform version is not available
/private/var/folders/mp/sgcm53dd33b348tm65vwc6_8kv5xkh/T/tmp-15382WpYr0Wvvmy6Q/ern_home/versions/3.0.0 /Users/blemair/Code/electrode-native/ern-core …
```
> Disable logging during unit tests run

- ern-util-dev/bin/ern-nyc.js
Follow up to https://github.com/electrode-io/electrode-native/pull/1401 
Forgot to add mocha hooks registration when using `nyc` command (for coverage), so the unit tests run with coverage were still showing polluted log output.
> Add missing mocha hooks to nyc command invocation

- ern-composite-gen/src/generateComposite.ts
Fix an issue with [selective dependency resolution support](https://native.electrode.io/reference/index#selective-dependency-resolutions-support) causing metro bundler failure when this feature is used, under some circumstances.
> Fix yarn selective dependency resolutions support

- ern-api-impl-gen/package.json
- ern-api-impl-gen/src/generators/android/ApiImplAndroidGenerator.ts
- ern-api-impl-gen/src/generators/ios/ApiImplIosGenerator.ts
- ern-api-impl-gen/src/generators/js/ApiImplJsGenerator.ts
- ern-cauldron-api/package.json
- ern-cauldron-api/src/BaseGit.ts
- ern-cauldron-api/src/EphemeralFileStore.ts
- ern-cauldron-api/src/GitFileStore.ts
- ern-container-gen-android/package.json
- ern-container-gen-ios/package.json
- ern-container-gen/package.json
- ern-container-gen/src/generateContainer.ts
- ern-container-gen/src/reactNativeBundleIos.ts
- ern-core/src/ErnBinaryStore.ts
- ern-core/src/FsCache.ts
- ern-core/src/GitManifest.ts
- ern-core/src/createTmpDir.ts
- ern-core/src/handleCopyDirective.ts
- ern-core/src/unzip.ts
- ern-local-cli/package.json
Replace blocks following such pattern 
```javascript
if (!fs.existsSync(dir)) {	
shell.mkdir('-p', dir)
}
```
with a single call to [fs-extra](https://github.com/jprichardson/node-fs-extra) more concise [ensureDir](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureDir.md) call.
```javascript
fs.ensureDirSync(dir)
```
Using synchronous version `ensureDirSync` in synchronous functions and asynchronous version `ensureDir` in asynchronous functions.
> Use fs-extra ensureDir

- ern-composite-gen/src/generateComposite.ts
- ern-core/src/MiniApp.ts
The missing commas were causing Lint errors in generated projects.
> Add trailing comma to generated metro.config.js

- ern-core/package.json
- yarn.lock
Most importantly, this updates the transitive dependency on `appium-support` as seen in this commit: 
https://github.com/appium/node-simctl/commit/3e68853666ba7525f657242e1e4e4625af6f1b92
The newer version of `appium-support` drops the dependency on `mjpeg-consumer`. `mjpeg-consumer` had a dependency on `buffertools`, which caused errors with `node-gyp` compilation on newer versions of Node. 😅 
Also see this PR for reference: https://github.com/appium/appium-support/pull/78
It does not look like any code changes are required on our end (we're only using `getDevices` and `installApp` from `node-simctl`).
> Update node-simctl to 5.1.1

- ern-orchestrator/package.json
- ern-orchestrator/src/start.ts
Fix an issue with `start` command causing multiple instances of native modules to be used.
Problem is due to the fact that all linked miniapps directories are copied over to their location in the composite directory, including their node_modules directory, containing all the native modules being used by the miniapp.
The `start` command was already excluding a few native modules directories from being copied to the composite (react-native / react-native-electrode-bridge) but was not excluding any other native modules.
This PR make sure that all native modules used in the composite, are not copied over along with the miniapp directory, so that they are only kept in the top level composite node_modules directory. 
For example, assuming we are using `start` command for two miniapps, both of …
> Fix an issue with ern start command

- ern-core/src/packageJsonFileUtils.ts
Fix a regression introduced in https://github.com/electrode-io/electrode-native/pull/1409 in `writePackageJson` and `writePackageJsonSync` functions.
Instead of calling our custom `fileUtils` helper, [we switched to using fs-extra](https://github.com/electrode-io/electrode-native/pull/1409/files#diff-782006eabb7ea51c10f5e550f380b257L29-L39) to write the json file. 
Problem is that our custom helper functions were internally passing the appropriate formatting options to `JSON.stringify`, and forgot about that when switching to fs-extra. 
System test fixtures of https://github.com/electrode-io/electrode-native/pull/1414 have been regenerated to fix the issue.
> Fix writePackageJson formatting

- system-tests/fixtures/api/complex-api/package.json
- system-tests/fixtures/api/test-api/package.json
- system-tests/regen-fixtures.js
- system-tests/tests/create-api-base-fixture.js
- system-tests/tests/create-api-complex-fixture.js
No longer take the machine-local user name and modify the `author` field in the test fixtures on regeneration.
> Avoid unnecessary modifications to test fixtures

- ern-core/src/utils.ts
Improve error message logged by `getCommitShaOfGitBranchOrTag` function in case the branch/tag does not exist in the target repository.
from:
```
✖ An error occurred: foo branch or tag not found
```
to:
```
✖ An error occurred: foo branch or tag not found in git+ssh://git@github.com/bar/miniapp.git
```
This makes it clear as to which repository is concerned, in case the function is used in a loop for multiple different repositories (as in the case of `regen-container` command).
> Improve error message

- ern-cauldron-api/src/GitDocumentStore.ts
- ern-core/src/FsCache.ts
Related to `fs-extra` introduction.
Related PRs : https://github.com/electrode-io/electrode-native/pull/1417 and https://github.com/electrode-io/electrode-native/pull/1409
Fix direct `fs.writeJson` calls so that they write JSON file with proper formatting.
> Fix writeJson formatting

- ern-orchestrator/src/container.ts
Quick fix in `runLocalContainerGen` to forward `sourceMapOutput` parameter to `generateContainer` (was missing)
> Fix missing source map output for local containers

- ern-core/src/resolveNativeDependenciesVersions.ts
- ern-core/test/resolveNativeDependenciesVersions-test.ts
Update `containsVersionsMismatch` function to support pre-release packages versions. 
Refactor the function to make it more readable/understandable.
Before this change, the function was throwing an error in case the versions array was containing different pre-release versions.
The function will treat different pre-release versions as mismatching, whichever mismatch level is passed to the function (similar to `patch` mismatch level which will return true if patch/minor or major is different). There is no widely adopted convention for pre-release package versioning, and a different pre-release id might contain a breaking change.
i.e:
```
[ '1.0.0-foo.1', '1.0.0-foo.2' ] => true
[ '1.0.0', '1.0.0-foo.1' ]       => true
['1.0.0-foo.1', ''1.0.0-foo.1' ] => false
```
Unit tests for this …
> Update containsVersionsMismatch function to support prerelease versions

- ern-core/src/android.ts
This updates the jetpack Libraries version to the latest stable release. 
https://developer.android.com/jetpack/androidx/versions
> Align jetpack libraries to the latest stable version

- .vscode/settings.json
- ern-cauldron-api/src/CauldronHelper.ts
- ern-composite-gen/src/Composite.ts
- ern-composite-gen/src/generateComposite.ts
- ern-container-gen-ios/src/IosGenerator.ts
- ern-container-gen/src/copyRnpmAssets.ts
- ern-container-gen/src/populateApiImplMustacheView.ts
- ern-container-gen/src/reactNativeBundleAndroid.ts
- ern-container-gen/src/reactNativeBundleIos.ts
- ern-core/src/BaseMiniApp.ts
- ern-core/src/BundleStoreSdk.ts
- ern-core/src/ErnBinaryStore.ts
- ern-core/src/Manifest.ts
- ern-core/src/ModuleFactory.ts
- ern-core/src/SourceMapStoreSdk.ts
- ern-core/src/YarnLockParser.ts
- ern-core/src/isPackagePublished.ts
- ern-core/src/nativeDependenciesLookup.ts
- ern-core/src/utils.ts
- ern-orchestrator/src/Ensure.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/runContainerPipeline.ts
- ern-orchestrator/src/runContainerPipelineForDescriptor.ts
- ern-orchestrator/src/runMiniApp.ts
- ern-orchestrator/src/start.ts
- ern-orchestrator/src/syncCauldronContainer.ts
- ern-runner-gen-android/src/AndroidRunnerGenerator.ts
- ern-runner-gen-ios/src/IosRunnerGenerator.ts
- package.json
- yarn.lock
Bump TypeScript to `3.7.3` version (latest), along with bumping all TypeScript associated dev dependencies to their latest, for proper [TypeScript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) support.
Please note that the only dev dependency to get a major bump is `pretty-quick`, going from `1.x` to `2.x`. [Only breaking change in 2.x](https://github.com/azz/pretty-quick/releases/tag/v2.0.0) is a strong requirement on Node 8, which is already our minimal Node version requirement, so no issue there.
This PR also contains an update to the vscode workspace settings to use the version of TypeScript installed in the workspace, rather than the one shipped in vscode. This is achieved through [typescript.tsdk](https://code.visualstudio.com/docs/typescript/ty …
> Bump typescript

- ern-composite-gen/src/generateComposite.ts
We noticed that `.json` files are being written to target `assets` directory when using `react-native bundle` command on composite.
This behavior was noticed starting from RN60 upgrade, and is linked to this commit in Metro https://github.com/facebook/metro/commit/dcb41e39f0df6ae1e0b3dfeff9ef5a69128830d5#diff-235a3e5d21175615e1cc254dd8b17eb2 that added `.json` to default assets list to be copied over.
Looks like the problem was experienced by some other users and reported. Imported `.json` files are backed into the JS bundle and therefore shouldn't have to be copied separately because they are not loaded dynamically at runtime (at the difference of images for example). For now the fix is just to override `assetExts` in the `metro.config.js` of the composite, by using all the same asset …
> Exclude json files from being packaged to bundle assets directory

- ern-api-impl-gen/src/ApiImpl.ts
- ern-api-impl-gen/src/generators/android/ApiImplAndroidGenerator.ts
This fixes the file mode of some directories generated by `ern-api-impl-gen`.
The default umask on macOS (and most Linux distributions) is `022`, there should be no need to give _group and world_ the executable bit on those directories. Generated directories will now have the default `755` instead of `777`.
It also removes an unused and unnecessary method related to file permissions.
> Fix file mode of api-impl generated directories

- ern-api-gen/src/DefaultCodegen.ts
- ern-api-gen/src/DefaultGenerator.ts
- ern-api-gen/src/languages/JavascriptClientCodegen.ts
- ern-api-gen/src/models/factory.ts
- ern-api-gen/src/models/properties/ObjectPropertyBase.ts
- ern-api-gen/test/api-test.js
- ern-api-gen/test/fixtures/apis/invalid/empty-property.json
on generating an api, i encountered this:
```
$ ern regen-api
[v0.38.7] [Cauldron: -NONE-]
✔ Syncing https://github.com/electrode-io/electrode-native-manifest.git Manifest 1s
? Would you like to bump the plugin version from [react-native-walmartsmartlist-api@1.8
✔ Syncing https://github.com/electrode-io/electrode-native-manifest.git Manifest 1s
✖ An error occurred: Could not resolve type undefined undefined
```
as you can see, the error message is invalid and not actionable.
additionally,
- regen-api was attempting to set an undefined value if license was omitted
- regen-api was _not_ setting `additionalProperties` appropriately
- regen-api was not handling $refs in additionalProperties
- fix the invalid `parent` reference passed into the function stack that induces the reported error
- …
> fix(ern-api-gen): patch bad object ref, improve error messaging, patch $ref bugs

- docs/cli/create-container.md
- ern-container-gen/src/generateContainer.ts
- ern-container-gen/src/types/ContainerGeneratorConfig.ts
- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/container.ts
Add new `--devJsBundle` option flag to `create-container` command to generate and inject a dev JavaScript bundle in the locally generated container, rather than a production one.
This new flag is part of the `ContainerGeneratorConfig` meaning that it can also be specified in a container generator configuration in Cauldron, to generate containers with a dev JS bundle rather than a production one.
Closes https://github.com/electrode-io/electrode-native/issues/1461
> Add new devJsBundle option to create-container command

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
Semaphore calls were unbalanced, causing the "onReactNativeInitialized" selector to never be called when react native modules were reloaded. This would lead to a scenario where the bridge (RCTBridge) of the ElectrodeBridgeTransceiver could become nil. The semaphore is unnecessary as we do not need to wait for dev menu to be added before other operations occur, so it has been removed.
> CEEMP-1330 Fix electrode container crashes

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
add `Disable/EnableDev` and `Disable/Enable Minification` in dev Menu.
In android react native has a dev menu that allow users to disable/enable dev/minification but in iOS dev option is switched on and minification is switched off. we add two extra dev menu items to toggle these two values.
> iOS - add extra dev menu

- system-tests/tests/create-api-impl-js-fixture.js
- system-tests/tests/create-api-impl-native-fixture.js
Fix a bug that is causing system tests to fail when run locally, under certain conditions (after a local fixture regeneration for api-impl fixtures, `node_modules` directory is created locally -excluded from git- and as it was not excluded from the list of directories to parse to compare files from, it was failing in case the fixture had been regenerated a while back and some node_modules files changed since then).
On another note, noticed through this PR that the files under `system-tests/tests` are excluded from prettier checks. Can see that due to missing trailing comma in arrays. Shouldn't be the case, created issue https://github.com/electrode-io/electrode-native/issues/1474 for follow up on this.
> Fix local run of system tests

- ern-core/src/YarnCli.ts
Fix a bug in `YarnCli:info` method, causing the method, in some conditions, to wrongly reject the promise.
> Fix yarn info bug

- ern-api-impl-gen/hull/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl/ElectrodeBridgeDelegate.h
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl/ElectrodeBridgeDelegate.m
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl/ElectrodePluginConfig.h
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl/ElectrodeReactNative.h
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl/ElectrodeReactNative.m
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl/ElectrodeReactNative_Internal.h
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeBridgeDelegate.h
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeBridgeDelegate.m
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodePluginConfig.h
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeReactNative.h
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeReactNative.m
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeReactNative_Internal.h
This updates the hull code for api-impl gen. The electrode react native interface was outdated. It has been updated with latest code that is currently used in the container gen. Methods that load fonts or are ui related were not included.
> Update api-impl-gen hull for iOS

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
Method is marked as optional, should check if delegate responds to selector before calling.
> Fix crash when calling optional delegate method

- .github/workflows/ci.yml
- README.md
This adds a basic GitHub Actions CI config, running Lint checks and unit tests (using Node.js v10 and v12).
We can just run this in parallel to the existing CI for a while to see how it works out.
> Enable basic GitHub Actions CI

- ern-cauldron-api/src/CauldronHelper.ts
- ern-composite-gen/src/Composite.ts
- ern-composite-gen/src/generateComposite.ts
- ern-container-gen-android/src/AndroidGenerator.ts
- ern-core/package.json
- ern-core/src/HermesCli.ts
- ern-core/src/bugsnagUpload.ts
- ern-core/src/createProxyAgent.ts
- ern-core/src/index.ts
- ern-local-cli/test/logErrorAndExitIfNotSatisfied-test.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/constants.ts
- ern-orchestrator/src/syncCauldronContainer.ts
- ern-orchestrator/test/codepush-test.ts
- yarn.lock
This is the initial integration of [bugsnag](https://www.bugsnag.com/) in electrode native.
When regenerating a cauldron container, or performing a code-push release, if a matching `bugsnag` configuration is found in the cauldron for target descriptor, electrode native will then upload the JS bundle source map -along with associated sources- to the bugsnag server, using [ern-bugsnag-sourcemaps](https://github.com/electrode-io/ern-bugsnag-sourcemaps) library.
It will also generate a unique `codeBundleId` that will be provided in the request to upload the source map. This `codeBundleId` is used by bugsnag to match a bundle to a source map. 
Electrode Native will also set this `codeBundleId` as a process environment variable `ERN_BUGSNAG_CODE_BUNDLE_ID`, prior to composite generation. 
This …
> Initial bugsnag integration

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-core/src/ReactNativeCli.ts
- ern-core/src/bugsnagUpload.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/syncCauldronContainer.ts
Per Bugsnag documentation, it is not needed to upload sources for non Hermes bundles, as the sources referenced in the source map of non hermes bundles are directly inlined inside the source map itself.
This PR ensure that we only upload sources to Bugsnag for Hermes bundles.
> Only upload sources to Bugsnag for Hermes bundles

- ern-local-cli/src/commands/cauldron/add/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/add/miniapps.ts
- ern-local-cli/src/commands/cauldron/batch.ts
- ern-local-cli/src/commands/cauldron/del/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/del/miniapps.ts
- ern-local-cli/src/commands/cauldron/regen-container.ts
- ern-local-cli/src/commands/cauldron/update/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/update/miniapps.ts
- ern-local-cli/src/lib/logErrorAndExitIfNotSatisfied.ts
- ern-local-cli/test/fixtures/common.js
- ern-local-cli/test/logErrorAndExitIfNotSatisfied-test.ts
- ern-orchestrator/src/Ensure.ts
- ern-orchestrator/src/syncCauldronContainer.ts
- ern-orchestrator/test/Ensure-test.js
Container version format rules are too strict for no real strong underlying reason.
It looks like the restriction that any container version should be compliant with semver rules, was only done so that we could feed the versions to semver library for comparison, without causing a crash due to non semver compliance of the versions, but also to make sure that we could auto patch increment the container version upon container regeneration (for non semver compliant versions, there is no such 'patch' version).
Even though, our container version check was even more stricter than what semver allows, just rejecting any versions that wasn't formatted as `[major].[minor].[patch]`.
These are not strong enough reasons to limit container version formatting such drastically. 
Having the ability to use …
> Relax container version format

- azure-pipelines.yml
This PR address the following warning that appeared recently when running our CI pipeline in Azure DevOps:
> ##[warning]This pipeline uses a Microsoft-hosted agent image that will be removed on March 23, 2020 (MacOS-10.13). You must make changes to your pipeline before that date, or else your pipeline will fail
> ##[warning]This pipeline uses a Microsoft-hosted agent image that will be removed on March 23, 2020 (Win 1803). You must make changes to your pipeline before that date, or else your pipeline will fail
Both `MacOS-10.13` and `Win 1803` images have been communicated as deprecated through a [recent blog post](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/). This PR replace the images with proper ones picked from the [official list of …
> Update Azure pipelines hosted images

- ern-composite-gen/src/addRNDepToPjson.ts
- ern-composite-gen/src/addRNStartScriptToPjson.ts
- ern-composite-gen/src/applyYarnResolutions.ts
- ern-composite-gen/src/createBabelRc.ts
- ern-composite-gen/src/createBaseCompositeImports.ts
- ern-composite-gen/src/createIndexJs.ts
- ern-composite-gen/src/createMetroConfig.ts
- ern-composite-gen/src/createRNCliConfig.ts
- ern-composite-gen/src/generateComposite.ts
- ern-composite-gen/src/getNodeModuleVersion.ts
- ern-composite-gen/src/installExtraPackages.ts
- ern-composite-gen/src/installPackages.ts
- ern-composite-gen/src/installPackagesUsingYarnLock.ts
- ern-composite-gen/src/installPackagesWithoutYarnLock.ts
- ern-composite-gen/src/patchMetro51AssetsBug.ts
- ern-composite-gen/src/patchMetroBabelEnv.ts
- ern-composite-gen/src/patchMetroBabelRcRoots.ts
- ern-composite-gen/test/compositegen-test.ts
- package.json
- yarn.lock
Quick refactoring of `ern-composite-gen` module to extract utility functions inlined in `generateComposite` to dedicated files.
This is some prep-work for further refactoring / improvements to this module.
Also includes adding `@types/sinon` to `devDependencies` ... while updating tests post refactoring, I came to notice that new TS policy introduced in https://github.com/electrode-io/electrode-native/pull/1502 also applies to tests source files, so got a lot of red warnings popping in the file as soon as I opened it, even though I didn't realized it before because the tests are explicitly excluded from compilation so no errors caught when running build checks. Will have to look into potentially removing them from exclusion and fix all of them.
> Refactor generateComposite

- ern-local-cli/src/index.dev.js
This PR fixes an issue experienced when using Electrode Native development version (1000.0.0) in some context.
Electrode Native dev version is transpiling TypeScript files on the fly and fails if there is some type issues in any of the source files, based on the rules of the current compiler version and config.
I experienced `ern` failing with such type issues when run from a directory containing a different JS project with it's own `node_modules`. It appears that it was considering some typescript configuration file from the local `node_modules` in some way, rather than the one of Electrode Native project. 
This PR ensure that Electrode Native dev uses `ts-node` and `ts-config-path` from Electrode Native workspace, and also sets the …
> Fix ern dev version issue

- ern-api-gen/package.json
- ern-api-impl-gen/package.json
- ern-cauldron-api/package.json
- ern-composite-gen/package.json
- ern-container-gen-android/package.json
- ern-container-gen-ios/package.json
- ern-container-gen/package.json
- ern-container-publisher/package.json
- ern-container-transformer/package.json
- ern-core/package.json
- ern-local-cli/package.json
- ern-orchestrator/package.json
- ern-runner-gen-android/package.json
- ern-runner-gen-ios/package.json
- ern-runner-gen/package.json
- ern-util-dev/package.json
- global-cli/package.json
- package.json
Related: #1473 #1506 #1507
Part of #1511
With this, all 18 primary `package.json` files in the repo follow a common and standardized formatting and key order.
Some significant simplifications and line savings were achieved by using simple strings instead of full objects for `contributors`. All dependencies were sorted alphabetically.
This PR does _not_ change/update any dependencies or add/remove any fields.
While there is no single authoritative field order for package.json files, several projects exist that aim to provide a "opinionated standard", e.g. [sort-package-json](https://github.com/keithamus/sort-package-json), [fixpack](https://github.com/HenrikJoreteg/fixpack), [prettier-package-json](https://github.com/cameronhunter/prettier-package-json). It's important to point out that …
> Format and standardize package.json files

- system-tests/src/tests/create-api-base-fixture.js
Fix an issue with API system test failing due to differences in the fixture v.s generated API schemas.
This is due to the fact that the fixture regeneration script is using [a fixed schema path](https://github.com/electrode-io/electrode-native/blob/v0.39.0/system-tests/regen-fixtures.js#L116-L118) to regenerate the API, while the system test was not using the same schema path.
This will fix daily system test runs in Azure DevOps pipeline which is currently broken.
> Fix base api system test

- ern-core/src/coloredLog.ts
Add new `log.raw` method which internally will call `kax.raw`.
`raw` logs do not have any level and will be logged whatever current log level is (as long as it's not off, i.e `LogLevel.Off`).
Raw logger can be used to log strings without them being icon prefixed (and colored) based on the log level.
> Add raw logger

- docs/cli/platform/config/set.md
- ern-core/src/config/InMemErnConfig.ts
- ern-core/src/config/JsonFileErnConfig.ts
- ern-core/src/config/index.ts
- ern-core/test/config/InMemErnConfig-test.ts
- ern-core/test/config/config-test.ts
- Look up in parent directories chain to resolve `.ernrc` configuration file
- Add support for some initial placeholders that can be used in `.ernrc` configuration files
With this update, one will be able to get rid of some `ern platform config set` commands especially in CI envs, which was the only way until now to set some configuration keys with a value coming from an environment variable (in our case, this will speed up our CI runs a bit because we won't have to run these commands). 
These changes are also necessary to support upcoming Electrode Native workspaces feature.
> Local config improvements

- ern-core/src/childProcess.ts
Update `spawnp` and `execp` functions, adding support for callers to provide their own loggers for `stdout` and `stderr` streams.
> Update spawnp and execp with configurable loggers

- docs/cli/publish-container.md
- ern-container-publisher/src/publishContainer.ts
- ern-container-publisher/src/types/ContainerPublisherConfig.ts
- ern-local-cli/src/commands/publish-container.ts
- ern-orchestrator/src/runContainerPipeline.ts
Add new `inPlace` option flag to publishers configuration.
This flag, if set, will not copy the container to a temporary directory to run publisher from, but will directly run the publisher from the generated container directory.
This flag is disabled by default to keep current publishers behavior. It can be set as an option to `publish-container` command or directly inside a publisher configuration of a container generator pipeline in the cauldron.
Thing is, for CI environments, where we generate the container and immediately publish it and then trash the workspace, there is no need to go through a temporary copy as we won't run the publishers multiple times on the same container but just once in the context of the job execution. Enabling this flag will allow us to greatly reduce the …
> Add new inPlace option to publishers config

- ern-core/src/bugsnagUpload.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/syncCauldronContainer.ts
Upload to Bugsnag, all sources that are referenced in the source map, even sources from the node_modules, rather than only uploading sources of miniapps.
See https://github.com/bugsnag/bugsnag-sourcemaps/pull/54#issuecomment-594071138 for rationale behind this change.
> Upload all sources to Bugsnag

- ern-local-cli/src/commands/bundlestore/upload.ts
- ern-local-cli/src/commands/cauldron/add/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/add/miniapps.ts
- ern-local-cli/src/commands/cauldron/batch.ts
- ern-local-cli/src/commands/cauldron/del/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/del/miniapps.ts
- ern-local-cli/src/commands/cauldron/regen-container.ts
- ern-local-cli/src/commands/cauldron/update/jsapiimpls.ts
- ern-local-cli/src/commands/cauldron/update/miniapps.ts
- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/container.ts
This PR allows `resetCache` option to be set in a container configuration in cauldron.
The code was previously only considering the `resetCache` option passed on the command line, but ignoring this option in any case if it was set in cauldron.
Logic here, as for other options, is that the option, if explicitly provided on command line, will take precedence over whichever value set in cauldron (if any). If it's not provided on the command line, the value (if any) from cauldron will be used.
Removing default `false` value for this option, in all commands, so that it remains `undefined` if not set, which makes nullish coalescing logic (`??`) properly work.
> Consider cauldron container config for resetCache flag

- docs/cli/start.md
- ern-local-cli/src/commands/start.ts
- ern-orchestrator/src/start.ts
Left over from https://github.com/electrode-io/electrode-native/pull/1520
Add `resetCache` option to `start` command.
> Add resetCache option to start command

- docs/cli/code-push.md
- docs/cli/code-push/patch.md
- docs/cli/code-push/promote.md
- docs/cli/code-push/release.md
A light first-pass update of the code-push cli docs with minor wording/structural improvements.
This fixes all whitespace errors and _most_ markdownlint (_except_ `MD041/first-line-heading` and `MD013/line-length` - both of which will be addressed more broadly in an upcoming doc update)
> Update cli code-push docs

- ern-local-cli/src/commands/bundlestore/upload.ts
- ern-local-cli/src/commands/create-composite.ts
- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/composite.ts
- ern-orchestrator/src/container.ts
- ern-orchestrator/src/runMiniApp.ts
- ern-orchestrator/src/syncCauldronContainer.ts
Hey! 
I was facing the same issue as #1287. 
The path/url specified for the `baseComposite` key in my `config/default.json` file is correctly loaded from the config. However, it's a plain string being passed down and not a `PackagePath` as expected in the [CompositeGeneratorConfig](https://github.com/electrode-io/electrode-native/blob/7b45fec57f4ce860685ea938fcbb31d5992c0f60/ern-composite-gen/src/types/CompositeGeneratorConfig.ts#L2).
I've now solved it by wrapping the path using the `PackagePath.fromString` method, before it's passed in to the composite generation. Would this be the right place to do it?
> Fix custom composite config

- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-orchestrator/src/codepush.ts
Fix a regression with `code-push release` command introduced in `0.40.0` causing `code-push release` command to fail with such an error message
```
An error occurred: No code push entries found for [descriptor] [deploymentName] deployment
```
when performing a code push to a descriptor with no prior code push performed to it.
> Fix CodePush issue

- ern-core/src/CodePushSdk.ts
Fix issue causing `--disableDuplicateReleaseError` flag on `code-push release` and `code-push promote` commands not being considered.
Due to the fact that the code wasn't awaiting on some async method calls, so in case of an exception the catch block was completely skipped (bubbling up to whichever first upstream catch block)
> Fix CodePush disableDuplicateReleaseError flag behavior

- ern-core/src/android.ts
This PR addresses two closely related issues:
A while ago `ANDROID_HOME` was [deprecated](https://developer.android.com/studio/command-line/variables#envar) and replaced with `ANDROID_SDK_ROOT`. For various reasons (mainly backwards compatibility with older versions of the Android Gradle plugin) most people will now have to set **both** variables for the foreseeable future. 🤦‍♂
The problem is that some people might only set one or the other.
With a new function `androidSdkRoot` that returns either `ANDROID_SDK_ROOT` or `ANDROID_HOME`, we now support both (giving the newer `ANDROID_SDK_ROOT` precedence).
Also for quite some time now, the Emulator has been shipped [as its own package](https://developer.android.com/studio/releases/emulator#25-3) - in the `$sdk/emulator/` folder. Historically …
> Fix Android SDK path resolution

- ern-api-impl-gen/src/generators/android/ApiImplAndroidGenerator.ts
- ern-composite-gen/src/GeneratedComposite.ts
- ern-composite-gen/src/WorkspaceComposite.ts
- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-ios/src/IosGenerator.ts
- ern-container-gen/src/generatePluginsMustacheViews.ts
- ern-core/src/Manifest.ts
- ern-core/src/iosUtil.ts
Refactor manifest plugin configuration, getting rid of some verbosity and improve type safety. 
One of the main change is that `getPluginConfig` method now takes the `platform` for which to get configuration of. Therefore, instead of returning the whole `ios` and `android` configuration objects, it only returns the configuration of the requested platform.
This PR is in the context of RN61+ support, as this refactoring is needed to more easily support some needed changes in the manifest plugin configuration in this context. It's been open separately not to pollute RN61+ support PR with such a consequent refactoring.
> Refactor manifest plugin config

- docs/cli/code-push/release.md
- ern-local-cli/src/commands/code-push/release.ts
- ern-orchestrator/src/codepush.ts
Add missing `--baseComposite` option to `code-push release` command.
The logic for this option was already in place in `performCodePushOtaUpdate` method, so it's clear that missed adding this option to this command when this feature was introduced.
Also apply fix from https://github.com/electrode-io/electrode-native/pull/1532 for properly coercing base composite config from cauldron.
> Add baseComposite option to code-push release command

- ern-core/package.json
- ern-core/src/YarnCli.ts
- ern-core/src/childProcess.ts
- package.json
- yarn.lock
Use `spawn` from [`cross-spawn`](https://www.npmjs.com/package/cross-spawn) instead of Node's own `child_process`, due to cross platform compatibility issues running executables/scripts (Linux, macOS, and Windows).
Some more details and background info in this almost 10 year old thread:
https://github.com/nodejs/node-v0.x-archive/issues/2318
This fix is related to an issue found with Yarn on Windows.
Fixes #1527
> Use cross-spawn in ern-core

- ern-orchestrator/src/start.ts
`ern start` bug fixed in https://github.com/electrode-io/electrode-native/pull/1411 started reappearing in ern `0.39.0`. This PR fixes this regression.
Fix will be shipped in patch release `0.40.3`
> Fix a regression of ern start command

- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
Since React Native 52, the dev screen is displayed using the `currentActivity` context instead of using the overlay permission. This PR is to remove the dependency electrode native has added inside the container code. 
Reference: 
https://github.com/facebook/react-native/commit/d19afc73f5048f81656d0b4424232ce6d69a6368
> Remove overlay permission upon app startup in Android

- ern-core/src/ios.ts
- ern-core/test/ios-test.js
Previously `ern run-ios` would only list `iPhone`-type simulators. Now, `iPad` is included as well.
Also fixes a minor wording inconsistency (asking to choose "device" when selecting a simulator).
Fixes #1549
> Include iPad in iOS simulator deployment targets

- ern-orchestrator/src/codepush.ts
Align logic for resolving entry file for `code-push release` command with the one used by composite generator.
Basically, use the platform specific entry file if present (`index.android.js` or `index.ios.js`), otherwise fallback to platform agnostic entry file (`index.js`).
This fixes an issue where only `index.js` is present, which currently causes the `code-push release` command to fail
> Fix entry file resolution for code-push release command

- .github/workflows/ci.yml
- docs/overview/requirements.md
- docs/overview/what-is-ern.md
- docs/platform-parts/cli/index.md
- envalidate.sh
- ern-core/package.json
- ern-core/src/ReactNativeCli.ts
- ern-core/test/android-test.ts
- ern-core/test/ios-test.js
- package.json
Node.js 8 has [reached end-of-life](https://nodejs.org/en/about/releases/) at the end of last year. It is no longer supported, and we're already starting to see issues (#1556). Node.js 14 was released today.
React Native set their minimum Node.js version to 10 [at the end of February](https://github.com/facebook/react-native/commit/f0c7178a3a24e7694b765946f0d884104c8cfa4c).
In order to not run into more dependency and security issues, we need to update as well.
With this, we can also remove `bluebird`, and a no-longer needed workaround from `ReactNativeCli.ts`.
> Set node engine restriction to >=10

- tsconfig.json
- tsconfig.release.json
Now that `ern` has a Node version requirement  of `>=10`, we can bump TypeScript target to `es2018`, fully supported by Node 10, so that TypeScript will emit `es2018` JS code on transpiling.
> Bump TypeScript target to es2108

- ern-core/src/MiniApp.ts
Using `ern add` to add a native module that is not yet supported in the manifest results in the following output :
```
$ ern add foo
✖ foo plugin is not yet supported. Consider adding support for it to the master manifest
ℹ Successfully added foo
```
The problem here is the misinformation given by the last log line. Indeed, the dependency is not added to the package.json of the miniapp in that case. 
Fix is just to throw an error rather that returning from the function, so that caller does not continue execution as if everything went fine.
```
$ ern add foo
✖ An error occured : foo plugin is not yet supported. Consider adding support for it to the master manifest
```
> Throw error rather than log return

- ern-core/src/CodePushSdk.ts
human readable code push error message
Before
```
✖ An error occurred: [object Object]
```
After
```
✖ [performCodePushPromote] Error: {"message":"App not found testAndroid","statusCode":404}
✖ An error occurred: {"message":"App not found testAndroid","statusCode":404}
✖ [performCodePushPromote] Error: {"message":"Deployment Staging:v2 has already been promoted to Production:v2.","statusCode":409}}
✖ An error occurred: {"message":"Deployment Staging:v2 has already been promoted to Production:v2.","statusCode":409}
```
> human readable code push error message

- ern-core/src/Manifest.ts
- ern-core/src/config/index.ts
- ern-core/src/config/resolveLocalErnRc.ts
- ern-core/src/index.ts
- ern-local-cli/src/index.ts
Because of electrode native support for arbitrary .ernrc config location, as well as arbitrary master/override manifest locations, it can quickly become unclear to know which config file is being used by the command, as well as which manifest and where it is being set. This can result in users experiencing issues with some commands, just because for example they overrode a manifest locally and forgot about it, or set a .ernrc in their directory tree, that is being picked up when it shouldn't ... or other random issue.
This PR adds extra information to ern command header, to clearly indicate the location of the .ernrc config file in use, as well as the location of override/master manifest (and where they are set). Each extra information line (config / override manifest / master manifest) …
> Show manifest and config details in ern header

- package.json
- yarn.lock
It doesn't look like this dependency was used. Also, Node.js already ships with npm.
This decreases the size of `node_module` by almost 40 MB! 🎉
> Remove npm dependency

- ern-core/src/MiniApp.ts
- system-tests/src/system-tests-coverage.js
- system-tests/src/system-tests.js
A couple of small improvements here.
Previously, when there was a mismatch in the transitive dependencies of a miniapp, it would output a misleading error message, e.g.
```
[Transitive Dependency] react-native-electrode-bridge was not added to the MiniApp
```
Now, the error message is more accurate and provides more information:
```
Version of transitive dependency react-native-electrode-bridge@1.5.24
does not match version declared in manifest: 1.5.23
```
Also improved the `system-tests.js` script:
`--all` is no longer required (instead, it will run all tests by default). If interactive mode is desired, it's still possible using the `-i/--interactive` flag. New is the possibility to pass individual test files to run, e.g.
```
yarn test:system create-api-complex-fixture misc
```
This …
> Improve error message and system tests script

- docs/cli/code-push/promote.md
- ern-local-cli/src/commands/code-push/promote.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/test/codepush-test.ts
- ern-util-dev/fixtures/default-cauldron-fixture.json
Moving forward we'd skip the native dependencies alignment checks during the code-push promotion 
- if the source and target app version is the same during the code-push promotion of the bundle. As the native dependencies alignment check is already done during the code-push release.
-  if the source and target app version is different and one needs to skip native dependencies alignment check, pass the `skipNativeDependenciesVersionAlignedCheck` as `true`.
> skip native dependencies check during code push promote

- ern-core/src/iosUtil.ts
[Directory name](https://github.com/electrode-io/electrode-native/tree/master/ern-container-gen-ios/src/hull/Config) is `Config` instead of `config`
> Fix directory name casing

- ern-local-cli/src/index.ts
`ern --version` can be used to display the global CLI / local CLI version.
The problem with prior implementation was that some commands are exposing a `--version` option. For example `publish-container` has a `--version` option to specify the version to use for the container. When using `--version` on `publish-container` was leading to the command being short circuited and the version of the platform shown instead. Only workaround was to use the shorthand `-v` option of `publish-container` command.
This PR fixes this issues, by only displaying version of ern when using `ern --version`, and not when `--version` is an option present on any arbitrary command line.
> Fix version option of ern command

- ern-local-cli/src/commands/publish-container.ts
`--inPlace` option was defined in command options but not handled at all in command implementation.
> Add missing handling of inPlace option in publish-container command

- ern-local-cli/src/commands/run-ios.ts
Very quick one to update platform error message of `run-ios` command to make the wording on par with the error message introduced in https://github.com/electrode-io/electrode-native/pull/1575
> Update run-ios error message

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
erndelegate shouldn't be required in swift, this will also surpress null warning on objective c
> ERNDelegate should be nullable, optional in swift

- ern-core/src/ios.ts
- ern-core/test/ios-test.js
Quick PR that adds the sdk (i.e. iOS version) to simulators in the interactive prompt shown for `ern run-ios`. Previously it was only displayed for devices.
We now also have a **consistent** output format (not only between devices and simulators, also with how devices are listed using `xcrun instruments -s`)
Sample output:
```
? Choose an iOS simulator
iPad (5th generation) (10.3) [17043F85-C66D-405F-8D13-38460DEF27B6]
iPad Pro (12.9-inch) (2nd generation) (10.3) [6B94537E-0E7C-4293-982F-BC12A7A3268D]
iPad Pro (10.5-inch) (10.3) [28463F95-C420-429B-94D0-B25FD23049D1]
❯ iPhone 7 (13.4) [F200BD5C-77CE-48D5-A2D0-FA952723A381]
iPhone 8 (13.4) [8ED6419D-7069-46C9-9531-32BC60C0D107]
iPhone 8 Plus (13.4) [535A2C2F-F20E-4069-A5B4-95A7567B0F1E]
iPhone 11 (13.4) …
```
> Add sdk to iOS simulator list

- ern-core/src/IosPluginConfigGenerator.ts
Use single-star `*` glob pattern rather than double-star `**` by default when generating iOS plugin configuration.
Copying with the `**` leads to a messed up flattened file structure, which makes the resulting target directory ugly and polluted with unnecessary files, but can also lead to some side effects causing container generation to fail.
> Fix an issue in ios plugin config generator

- ern-cauldron-api/src/getActiveCauldron.ts
- ern-local-cli/src/index.ts
Quick improvements and fixes around new ern info header introduced in https://github.com/electrode-io/electrode-native/pull/1572 
- Avoid polluting the info header with `connecting to cauldron` log, mixed in between info header lines, by adding a silent flag to `getActiveCauldron` function.
- Rethrow exception from `getActiveCauldron` rather than exiting the process. Our top level command handlers are anyway doing that, so there was no reason to exit process here. Moreover, this allow the info header to gracefully handle a connection error with the cauldron, by just notifying an informational message `Cannot reach Cauldron` rather than throwing and existing the process. This is also a fix in a way, because if the cauldron was unreachable (for example connected to an internal cauldron …
> Improvements and fixes around new ern info header

- ern-api-impl-gen/hull/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl.xcodeproj/xcshareddata/xcschemes/ElectrodeApiImpl.xcscheme
- ern-api-impl-gen/hull/ios/ElectrodeApiImpl.xcworkspace/contents.xcworkspacedata
- ern-api-impl-gen/src/generators/ios/ApiImplIosGenerator.ts
- ern-core/src/iosUtil.ts
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl.xcodeproj/xcshareddata/xcschemes/ElectrodeApiImpl.xcscheme
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl.xcworkspace/contents.xcworkspacedata
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/Podfile
- system-tests/fixtures/ios-container/Podfile
- system-tests/fixtures/ios-container/Podfile.lock
Fix issue with iOS native api implementation project generation (`create-api-impl` command) when using a version of react native >= 0.61.0.
This issue was surfaced through system test failure.
This PR updates the API implementation iOS project hull as well as the generation logic, to properly support RN61+.
**EDIT** :  System tests ✅
> Fix iOS native api implementation project generation with RN61+

- ern-container-gen-ios/src/IosGenerator.ts
- system-tests/src/tests/create-container-ios-fixture.js
- system-tests/src/tests/misc.js
Now that CocoaPods is required for iOS container generation, macOS is a requirement. It'll fail on Linux and Windows:
```
spawnp => command: pod args: ["install"] options: {}
[ Running pod install (Failed) ]
popd
/tmp/tmp-5319hpxSXui6YFVV /tmp/tmp-5319hpxSXui6YFVV
popd
/tmp/tmp-5319hpxSXui6YFVV
[ Generating Container (Failed) ]
[ Generating Container locally (Failed) ]
✖ An error occurred: spawn pod ENOENT
Error: spawn pod ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
at onErrorNT (internal/child_process.js:415:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
```
With this PR we're checking the platform and error earlier with an error message, instead of failing later on.
Note: While CocoaPods itself (the `pod` command) does appear to …
> Fix system tests and improve error messaging

- ern-api-gen/src/java/ServiceLoader.ts
Allow `ServiceLoader` to read all available code generators in `META-INF/services` regardless of the line endings used in file that declares them (`io.swagger.codegen.CodegenConfig`).
Note: ServiceLoader is not part of Swagger, but a reimplementation/mockup of Java's own [`java.util.ServiceLoader`](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html).
Previously, this would fail if `os.EOL` returns something other than the actual line ending marker (`LF`) used. For example on Windows (where `os.EOL` returns `CRLF`), `load` would return _one_ long string instead of 7 individual items, because none of the lines are recognized:
```
1) CodegenConfigurator
should do something async:
Error: Can't load config class with name android Available:
at Object.forName …
```
> Fix ern-api-gen ServiceLoader file handling

- docs/platform-parts/manifest/native-modules.md
- ern-container-gen-ios/src/IosGenerator.ts
Add `.xcassets` resources (xcode asset catalogs) injection support to iOS container.
> Add .xcassets resources support to iOS container

- ern-composite-gen/package.json
- ern-composite-gen/src/generateComposite.ts
Throw an error when generating a composite that includes local miniapps, if there happens to some some native module(s) versions mismatch.
This PR follows an issue that was identified in `0.41.0`, when using `ern start` with some local miniapps using mismatched native modules version, resulting in some obscure packager error. Better to fail early in this case, with a clear error message.
**Sample error output**
```
✖ An error occurred: Mismatching native module versions detected.
✖ Native module(s) versions should be aligned across miniapps.
✖ You should resolve the following version mismatches prior to retrying.
✖ ┌──────────────────────────────────────────────────────────────┬─────────┐
✖ │ path                                                         │ version │
✖ …
```
> Throw an error on mismatching native module versions

- ern-local-cli/scripts/postinstall.js
Just get the version directly from the `package.json`.
Once merged will remove extra cumbersome steps in [release process wiki page](https://github.com/electrode-io/electrode-native/wiki/New-platform-version-release-process) to manually edit the version prior to each release, which won't be needed anymore.
> Update ern-local-cli postinstall script

- ern-orchestrator/src/start.ts
After https://github.com/electrode-io/electrode-native/pull/1532 and https://github.com/electrode-io/electrode-native/pull/1544 I found one more place where the `baseComposite` wasn't wrapped into a `PackagePath`
> Fix baseComposite option for start command

- ern-composite-gen/src/generateComposite.ts
- ern-core/src/resolveNativeDependenciesVersions.ts
Fix a conditional logic bug in `resolveNativeDependenciesVersions.ts` which was causing non major mismatching bridge versions to be invalidly considered as mismatching, leading to potential issues when using `ern start`.
Also, add latest version of the bridge to top level composite, for packager to properly resolve it (and avoid using a random version potentially locked by one of the miniapps).
> Fix conflicting bridge version

- ern-core/src/Platform.ts
- ern-core/test/Platform-test.ts
This fixes: https://github.com/electrode-io/electrode-native/issues/1611
**Root cause**
The `yarn add` command on [this](https://github.com/electrode-io/electrode-native/blob/889074ee62b6899690066ba3c2c9450591970e81/ern-core/src/Platform.ts#L118) line fails silently (but the `ern platform install` operation is marked as successful) because there's no `package.json` in the current folder.  
**Solution**
The initial platform version (the latest) is fetched correctly because it's an entirely different code path ([here](https://github.com/electrode-io/electrode-native/blob/889074ee62b6899690066ba3c2c9450591970e81/global-cli/src/index.js#L85)). For now I've just copied the relevant line but it might be even nicer to unify the platform installation code paths. However, I couldn't figure out …
> Fix platform installation

- ern-api-gen/resources/swift/libraries/ern/apidatamodel.mustache
- ern-api-gen/resources/swift/libraries/ern/model.mustache
- system-tests/fixtures/api/complex-api/IOS/ErnObject.swift
- system-tests/fixtures/api/complex-api/IOS/NavBarButton.swift
- system-tests/fixtures/api/complex-api/IOS/TestMultiArgsData.swift
- system-tests/fixtures/api/test-api/IOS/Item.swift
SwiftLint and/or SwiftFormat accidentally removed `self.` from api swift templates, which was merged in #1420
This re-adds them.
> Re-add missing self properties

- package.json
- yarn.lock
* **publish:** Canary releases without previous tags should not explode ([c9eb590](https://github.com/lerna/lerna/commit/c9eb590bf867889a188598322bb4552db7a34dfc))
* **project:** Add `getPackagesSync()` export ([068bdd7](https://github.com/lerna/lerna/commit/068bdd75683ca9687a420523e4ba007bd8b3b220))
* **version:** Ignore private packages completely with `--no-private` ([a9b9f97](https://github.com/lerna/lerna/commit/a9b9f97457e4e4b0cac7f4ce562458d921a1f9be))
> Update lerna to 3.21.0

- .github/workflows/ci.yml
Extend GitHub Actions CI matrix with additional platforms, and also run `yarn build`.
Instead of just `ubuntu-latest`, with this we're now also running build+unit tests on `macos-latest` and `windows-latest`. Node.js matrix [10, 12, 14] we'll keep on Linux only for now, macOS and Windows are using Node.js 12.
`yarn check:lint` only runs on Linux/Node.js 12.
The new config will yield 5 different jobs, all running in parallel.
> Add build step and more platforms to CI

- ern-api-gen/package.json
- ern-api-gen/src/java/MustacheWriter.ts
- ern-api-impl-gen/package.json
- ern-api-impl-gen/src/generators/android/ApiImplAndroidGenerator.ts
- ern-api-impl-gen/src/generators/ios/ApiImplIosGenerator.ts
- ern-composite-gen/package.json
- ern-container-gen/package.json
- ern-core/package.json
- ern-core/src/mustacheUtils.ts
- ern-runner-gen-android/package.json
- ern-runner-gen-ios/package.json
- package.json
- yarn.lock
Despite being a "major" version upgrade, [the changelog](https://github.com/janl/mustache.js/blob/master/CHANGELOG.md) mainly lists internal improvements. There aren't any breaking api changes, at least the ones we're using. They also mention
> Majority of using projects don't have to worry by this being a new major version.
Overall, I felt a slight (maybe subjective) performance improvements locally. There are no changes to any of the generated fixtures (as expected).
The second one is the more interesting:
[Partials](https://github.com/janl/mustache.js/#partials) are now supported in the two exported methods of `mustacheUtils`.
This also lifts some unnecessary restrictions that were previously enforced in `ern-api-impl-gen`: It was processing the resource directory under the assumption …
> Update Mustache and add support for partials

- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/syncCauldronContainer.ts
Do not upload sources for Android Hermes bundles.
Recently this started causing huge payload sizes, ultimately failing to be uploaded to BugSnag with and HTTP 500 error.
Looking at the source map, I can see that it references a bunch of files that are not sources (images, json ...). Given that all sources files referenced by the source map are uploaded, this is what probably causes the huge resulting payload size. Not sure why the generated source map references such non source files (sure they are imported in the code, but should not be accounted for in the source map), maybe it's some kind of issue with react native source map generation for Hermes bundles, or just some configuration issue.
This is a hotfix directly targeting 0.41. branch, to be released in 0.41.5. Not targeting master …
> Fix bugsnag upload issue

- system-tests/src/tests/create-container-android-fixture.js
- system-tests/src/tests/create-container-ios-fixture.js
Tiny PR, just adding `yarn.lock` to the exclude list of the container fixture tests. 4 of the 6 fixture tests already had the file in the ignore list. Without this, it could lead to local test failures.
> Exclude yarn.lock from container fixtures check

- system-tests/src/regen-fixtures.js
Trying to regenerate all fixtures (including the iOS container fixture) on Linux or Windows results in the whole directory being deleted. iOS container generation is only supported on macOS, so this avoids running the command on non-macOS.
> Do not try to regen iOS fixtures on non-darwin

- CONTRIBUTING.md
- README.md
- docs/README.md
- global-cli/src/index.js
- setup-dev.js
This simplifies the initial installation process with two small but significant improvements:
Now it is possible to override the initial version of ERN (i.e. `ern-local-cli`) that is downloaded on a new system (no previous `.ern` folder) using the environment variable `ERN_INITIAL_VERSION`. This is especially useful on CI systems and/or in combination with specifying a custom `ERN_HOME`.
Previously, we had the rather unusual requirement to run `ern` (without arguments) at least once after globally installing `electrode-native`:
```
npm install -g electrode-native && ern
```
This is no longer necessary. Any arguments passed to the first invocation of `ern` are now automatically passed to `ern-local-cli` _after_ the initial install. This reduces first time use friction and standardizes …
> Improve initial installation process

- ern-local-cli/src/commands/create-miniapp.ts
- system-tests/src/tests/misc.js
Deprecate `--packageManager` flag of `ern create-miniapp`. Yarn is used by default. This can be overridden using the new `--npm` flag (just like RN).
Most importantly, it removes the extra prompt if `--packageManager` is _not_ specified on command line.
> Deprecate --packageManager flag of create-miniapp

- ern-api-gen/package.json
- ern-core/package.json
- ern-util-dev/package.json
- package.json
- yarn.lock
0.8.4 includes https://github.com/shelljs/shelljs/commit/05374a749992969bb6b853095f4c9308df69aa82 which fixes a bunch of warnings we keep getting when using Node.js 14:
```
(node:54809) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54809) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:54809) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:54809) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:54809) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:54809) Warning: …
```
> Update shelljs to 0.8.4

- global-cli/package.json
A couple of small updates in preparation for `global-cli@1.1.0`:
- Update `main` value (should _not_ start with `./`, otherwise the default npm packing method won't automatically include the file)
- Add `files` array to explicitly declare items to be published (this guards against the possibility of accidentally publishing untracked files in the directory)
> Use files array in global-cli package.json

- global-cli/package.json
Lower node engine restriction in `global-cli` from 10 to 8.
Reason: The global CLI is a standalone package (with currently no strict requirement for Node 10+), and it can also be used by people still using an _older_ version of ERN (using `ERN_INITIAL_VERSION` on first install). This improves backwards compatibility on CI.
> Set node engine restriction in global-cli to >=8

- ern-runner-gen-android/test/AndroidRunnerGenerator-test.ts
- ern-runner-gen-android/test/regen-fixtures.ts
- ern-runner-gen-ios/test/IosRunnerGenerator-test.ts
- ern-runner-gen-ios/test/regen-fixtures.ts
Major simplifications and partial rewrite of both test cases and `regen-fixtures` scripts of `ern-runner-gen-android` and `ern-runner-gen-ios`.
In preparation for the hull updates in the runner projects.
> Update runner-gen tests

- azure/templates/system-tests.yml
Forgot to take out these steps 🤦 
With 1.1.0 of global-cli it is no longer necessary to explicitly install the local cli. `ern` without arguments will now _always_ return 1 (including the very first time it is called).
> Fix azure system tests

- ern-container-gen-ios/src/IosGenerator.ts
- ern-core/src/iosUtil.ts
Noticed that the iOS plugin configuration `podspec` directive wasn't properly working.
Two problems here:
- The `podspec` file was copied to the wrong directory (container dir instead of plugin directory in composite node modules). Fixed by updating destination directory with proper one.
- When generating the container, `yarn add` of the community cli in container dir was done after the copy of all composite native modules to the `node_modules` directory of container dir. Because we are adding all native modules to container package.json prior to running this `yarn add`, this was reinstalling all modules, including the ones that were patched with podspec directive (so overwriting the changes). The fix here is just to reorder things, and run any `yarn add` in the container prior to copying …
> Fix podspec ios directive

- ern-core/src/resolveNativeDependenciesVersions.ts
First bug is that under some circumstances, electrode native would behave incorrectly, leading to an error when generating a composite. The problem was the use of `_.map(entry, 'version')` to map an array of packages to their versions. In case of a package used across multiple miniapps with the same version, the resulting array looked like `['1.0.0', '1.0.0']` for example, going into the conditional block handling multiple different versions of the dependency, instead of going through the conditional where only one version is used. The fix here is just to apply `_.uniq` on the array, to only keep unique versions (so `['1.0.0,  '1.0.0']` collapse to `['1.0.0']` and the right conditional is entered). 
```
if (pluginVersions.length > 1) {
// If there are multiple versions of the dependency …
```
> Fix two bugs in resolveNativeDependenciesVersions

- ern-core/src/createProxyAgent.ts
With this small change, the `createProxyAgentFromErnConfig` function now supports the `http_proxy` and `https_proxy` environment variables in addition to the existing support for config keys from the ern config (currently `bundleStoreProxy`, `bugsnagProxy`, or `sourceMapStoreProxy`).
The config keys still take precedence, so if one is set, this PR won't affect the existing behavior.
> Add support for http_proxy env variables

- system-tests/fixtures/android-container/container-metadata.json
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeBridgeHolder.h
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeBridgeHolder.m
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeBridgeTransceiver.m
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl/ElectrodeReactNativeBridge/ElectrodeLogger.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNativeBridge/ElectrodeBridgeHolder.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNativeBridge/ElectrodeBridgeHolder.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNativeBridge/ElectrodeBridgeTransceiver.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNativeBridge/ElectrodeLogger.m
- system-tests/fixtures/ios-container/container-metadata.json
- system-tests/fixtures/ios-container/package.json
Following `react-native-electrode-bridge` version update to [v1.5.25](https://github.com/electrode-io/react-native-electrode-bridge/releases/tag/v1.5.25)
> Regenerate system test fixtures

- docs/cli/cauldron/repo/add.md
- ern-cauldron-api/src/CauldronRepositories.ts
- ern-core/src/createProxyAgent.ts
- ern-local-cli/src/commands/cauldron/repo/add.ts
This adds a new `--force`/`-f` option to the `ern cauldron repo add` command, allowing the user to overwrite an existing alias with a new value, without the need to remove it first.
```
// ('test-cauldron' alias already exists)
$ ern cauldron repo add test-cauldron /tmp/cauldron
✖ An error occurred: A Cauldron repository already exists with test-cauldron alias
$ ern cauldron repo add -f test-cauldron /tmp/cauldron
ℹ Added Cauldron repository /tmp/cauldron with alias test-cauldron
```
> Allow "cauldron repo add" to overwrite alias

- ern-composite-gen/src/createMetroConfig.ts
Path names on Windows that contain backslashes need to be escaped before they are put in `metro.config.js`, otherwise they are interpreted as control characters.
Verified this locally generating a new miniapp and composite on Windows 10.
Fixes #1586
> Fix watch folder path escaping on Windows

- ern-core/src/PackagePath.ts
Add missing conditional to handle windows package file path .
This fixes an issue with local scoped packages paths such as `C:\Users\foo\app\node_modules\@scope\package` that were then incorrectly entering the registry package. path conditional (i.e `foo@1.0.0`), leading to errors down the line.
> Fix scoped local package path on windows

- ern-composite-gen/src/generateComposite.ts
- ern-orchestrator/src/start.ts
Kinda follow up to https://github.com/electrode-io/electrode-native/pull/1666
`blacklistRe` paths in `metro.config.js` are not generated properly on Windows.
For example, this is how a path will currently look like when generated `/C:\foo\node_modules\react-native\/.*/`, while valid path should instead be `/C:\\foo\\node_modules\\react-native\\.*/`
To be noted that there is some duplication here (in `start` and `generateComposite`), not limited to this line. Some refactoring should be done. Not part of this PR only addressing this issue with minimum changes, for patch release.
> Fix metro config blacklistRe generation on Windows

- ern-runner-gen-android/src/hull/app/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/build.gradle
These `packagingOptions` are part of the default RN 0.62.2 template:
https://github.com/facebook/react-native/blob/v0.62.2/template/android/app/build.gradle#L167
Without them `ern run-android` in a miniapp may fail, forcing repo owners to modify and commit the generated `android` folder to source control.
> Add packagingOptions to android runner build

- ern-cauldron-api/src/CauldronApi.ts
Not much in this PR in term of code changes actually but it will improve tracking of `yarn.lock` files.
This PR updates the `updateYarnLock` method, for it not to create a new yarn lock file in the cauldron but instead reuse the existing one (by just overwriting it).
I am not sure why in the first place this method was implemented this way, but it was a mistake.
Just to give some context here ... 
When Electrode Native generates a container using a cauldron, it stores the resulting `yarn.lock` file inside the cauldron (under `yarnlocks` directory). The filename that is used to store this `yarn.lock` is a generated UUID, for example `0b3877c3-51d2-4090-95cb-2e8547258d9b`. The problem with current `updateYarnLock` method is that it first removes the previous yarn lock file (UUID) associated …
> Reuse yarn lock files instead of creating new ones

- ern-container-gen-ios/src/IosGenerator.ts
- ern-orchestrator/src/container.ts
Follow up to https://github.com/electrode-io/electrode-native/pull/1662
Late changes to this PR were not tested before merge (my bad)
There was a bug in case the iOS extra configuration is not provided, were the code would fail (trying to access skipInstall property on undefined object).
Also in case of container generation from Cauldron, the extra iOS configuration was not retrieved from Cauldron.
This PR addresses these two issues.
> Fix iOS skipInstall

- docs/cli/create-miniapp.md
- ern-core/src/MiniApp.ts
- ern-core/src/ReactNativeCli.ts
- ern-local-cli/src/commands/create-miniapp.ts
Similar to how we now have a `--skipInstall` for `create-container` (#1662), this adds the `--skipInstall` to `create-miniapp`. Does a similar thing, and in this case, simply passes through the `--skip-install` flag to the React Native CLI.
> Add --skipInstall option to create-miniapp

- system-tests/src/tests/create-container-ios-fixture.js
Remove expected failure exit code now that we use `--skipInstall` flag for the iOS `create-container` command, which will cause it to end with success even on Windows/Linux.
> Fix system tests on Windows/Linux

- ern-composite-gen/src/installPackagesUsingYarnLock.ts
- ern-composite-gen/src/miniAppsDeltasUtils.ts
- ern-composite-gen/test/compositegen-test.ts
When reusing a composite `yarn.lock` _(`bypassYarnLock=false`)_ use `yarn add` instead of `yarn upgrade` to update MiniApp versions.
When reusing `yarn.lock` we want to ensure that the new composite dependency graph remains as close to the previous one as possible. The problem with `yarn upgrade` is that it will refresh the whole dependency graph of the miniapp updated to a new version; retrieving latest versions of dependencies matching the defined ranges, even if no top level dependencies (in the miniapp package.json) were explicitly updated.
For example, assuming a miniapp has the following dependencies in its package.json:
```
"dependencies": {
"depA": "^1.0.0",
"depC": "^1.0.0"
}
```
The resulting resolved dependency tree might look like this (assuming depA is having a dependency on …
> Use yarn add instead of upgrade when reusing yarn.lock

- ern-util-dev/bin/ern-mocha.js
We have noticed some tests randomly failing, running into timeout, when run on GitHub actions agents.
This PR increase mocha test timeout to 5s _(from the default of 2s)_ which should greatly reduce the amount of random failures due to timeouts (let's keep an eye on this after merge).
> Increase mocha test timeout

- ern-composite-gen/src/createMetroConfig.ts
- ern-composite-gen/src/generateComposite.ts
- ern-composite-gen/test/compositegen-test.ts
Add out of the box `svg` file import support for full composites, using [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer).
Also includes a formatting fixes to the changed file (minimal, not using two commits here).
> Add svg import support

- ern-composite-gen/src/GeneratedComposite.ts
Some code was added recently to this function to deal with local MiniApps separately, due to the refactoring of full composite generation. In the case of non full composite (using base composite), we noticed that. each local miniapps gets injected twice  in the container, resulting in container build failure.
Fix is just not to update the conditional not to consider file based path.
> Fix a bug causing local miniapps to be included twice in container

- ern-local-cli/src/commands/platform/config/set.ts
Fix `platform config set` command when setting object values.
For example, running in `ern platform config set manifest '{"override": {"url": "/Users/foo/bar"}}'` currently results in a stringified version of the object to be set as the value:
```json
{ "manifest": "{\"overrride\": { \"url\": \"/Users/foo/bar\"}}" }
```
With this PR fix, the object itself will be properly set as the value:
```json
{
"manifest": {
"override": {
"url": "/Users/foo/bar"
}
}
}
```
> Fix "platform config set" command for object values

- ern-container-gen-android/src/hull/build.gradle
- ern-core/src/android.ts
- system-tests/fixtures/android-container/build.gradle
The update of the Android Gradle plugin in the container from `3.4.0` to `3.5.2` is causing some unexpected regressions. In certain project setups, it might result in the following container build error:
```
More than one file was found with OS independent path 'classes.jar'
```
Other people have faced similar issues, and there is no simple fix available.
https://stackoverflow.com/questions/57725323/more-than-one-file-was-found-with-os-independent-path-classes-jar-com-andro
https://github.com/gradle/gradle/issues/10882
It will most likely require some extended investigation to figure out exactly what's going wrong and what the proper fix will look like.
This reverts the update, and instead changes the default version from `3.4.0` to `3.4.2`, keeping the container plugin at the `3.4.x` …
> Revert "Set Android container Gradle plugin to 3.5.2"

- ern-cauldron-api/src/CauldronRepositories.ts
- ern-core/src/index.ts
- ern-core/src/sortObjectByKeys.ts
- ern-core/test/sortObjectByKey-test.ts
I have a lot of cauldron repositories in my local setup and when using `ern cauldron repo list` I started having some difficulty finding a particular cauldron repo alias, as they are not sorted.
This PR keep the `cauldronRepositories` object (in `.ernrc`) sorted (prior to object update, its keys get sorted), so that `ern cauldron repo list` now list the repositories sorted by alias. Because the logic is sorting the object keys prior to writing it to `.ernrc`, the `.ernrc` file will also contain the `cauldronRepositories` object with its keys sorted.
> Keep cauldron repositories sorted

- ern-composite-gen/src/createIndexJs.ts
- ern-composite-gen/src/generateComposite.ts
The order of miniapps imports in composite `index.js` was not deterministic, which could lead to some issues in the case of miniapps having to be imported before other ones (should never be the case, still).
This PR achieves the necessary to guarantee deterministic miniapps imports order.
To avoid introducing any additional configuration complexity, the order of imports will exactly match the order of the miniapps as defined in cauldron (when generating a composite from cauldron), or the order of the miniapps provided on command line (when generating a composite with a command taking arbitrary miniapps paths).
> Guarantee miniapps import order in composite

- ern-core/src/android.ts
Prep work for React Native 0.63 support
[Hermes engine was updated to 0.5.0 in React Native 0.63.0](
https://github.com/facebook/react-native/commit/4305a291a9408ca65847994bbec42f1fbc97071d)
This PR updated the default version of Hermes used by Electrode Native for RN63+, to `~0.5.0` matching [range used by React Native](https://github.com/facebook/react-native/blob/v0.63.0/package.json#L98).
> Set default hermes version for RN63+

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeBridgeDelegate.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeBridgeDelegate.m
Using weak reference for delegate properties is standard Objective C practice. Also, copy for immutable arrays.
> Remove strong references for delegates

- ern-core/src/android.ts
- ern-core/test/android-test.ts
Fix very silly bug introduced in https://github.com/electrode-io/electrode-native/pull/1688 that could have been caught easily by unit tests. But there was no unit tests for this function, so adding some as well so that this does not happen again next time ;)
> Fix hermes default version for RN63+

- ern-container-gen-ios/src/IosGenerator.ts
Scoped native modules packages are not copied to the proper destination in iOS container `node_modules` directory. 
For example `node_modules/@foo/bar` is currently copied into `node_modules/bar`
This issue doesn't cause container generation to fail _(which explains in part why it was only noticed now),_ but the CocoaPods of all such scoped modules are just not injected in the generated container.
This PR fixes this problem.
> Fix RN61+ iOS container issue with scoped packages

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
Fixes missing semicolon in miniappview interface.
Also improper syntax is color method signature.
> Fix typo in miniappview interface

- ern-container-gen-ios/src/hull/.gitignore
When generating a complete (installed) container with ern (pod install being run), we don't want to exclude the Pods directory when publishing the container to a git repository.
Indeed, a complete iOS container published to git, should be 'buildable' fresh from a git clone, without having to run `yarn install` nor `pod install`.
Having this directory in the .gitignore of the iOS container, was causing such containers to fail building out of the box when cloned from the git repository.
> Remove Pods directory from iOS container gitignore

- ern-container-gen/src/copyRnConfigAssets.ts
- ern-container-gen/test/fixtures/CompositeWithRnConfigs/package.json
An issue was found in `copyRnConfigAssets` function on iOS, that would cause assets injection to be done twice (first by ern, adding the resources directly to Container resources, and second, during pod install, as podspec contains resources injection statements), leading in some edge cases to container build failing because of resource duplication.
Fix here only applies for iOS and if a version of React Native >= 0.61 is used. If that's the case, ern will skip copying assets of packages that contain a podspec file, as they will be copied over by pod install.
> Fix copyRnConfigAssets for iOS on RN61+

- ern-core/src/ReactNativeCli.ts
`ern start` command currently fails with `ENOENT` error when run from Windows.
This PR fixes this issue.
> Fix ern start command on Windows

- ern-local-cli/src/commands/cauldron/add/nativeapp.ts
- ern-local-cli/src/commands/create-container.ts
- ern-local-cli/src/commands/publish-container.ts
- ern-local-cli/src/commands/run-android.ts
- ern-local-cli/src/commands/transform-container.ts
`--extra/-e` option of some commands is highly prone to errors as its value can a JSON literal or a JSON file, that can be easily malformatted in some way. 
In that case, `ern` currently fails with somewhat obscure error `An error occurred: [parseJsonFromStringOrFile] Invalid JSON or file` which might not immediately lead the user to understand that something is wrong with the `extra` option value being provided.
This PR just improves the error message in case of an issue parsing the `extra` option value.
> Improve error message of extra option

- ern-api-gen/package.json
- ern-api-gen/src/java/File.ts
There was only a _single_ (direct) dependency on `mkdirp` left in our code base. This removes it and replaces it with (now) built-in functionality of `fs`.
> Remove mkdirp

- ern-api-gen/resources/swift/libraries/ern/model.mustache
Fix a bug in iOS API generator that is producing invalid swift file when using an array of primitives as an object property type.
For example, defining an object `foo` with a `bar` property being a string array, as depicted by the following schema:
```json
{
"foo": {
"type": "object",
"properties": {
"bar": {
"type": "array",
"items": {
"type": "string"
}
}
}
}
}
```
Is currently resulting in the following Swift code to be generated :
```objc
NSObject.generateObject(data: dictionary["bar"], classType: [Any].self, itemType: .self)
```
Instead of 
```objc
NSObject.generateObject(data: dictionary["bar"], classType: [Any].self, itemType: String.self)
```
The issue is not limited to string array type, but any array of primitive type is resulting in the same invalid generation.
This PR fixes …
> Fix iOS API generator for arrays of primitives

- system-tests/fixtures/api/complex-api/IOS/ErnObject.swift
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complexapi/ern/model/ErnObject.java
- system-tests/fixtures/api/complex-api/schema.json
- system-tests/fixtures/api/complexapi-schema.json
Follow up to https://github.com/electrode-io/electrode-native/pull/1707
Add the following properties to `ERNObject` to complex API schema  
- `stringArray`
- `integerArray`
- `booleanArray`
to properly cover generation of some basic arrays of primitive types.
Obviously,  also regenerate system test fixtures 😉
> Add more properties to system test api schema

- docs/platform-parts/manifest/native-modules.md
- ern-container-gen-android/src/AndroidGenerator.ts
Rather than introducing a new specific prefix for all type of dependencies statements as we started doing, this PR is adding a new `freeeform:` prefix for dependencies, to inject any arbitrary dependency string, allowing to cover all possible current and future needed dependency literal formats.
> Add raw dependencies support to Android plugin configuration

- ern-cauldron-api/src/CauldronRepositories.ts
Allow regular https-style urls with the `ern cauldron repo add` command.
1. There is no technical reason to only allow ssh urls or https with user/pass/token
2. Using a native credentials helper of the operating system is preferred over embedding credentials in the url
3. ERN works just fine with plain https url (no other changes needed)
4. It's not ERN's job to mandate/enforce a certain local Git setup
> Remove strict cauldron https check

- ern-container-gen-ios/src/IosGenerator.ts
Reorder a step of iOS container generation, just so that in case of an RN 61+ container, the plugin injection phase _(injecting native modules based on configuration defined in the manifest)_ is performed AFTER copying the composite `node_modules` _(containing the native module pods)_ to the container output directory and not BEFORE (as it is currently).
This is done because, in very specific cases, the native code and supporting pods of native modules could need to be altered or used in some ways during plugin injection, based on some plugin configuration directives, but can't currently happen because of the fact that this copy happens after the plugin configuration is evaluated.
> Reorder iOS container generator steps

- ern-composite-gen/src/createIndexJs.ts
- ern-composite-gen/src/generateComposite.ts
Looks like when we introduced faster composite generation back in 0.41.0, we forgot about JS API implementations ...
We are not using any JS API implementations internally, that's probably why this problem has not surfaced earlier and been only [recently reported](https://github.com/electrode-io/electrode-native/issues/1710).
The issue only impacts container/composite generation when using one or more JS API implementations and only local MiniApps _(i.e not git or registry urls for the MiniApps, only file based path)_. In that case the JS API implementations provided to the composite generator are just plain ignored _(not installed in the composite, nor imported in composite index.js. entry file)._
This PR fixes this, by properly handling JS API implementation(s) in this specific context …
> Fix JS API implementations injection in composite

- ern-orchestrator/src/start.ts
Fix an issue causing linked registry based miniapps _(miniapps linked using `ern link` and retrieved from a registry url instead of git)_ to be improperly imported in the composite index.
Fixes https://github.com/electrode-io/electrode-native/issues/1713
> Fix an issue with linked registry miniapps

- yarn.lock
Patch for Prototype Pollution in dot-prop [CVE-2020-8116](https://github.com/advisories/GHSA-ff7x-qrg7-qggm)
> Update dot-prop to 4.2.1

- ern-orchestrator/src/codepush.ts
Follow up to https://github.com/electrode-io/electrode-native/pull/1687
CodePush is not guaranteeing MiniApps import order based on Cauldron because of a [`unionBy`](https://lodash.com/docs/#unionBy) call that uses user provided MiniApps to CodePush as first parameter of the union call, and the complete list of MiniApps from Cauldron as the second parameter. Because lodash [`unionBy`](https://lodash.com/docs/#unionBy) order elements based on the first array, this causes the order guarantee based on Cauldron not to be honored.
The fix is just to switch the two parameters, so that ordering will match the order from Cauldron, as for all other commands generating a composite from Cauldron.
> Fix CodePush MiniApps import ordering

- ern-container-gen-ios/src/IosGenerator.ts
Add `verbose` flag to `pod install` command, to get more details, especially in the case of the command failing.
> Set verbose flag for pod install command

- ern-composite-gen/src/createIndexJs.ts
Improve `createIndexJs` function in composite generator to throw a custom error message in case a specific dependency is not found in the composite package.json _(currently, the following error is thrown: `Uncaught TypeError: Cannot read property '0' of undefined`)_
> Improve error reporting for composite createIndexJs failure

- ern-core/src/iosUtil.ts
Some users have reported the following obscure error when generating an iOS container 
`✖ An error occurred: TypeError: Cannot read property 'productReference' of null`
This error is coming from the library we use to parse iOS project files _(.pbxproj)_ and is usually caused by a plugin misconfiguration in manifest. Unfortunately this error is not very informative and does not clearly point to the cause of the problem.
This PR improves the error message in such a scenario, to throw this error instead _(sample)_
```
✖ An error occurred: Error when trying to inject react-native-reanimated in iOS container.
✖ This error is typically due to a plugin misconfiguration in manifest.
✖ Please make sure that the following static lib(s) reference(s) (name and target) in your configuration ...
✖ [
✖ …
```
> Improve an error message in iOS container generator

- ern-api-impl-gen/src/generators/ios/ApiImplIosGenerator.ts
- ern-container-gen-ios/src/IosGenerator.ts
- ern-core/src/iosUtil.ts
Follow up of https://github.com/electrode-io/electrode-native/pull/1737 which missed propagating the iOS deployment target for native api implementation project generation.
Moved `getDefaultIosDeploymentTarget` function to `iosUtil` part of this PR, as being a generic iOS utility function it belongs in this file, making it more accessible to other modules. Also make it return undefined instead of null, to comply with some expected types _(and in a sense it's more meaningful as the pod deployment target is not defined for versions of RN < 61 that are not using any Podfile)._
> Fix iOS deployment target for native api impls

- ern-container-gen-ios/src/IosGenerator.ts
Fix an issue with ios container deployment target caught by system tests.
In case no explicit extra ios configuration is supplied to the container generator, this LOC would throw an error.
To be merged prior to 0.45.0 release.
> Fix an issue with ios container deployment target

- docs/platform-parts/composite/index.md
- ern-composite-gen/src/generateComposite.ts
- ern-composite-gen/src/types/CompositeGeneratorConfig.ts
- ern-composite-gen/test/compositegen-test.ts
- ern-container-gen/src/bundleMiniApps.ts
- ern-local-cli/src/commands/bundlestore/upload.ts
- ern-local-cli/src/commands/create-composite.ts
This adds support for custom `extraNodeModules` entries in `metro.config.json` of the Composite project.
Docs have been updated and a test case was added. The diff is pretty short and straightforward, so I won't put any additional description here.
I'm not exactly sure if something identical can be done with the existing Babel support - If that's the case then we might not need this.
> Add custom Metro config extraNodeModules support

- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/composite.ts
- ern-orchestrator/src/generateContainerForRunner.ts
Two small commits related to passing custom metro config parameters to the composite generator. Best reviewed individually:
The first commit only aligns some minor inconsistencies in parameter naming and structure (no functional changes). The second commit is the one with the actual change: `create-container` now supports the optional `metroExtraNodeModules` in a Cauldron's `compositeGenerator` config added in #1743.
> Align composite gen config parameters

- ern-core/src/iosUtil.ts
Related to #1737 #1739 #1741, usage of `getDefaultIosDeploymentTarget` in projects with a version of React Native **lower than 0.61** leads to a bug which leaves the deployment target undefined. This causes the generated container to defaults to the latest in Xcode (e.g. 13.2), and fail the build.
With this small patch, the method now supports practically all versions of RN: Versions before 0.56.0 had a deployment target set to `8.0` (tested all the way down to 0.41). The change from 8.0 to 9.0 happened in RN 0.56 (not 0.61, which is what the method previously assumed).
Thanks @jw2175 for helping to investigate!
> Fix default iOS deployment target for RN<0.61

- ern-cauldron-api/src/getActiveCauldron.ts
- ern-cauldron-api/src/index.ts
- ern-local-cli/src/commands/cauldron/config/get.ts
- ern-local-cli/src/commands/cauldron/upgrade.ts
- ern-local-cli/src/commands/create-composite.ts
- ern-local-cli/src/commands/create-container.ts
- ern-local-cli/src/index.ts
- ern-orchestrator/src/start.ts
Fix a `create-container` command bug introduced in`0.45.2` through #1745
The issue is on [this line](https://github.com/electrode-io/electrode-native/pull/1745/files#diff-21660d33eebc3be34c32e7b9851feab3c24608a6e00935391811d967c2f95782R188) where `cauldron` instance can be `undefined` _(if not connected to a cauldron, which is allowed if miniapps are explicitly provided to the command)_, leading to the command failing with `Cannot read property 'getCompositeGeneratorConfig' of undefined` in this case.
The fix here is only to replace `cauldron.getCompositeGeneratorConfig` with `cauldron?.getCompositeGeneratorConfig`.
The additional code updates in this PR is just due diligence to enhance type safety to catch such errors on cauldron instances retrieved via `getActiveCauldron` way earlier. …
> Fix cauldron requirement for create-container command

- ern-orchestrator/src/generateContainerForRunner.ts
- ern-orchestrator/src/runMiniApp.ts
- ern-orchestrator/test/generateContainerForRunner-test.ts
- ern-orchestrator/test/runMiniApp-test.ts
With this change, `metroExtraNodeModules` are now also passed and taken into account for `ern run-android` and `ern run-ios`.
> Pass extraNodeModules to compositeGen in runner

- ern-core/package.json
- yarn.lock
Add missing `fs-extra` dependency that is used by `ern-core` module but not declared in its package.json, causing some errors when `ern-core` is used a dependency in a project.
> Add missing fs-extra dependency to ern-core

- docs/platform-parts/manifest/native-modules.md
- ern-core/src/Manifest.ts
- ern-core/src/iosUtil.ts
Introduce new `extraPodspecsSources` manifest directive for iOS plugins configurations.
It allows to inject extra [pod specs sources](https://guides.cocoapods.org/syntax/podfile.html#source) in the container Podfile, in case some pod spec dependencies of a native module needs to be retrieved from a specific pod spec repository _(common for non open sourced dependencies)_.
Associated master manifest PR : https://github.com/electrode-io/electrode-native-manifest/pull/204
> Add extraPodspecsSources manifest directive for iOS

- docs/cli/platform/config/del.md
- docs/cli/platform/config/get.md
- docs/cli/platform/config/set.md
- ern-container-gen-ios/src/IosGenerator.ts
- ern-orchestrator/src/constants.ts
CocoaPods support side-by-side installation of multiple versions of the `pod` executable.
If multiple versions are installed, it will by default pick the latest version (afaik).
It is possible to select a specific version of the executable for running pod commands, as indicated in [this SO post](https://stackoverflow.com/questions/20487849/how-to-downgrade-or-install-an-older-version-of-cocoapods).
When generating an iOS container, ern will run `pod install` as-is without specifying any version, so it will use the latest.
In some fringe cases, or for conducting some experimentation, it might be needed to use a specific version of the pod executable for running `pod install`.
This PR adds a new configuration property `podVersion` to ern global config, so that a specific pod executable …
> Add support for configurable pod binary version

- ern-cauldron-api/test/BaseGit-test.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-composite-gen/test/compositegen-test.ts
- ern-core/test/ErnBinaryStore-test.ts
- ern-core/test/FsCache-test.ts
- ern-core/test/ModuleFactory-test.ts
- ern-core/test/Utils-test.ts
- ern-orchestrator/test/Ensure-test.js
- ern-orchestrator/test/codepush-test.ts
- ern-orchestrator/test/launchOnDevice-test.ts
- ern-orchestrator/test/runMiniApp-test.ts
- ern-orchestrator/test/utils-test.js
- ern-util-dev/src/index.js
Remove the two custom methods `doesThrow` and `doesNotThrow` from `ern-util-dev`, and instead use the built-in `assert.rejects(...)` (and `expect(...).to.not.throw()` from chai):
https://nodejs.org/api/assert.html#assert_assert_rejects_asyncfn_error_message
```typescript
assert(
await doesThrow(
object.method,
object,
'test'.toAppDescriptor(),
),
);
```
```typescript
assert(rejects(object.method('test'.toAppDescriptor())));
```
This results in shorter test code that's easier to read&write, but aside from the cosmetics this also helped uncover several directly related code issues:
Since TypeScript can now properly detect and check parameter types, it turned out that some tests were calling the methods with wrong arguments (previously undetected), and checked for exceptions thrown. Removed …
> Replace doesThrow with rejects

- ern-container-gen-android/src/AndroidGenerator.ts
This fixes an issue with the Android container generator related to distinguishing regular from raw dependencies declared in the manifest plugin configs.
If the string _before_ the first `:` contains a `'`, '`(`', or a space, is should be considered a raw dependency, *not* a regular dependency. Raw dependencies are inserted 1:1 in the generated `build.gradle` file and are the preferred way to declare dependencies from ERN 0.46 going forward (see also #1765).
Examples for regular deps:
```
"dependencies": [
"com.google.firebase:firebase-crashlytics:17.1.0",
"com.google.firebase:firebase-crashlytics-ndk:17.1.0"
]
```
Examples for raw deps:
```
"dependencies": [
"implementation 'com.example:impl:1.0.0'",
"api 'com.example:api:1.0.0'",
"annotationProcessor …
```
> Fix logic for raw and regular deps in plugins cfg

- ern-core/src/AndroidPluginConfigGenerator.ts
- ern-core/test/AndroidPluginConfigGenerator-test.ts
- ern-core/test/fixtures/PluginConfigGenerator/android/dependencies/build.gradle
- ern-local-cli/src/commands/create-plugin-config.ts
**Update**:
This PR also increases `manifestBaseErnVersion` for `create-plugin-config` to `0.46.0`.
---
ERN started supporting "raw" dependency types in plugin configs with version 0.44 (see #1712). However, `ern create-plugin-config` did not include the dependency type in the generated file. With this small change, it will now correctly support and recognize additional types (e.g. `compileOnly`, `api`, ..) and not just add the dependency to a plain list (which would then _all_ be added using `implementation` to the container).
Example before:
```
{
"android": {
"root": "android",
"dependencies": [
"com.example:impl:1.0.0",
"com.example:api:1.0.0",
"com.example:annotation-processor:1.0.0",
"com.example.compile-only:1.0.0"
]
},
"ios": {}
}
```
Now:
```
{
"android": {
"root": "android", …
```
> Include dependency type in generated plugin config

- ern-container-gen-ios/src/IosGenerator.ts
Fix a bug in iOS container generator, that results in some native modules not being properly copied over to target node_modules directory of generated containers.
The bug was due to the RegEx being used to detect the node modules being required by the container pods project, which was missing some modules in some rare case. The only and first occurrence of this issue was noticed with AppCenter native module.
For example, in the usual case _(99% of native modules experienced so far)_ the path to a native module specified in the Pods project.pbxproj will look like this _(quoted)_ :
```
path = "../node_modules/foo/bar";
```
Whereas for the AppCenter native module the path is as follow _(unquoted)_
```
path = ../node_modules/appcenter/ios;
```
> Fix ios node modules copy

- ern-core/src/Manifest.ts
- ern-core/src/nativeDependenciesLookup.ts
Add support for injecting ObjectiveC APIs in the iOS container. 
**Please note that such APIs will not be auto generated as the iOS API generator only generates Swift APIs**
This can however be needed in case an ObjectiveC API is manually created _(which can be useful in some scenarios)_.
Indeed, while 99% of APIs use cases will be limited to using generated APIs, one handy thing about APIs is that their sources are injected into the container and exposed to the client application, which can be useful to inject arbitrary native custom code into the container that can be invoked from the client application _(without any JS<->Native cross communication as is the typical use case for APIs)_.
This PR also fixes the RegExp used to detect directories contain native code. 
The problem with this …
> Add support for ObjC APIs injection

- ern-api-impl-gen/src/generators/android/ApiImplAndroidGenerator.ts
- ern-composite-gen/src/Composite.ts
- ern-composite-gen/src/GeneratedComposite.ts
- ern-composite-gen/src/WorkspaceComposite.ts
- ern-composite-gen/src/createMetroConfig.ts
- ern-composite-gen/src/generateComposite.ts
- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-ios/src/IosGenerator.ts
- ern-core/src/MiniApp.ts
- ern-core/src/android.ts
- ern-core/src/getMetroBlacklistPath.ts
- ern-core/src/index.ts
- ern-core/src/iosUtil.ts
- ern-core/test/android-test.ts
- ern-orchestrator/src/start.ts
- ern-runner-gen-android/src/AndroidRunnerGenerator.ts
Add Android & iOS support for React Native 0.64.0.
React Native 0.64.0 AAR has already been published to [Maven Central](https://repo1.maven.org/maven2/com/walmartlabs/ern/react-native/0.64.0/). 
The changes to Electrode Native, part of this PR, accounts for the following changes in RN 0.64 :
- Minimum SDK level now set to 21
- Hermes engine package version bumped to ~0.0.7
- New requirement on react-native-codegen package to generate Turbo Modules from specs
- Updated module locations and new modules _(changes done through new plugin configuration in manifest : https://github.com/electrode-io/electrode-native-manifest/pull/214)_
- Metro blacklist source file renamed from `blacklist` to `exclusionList`
> Add support for React Native 0.64.0

- ern-orchestrator/src/start.ts
Improve `ern start` command by adding a check to ensure that all linked MiniApps _(either implictly for local miniapps or explicitly for remote miniapps)_ haven been properly installed _(i.e `yarn install` or `npm install` was run from these directories)_
It actually happened to me quite a few times _(and probably to some other users)_ to use `ern start` with some local MiniApps I forgot to install, leading to a confusing obscure red screen at runtime.
This PR catches this problem early on, before launching the packager, to avoid running into a runtime issue.
> Add linked miniapps installation check for ern start

- ern-orchestrator/src/start.ts
Improve `ern start` command logging to give better feedback on all linked MiniApps.
- Reintroduce logging of linked directories _(fixing regression done in [this commit](https://github.com/electrode-io/electrode-native/commit/e52951cf60a86b4a9d5f59cb73a2119afa6a9a20#diff-d74ec06d0d0c724b4a896c9322f1b2c20e815c9aa8f47a0545b4b8e0b9f30574L208-L213))_
- Add explicit logging indicating auto linking of local MiniApps, prior to generating the composite.
Sample output :
```
➜  ern start --miniapps /Users/foo/first-miniapp git+ssh://git@github.com:foo/second-miniapp.git
✔ Ensuring that metro server is not running 3s
✔ Auto linking local MiniApp from /Users/foo/first-miniapp 0s
✔ Generating MiniApps composite 44s
✔ Cleaning up existing composite directory 0s
✔ [1/1] Adding …
```
> Improve ern start command logging

- docs/SUMMARY.md
- docs/cli/run-container-pipeline.md
- ern-local-cli/src/commands/run-container-pipeline.ts
This PR introduces a new Electrode Native command, `run-container-pipeline`.
It allows to run a locally created container through a given Container pipeline.
A Container pipeline is a collection of Container `transformers` and/or `publishers` _(defined as `pipeline blocks`)_ that are run in sequence, one after the other, when using the `cauldron regen-container` command.
This is a convenient structure as it allows to define a chain of transformer and/or publishers to run, along with their configuration, in the form of JSON configuration files stored locally, or in a Cauldron. It ultimately simplifies the sequencing of transformers/publishers without having to chain multiple `transform-container`/`publish-container` commands manually, each having to be fed their own configuration.
One …
> Introduce new run-container-pipeline command

- ern-container-gen-ios/src/IosGenerator.ts
- ern-container-gen-ios/src/hull/ElectrodeContainer.xcodeproj/project.pbxproj
- ern-container-gen-ios/src/hull/ElectrodeContainer/MiniAppNavigationControllers/README.md
- ern-container-gen-ios/src/templates/MiniAppNavigationController.mustache
- ern-container-gen-ios/src/templates/licenseInfo.mustache
- system-tests/fixtures/ios-container/ElectrodeContainer/MiniAppNavigationControllers/MovieDetailsMiniAppNavigationController.swift
- system-tests/fixtures/ios-container/ElectrodeContainer/MiniAppNavigationControllers/MovieListMiniAppNavigationController.swift
- system-tests/fixtures/ios-container/ElectrodeContainer/MiniAppNavigationControllers/README.md
@belemaire goal is to generate subclasses of ENBaseNavigationController inside the container. I'm able to generate the files, following the example from https://github.com/electrode-io/electrode-native/blob/master/ern-container-gen-android/src/AndroidGenerator.ts
However, not sure how to include the references to the new files inside the pbxproj file of the container so that it will show up in the project navigator when using Xcode.
> Generate miniapp navigation controllers for iOS containers

- ern-container-gen-ios/package.json
Fix bug introduced in ERN 0.47.0 via https://github.com/electrode-io/electrode-native/pull/1790
Some mustache templates to generate iOS files in the container were introduced in this PR, but were not copied over to release package directory, leading to error when trying to generate an iOS container.
Will be released as hotfix in ERN 0.47.1
> Fix ios container mustache template copy

- ern-container-gen-ios/src/IosGenerator.ts
Pbxproj file paths should be relative instead of full
ex: 
path = "MiniAppNavigationControllers/AccountMiniAppNavigationController.swift"
instead of 
path = "/Users/jenkinspan/looper-workspace/workspace/.../ios/ElectrodeContainer/MiniAppNavigationControllers/AccountMiniAppNavigationController.swift"
> Fix paths for miniapp nav controllers to be relative

- ern-container-gen-ios/src/IosGenerator.ts
- ern-core/src/iosUtil.ts
Add new `excludedNativeModules` iOS container configuration property.
It can be used to selectively exclude one or more native modules pods so that they don't get injected inside the container.
It has the same effect as using `ignorePodSpec` directive in a manifest plugin configuration.
While the native module pod will be ignored, causing the native module native code to be completly ignored and not injected in the container, it won't impact the JavaScript side of the native module which will still be bundled in case the JS application code is importing and consuming the native module JS surface.
As any iOS container generator configuration, this property can either be set in cauldron configuration via `containerGenerator.iosConfig` or directly supplied to `create-container` or `run-ios` …
> Add excludedNativeModules to ios container config

- ern-container-gen/src/executeBundleHooks.ts
- ern-container-gen/src/generateContainer.ts
- ern-container-gen/src/types/ContainerGeneratorConfig.ts
- ern-container-gen/src/types/ContainerGeneratorHooks.ts
- ern-orchestrator/src/container.ts
sample commands 
- `ern run-android --extra '{"containerGenerator": {"hooks": {"preBundle": "/Users/k0s00ly/workspace/ern/picking-miniapp/script/pre-script.sh","postBundle": "/Users/k0s00ly/workspace/ern/picking-miniapp/script/post-script.sh"}}}'
`
- `ern run-android --extra cauldron://config/config.json
`
- `ern create-container --miniapps file:///Users/k0s00ly/workspace/ern/picking-miniapp --extra cauldron://config/config.json
`
****** OUTPUT ******
```
exec /var/folders/qw/0dxtwnhn2px_n55zdrtcx46w0000gp/T/tmp-36171kyCBi44Y8br5/pre-script.sh
{
cwd: '/private/var/folders/qw/0dxtwnhn2px_n55zdrtcx46w0000gp/T/tmp-36171HCvrf9IJcFIL'
}
Recognized Pre Script
```
```
exec /var/folders/qw/0dxtwnhn2px_n55zdrtcx46w0000gp/T/tmp-3617133qECZy0xWqR/post-script.sh 
{ cwd: …
```
> add support to execute pre/post scripts

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
Deprecating all prior overloaded methods.
Providing one method each for creating UIViewController and UIView with all parameters.
> [iOS] Refactor miniappview init

- ern-core/src/createTmpDir.ts
Fix bug introduced in ERN [v0.48.0](https://github.com/electrode-io/electrode-native/releases/tag/v0.48.0) through https://github.com/electrode-io/electrode-native/pull/1808
This bug is causing some ERN commands to fail with such an error, when and only when `tmp-dir` CLI option of ERN is used _(to override the system temporary directory location)_.
```
✖ An error occurred: dir option must be relative to "/var/folders/rt/wyyd9ym914z3cpjh00y6t5_x3blvsn/T", 
found "/Users/xxxx/ern-temp".
```
This bug is due to the bump of [tmp](https://github.com/raszi/node-tmp) dependency version _(0.0.33 -> 0.2.1)_ containing a breaking change. 
`dir` option of this module still exists but it does not have the same use anymore _(it now except a relative path, relative. to the system temporary directory)_ …
> Fix bug in createTmpDir function

- ern-orchestrator/src/codepush.ts
- ern-orchestrator/test/codepush-test.ts
Fix a regression of `code-push release` command, that got introduced in [v0.44.1](https://github.com/electrode-io/electrode-native/releases/tag/v0.44.1) release through https://github.com/electrode-io/electrode-native/pull/1720
The bug comes from the fact that `unionBy` keeps entries from the first array, causing the current MiniApps SHA _(or JS API impls)_, as set in Cauldron, to be picked, instead of the ones supplied to the command, leading to the CodePush release being a noop.
Instead of preserving the ordering by switching `unionBy` arrays _(causing this buggy side effect)_, revert the order of the arguments to the right one, and reorder MiniApps/JS API implementations via a post processing function.
> Fix bug in code-push release

- .github/workflows/release.yml
Add initial GitHub action workflow to take care of publishing new Electrode Native releases to npm.
With this PR, the release process is still partially manual. Full automation is not what's intended in this PR _(this might be tackled on later on if deemed necessary)_. 
This workflow only takes care of publishing new versions to npm, to avoid having to perform this step from a workstation, mainly to improve security _(mostly to avoid any compromised env or having to share publication password with all maintainers)._
It triggers whenever a tag is pushed to the repository _(we only use tags for versioning in this repository)_. 
The job will read the version to publish from the `lerna.json` file kept at the root of the repository, and run `lerna publish` to publish all packages with this …
> Add GitHub action workflow for ern release

- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- system-tests/fixtures/api-impl-js/ern-movie-api-impl/package.json
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/build.gradle
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/Podfile
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/package.json
A very minor update to `ElectrodeReactContainer.java` (to avoid an unnecessary change to the fixtures, as well as an unused import). Also the fixtures needed to be regenerated due to some recent changes in the code base (tests were failing).
> Update ElectrodeReactContainer.java and regen fixtures

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
This allows calling of start method from swift to be able to pass nil to electrode plugin config. Found after runner was moved to Swift.
> Make electrode plugin delegates nullable

- docs/platform-parts/composite/index.md
- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/generateContainerForRunner.ts
- ern-orchestrator/test/generateContainerForRunner-test.ts
`runLocalCompositeGen`, the function used to generate a composite without retrieving composite generator configuration from cauldron _(used indirectly by commands such as `run-android`/`run-ios`/`create-container` ..)_ is never invoked with the `resolutions` argument, meaning that it is not possible to leverage Yarn selective dependency resolutions support when using these commands.
This PR addresses this problem by making it now possible to supply `resolutions` to these commands via the `--extra` configuration object option _(in the `compositeGenerator` object)_
> Pass resolutions to runLocalCompositeGen

- ern-core/src/ReactNativeCli.ts
Under some rare circumstances _(watchman related)_ we have noticed metro bundler failing to generate the JS bundle but exiting its process with a non error status code.
In that case, Electrode Native will continue its container generation pipeline execution as if nothing happened and will ultimately fail later on when it tries to copy the bundle to the container. 
This is a problem for multiple reasons. First, the build will take a while more before failing _(it might take up to many more minutes before it reaches the point where it will fail)_. Second, because the error is thrown much later on in the process, it might cause confusion as to what exactly the problem is.
We should instead fail fast, at the site of the problem, in that case just after Metro bundler process exit. 
This PR …
> Throw in case metro fails to generate the bundle silently

- ern-container-gen-ios/src/IosGenerator.ts
- ern-container-gen-ios/src/templates/MiniAppNavigationController.mustache
- ern-container-gen-ios/src/templates/MiniAppsConfig.mustache
- ern-container-gen-ios/src/templates/generatedCode.mustache
- system-tests/fixtures/ios-container/ElectrodeContainer/MiniAppNavigationControllers/MiniAppsConfig.swift
- system-tests/fixtures/ios-container/ElectrodeContainer/MiniAppNavigationControllers/MovieDetailsMiniAppNavigationController.swift
This PR allows access to miniapp names for consuming native app.
> Add MiniAppsConfig file to iOS container gen

- ern-orchestrator/test/codepush-test.ts
Avoid word 'failing' to make it easier to search for failing tests.
> Update description of codepush tests

- .github/workflows/publish.yml
- .github/workflows/version.yml
This PR introduces a new workflow **version.yml**, which, together with **publish.yml**, fully automates new releases of Electrode Native.
After this is merged, the following is **no longer required**:
- Manual creation/synchronization of release branches
- Updates to `lerna.json`
- Locally committing and tagging
- Pushing of tags
Instead, we now have two separate workflows that work together as follows:
1. **Step 1: version.yml** (GitHub side, triggered **manually**)
Once the repo is in a state ready for a new release, the version workflow is triggered on the respective branch:
- The _default_ branch for a new _minor_ release
- An existing `v0.x` branch for a new patch release
The workflow will create the new release branch (if necessary), update versions, commit changes, create tags, …
> Automate publishing and versioning

- ern-core/src/AndroidPluginConfigGenerator.ts
This is to be reverted after a fixed version of gradle-to-js is available.
https://github.com/ninetwozero/gradle-to-js/issues/32
> Prevent plugin cfg gen crash caused by g2js bug

- ern-core/src/YarnCli.ts
When using ern regen-api in not published api folder, it throws an error saying "Received invalid response from npm.". This PR fixes this yarn info command issue and replaces generic message with 'Package not found'.
Closes #1764
> Fix yarn info generic message when package not exists

- ern-core/src/AndroidPluginConfigGenerator.ts
- ern-core/src/PluginConfigGenerator.ts
- ern-core/test/AndroidPluginConfigGenerator-test.ts
- ern-core/test/fixtures/PluginConfigGenerator/android/TestCustomCtorPackage.java
- ern-core/test/fixtures/PluginConfigGenerator/android/TestCustomCtorPackage.kt
- ern-core/test/fixtures/PluginConfigGenerator/android/TestNoArgCtorPackage.java
- ern-core/test/fixtures/PluginConfigGenerator/android/TestNoArgCtorPackage.kt
- ern-core/test/fixtures/PluginConfigGenerator/android/TestPackage.java
- ern-core/test/fixtures/PluginConfigGenerator/android/TestPackage.kt
- ern-core/test/fixtures/PluginConfigGenerator/android/TestPrimaryCtorPackage.kt
- ern-core/test/fixtures/PluginConfigGenerator/android/build.gradle
Several updates and improvements to `AndroidPluginConfigGenerator.ts`. Biggest user visible change is that it now includes basic support for detecting and processing Kotlin source files in plugins when running `ern create-plugin-config`. Added new test cases to verify new use cases.
Closes #1757
> Update plugin config gen with kotlin support

- ern-core/package.json
- ern-local-cli/package.json
- yarn.lock
Precaution to avoid unintended upgrades to a version containing malicious code:
https://gist.github.com/MidSpike/f7ae3457420af78a54b38a31cc0c809c
Closes #1858
> Lock node-ipc to 9.2.1

- ern-container-gen-ios/src/IosGenerator.ts
- ern-core/src/iosUtil.ts
iOS container builds for RN 0.64+ started failing on 2022-03-23 due to a change in the external dependency `react-native-codegen` (which the container generator added without specifying a version).
This aligns the version of react-native-codegen with the version of React Native during iOS container generation.
> Fix iOS container generation for RN 0.64+

- ern-core/src/android.ts
Android container gen and codepush ota updates were not using matching versions of Hermes and JSC for RN 0.65+ - This fixes it.
> Align Hermes/JSC versions for RN 0.65+

- ern-runner-gen-ios/src/hull/ErnRunner/Info.plist
- ern-runner-gen-ios/test/fixtures/simple-ios-runner/ErnRunner/Info.plist
Protected Resources in iOS apps needs UsageDescription keys/values to be added to the Info.plist (Information Property List).  The string values will be presented to the user the first time they access the resource.  Failure to set the appropriate UsageDescription in the Info.plist will result in the app crashing when running in iOS 10 or greater.
Here is the complete list of Protected Resources:
https://developer.apple.com/documentation/bundleresources/information_property_list/protected_resources
The ErRunner generated by Electrode Native is missing two UsageDescriptions from that list and available to iOS 10, the minimum target typically generated: 
https://developer.apple.com/documentation/bundleresources/information_property_list/nssiriusagedescription …
> New iOS plist UsageDescription keys

- system-tests/fixtures/api-impl-js/ern-movie-api-impl/package.json
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/build.gradle
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/package.json
Updated RN 0.66.5 in Manifest - https://github.com/electrode-io/electrode-native-manifest/pull/234
Fix all the test fixtures to use RN 0.66.5
> Update RN to 0.66.5 in system test fixtures

- ern-orchestrator/src/runMiniApp.ts
- Add support to query maven publisher version from manifest for backward compatibility.
- Needs to be merged with -> https://github.com/electrode-io/electrode-native-manifest/pull/237
> update mavenPublisher in miniappRunner to query version from manifest

- ern-api-gen/resources/android/libraries/ern/api.mustache
- ern-api-gen/resources/android/libraries/ern/apidatamodel.mustache
- ern-api-gen/resources/android/libraries/ern/apievents.mustache
- ern-api-gen/resources/android/libraries/ern/apirequests.mustache
- ern-api-gen/resources/android/libraries/ern/model.mustache
- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/gradle.properties
- ern-core/src/AndroidPluginConfigGenerator.ts
- ern-core/test/AndroidPluginConfigGenerator-test.ts
- ern-core/test/fixtures/PluginConfigGenerator/android/build.gradle
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/SystemTestEventApi.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/SystemTestEventEvents.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/SystemTestEventRequests.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/SystemTestsApi.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/SystemTestsRequests.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/TestEventObjectParamApi.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/TestEventObjectParamData.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/TestEventObjectParamEvents.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/TestEventObjectParamRequests.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/api/TestMultiArgsData.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/model/ErnObject.java
- system-tests/fixtures/api/complex-api/android/lib/src/main/java/com/complex/ern/model/NavBarButton.java
- system-tests/fixtures/api/test-api/android/lib/src/main/java/com/test/ern/api/WalmartItemApi.java
- system-tests/fixtures/api/test-api/android/lib/src/main/java/com/test/ern/api/WalmartItemEvents.java
- system-tests/fixtures/api/test-api/android/lib/src/main/java/com/test/ern/api/WalmartItemRequests.java
- system-tests/fixtures/api/test-api/android/lib/src/main/java/com/test/ern/model/Item.java
Update erncontainer-gen and ern-api-gen to use androidx packages
Migration to Androidx - https://developer.android.com/jetpack/androidx/migrate
> Migrate to androidx package

- ern-composite-gen/src/generateComposite.ts
Use versions restricted to semver major component for additional packages added to the composite to avoid breaking compatibility.
> Ensure composite dependencies are version limited

- system-tests/fixtures/api-impl-js/ern-movie-api-impl/package.json
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/build.gradle
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/package.json
Fixtures needed updates after https://github.com/electrode-io/electrode-native-manifest/pull/236 was merged.
> Regen fixtures

- package.json
- yarn.lock
This updates the `typescript` dependency to `4.9.4`.
It also includes one preliminary commit to update and align `@types/inquirer` (previously, it was not aligned with the current version of inquirer used, and would cause errors with the new TypeScript version).
> Update typescript to 4.9.4

- ern-api-gen/src/generateProject.ts
- ern-api-gen/test/generateProject-test.js
- system-tests/fixtures/api/complex-api/package.json
- system-tests/fixtures/api/test-api/package.json
Instead of `{major}.{minor}.x`, use standard `^{major}.{minor}.{patch}` for `react-native-electrode-bridge` in generated api projects.
Note: `{major}.{minor}.x` is effectively `~{major}.{minor}.{patch}` - There is no reason to limit only patch updates (if semver is followed correctly).
> Use standard semver version for api gen bridge

- ern-core/src/Manifest.ts
Support both old 'IOS' and new 'ios' paths in the default api plugin config.
This is a follow-up to (and should have been part of) #1871
Also improve some of the related plugin config logging output in the same file.
> Fix api default config for case sensitive systems

- .github/workflows/ci.yml
Node.js 12 is end-of-life (and also deprecated on GitHub Actions). Remove it from CI matrix build, and add Node.js 18 instead.
~This also removes the engines restriction from package.json.~ (will be done in separate PR).
> CI: Remove Node.js 12, add Node.js 18

- docs/platform-parts/container/container-publication.md
- docs/platform-parts/container/container-transformation.md
- ern-local-cli/src/commands/publish-container.ts
- ern-local-cli/src/commands/transform-container.ts
Updated prefix rule. 
Because we must use scope company prefix. Like this `@company/ern-container-transformer-zfr`
> Update rule of create custom publisher/transformer

- ern-api-impl-gen/resources/android/RequestHandlerProvider.java.mustache
- ern-api-impl-gen/resources/android/apiController.mustache
- ern-api-impl-gen/resources/android/requestHandlerProvider.mustache
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/ern/api/impl/MoviesApiController.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/ern/api/impl/MoviesApiRequestHandlerProvider.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/ern/api/impl/RequestHandlerProvider.java
- system-tests/fixtures/api/complex-api/package.json
- system-tests/fixtures/api/test-api/package.json
Reverts electrode-io/electrode-native#1885
On closer inspection, it turns out there is quite a bit more support library leftover in ern-api-impl-gen which is currently causing some issues.
For the next release it is probably safer to revert this change - I'll follow up with a more thorough PR at a later date.
> Revert "Use androidx imports in api-impl-gen"

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/test/convertToAndroidX-test.ts
- ern-container-gen-android/test/fixtures/RNHttpapiPackagePlugin.java
- ern-container-gen-android/test/fixtures/WMBarcodePackagePlugin.java
When targeting React Native 0.60.0 or later (which uses AndroidX), attempt to automatically convert legacy plugin sources from android.support to androidx.
> Update and fix plugin conversion to support Androidx

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/test/convertToAndroidX-test.ts
- ern-container-gen-android/test/fixtures/RNHttpapiPackagePlugin.java
- ern-container-gen-android/test/fixtures/WMBarcodePackagePlugin.java
When targeting React Native 0.60.0 or later (which uses AndroidX), attempt to automatically convert legacy plugin sources from android.support to androidx.
> Update and fix plugin conversion to Androidx

- azure-pipelines.yml
MacOS 10.15 is not available in azure pipelines. Update to BigSur https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
> Update azure macOS image to 11

- docs/platform-parts/container/container-integration.md
- ern-container-gen-ios/src/IosGenerator.ts
Add optional podRepoUpdate flag in iosConfig
- Can be used to update the pod specs when running pod install in container generation. Flag is by default disabled and can be enabled in cauldron below.
This flag was made to use in regen-container command - it generates the container with updating the pod specs during pod install and updates the cauldron with new version and yarnlocks.
```
{
"containerGenerator": {
"iosConfig": {
"podRepoUpdate": true
}
}
}
```
or can be using in extra argument in create-container command 
--extra '{"iosConfig": {"deploymentTarget": "11.0", "podRepoUpdate": true}}'
> Add optional podRepoUpdate flag in iosConfig

- .github/workflows/version.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- azure-pipelines.yml
Update Azure pipelines config to use `macOS-latest` instead of `macOS-11`.
[According to the docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml), macOS-latest is currently pointing to macOS-12, while macOS-11 is marked as deprecated.
Hopefully, this will fix a strange macOS related CI failure. See https://github.com/electrode-io/electrode-native/runs/26834219060 and #1903 for example
> Use macOS-latest for Azure CI

- ern-core/package.json
- ern-core/src/gitCli.ts
- tsconfig.release.json
- yarn.lock
- Electrode Native Platform uses simple-git for git cli operations.
- Right now ERN only has SSH to authenticate in CI.  Updated simple-git to latest and add ability to support github_token to authenticate the cli commands. 
- Updated simple-git/promise since its going to be deprecated soon.
- ern-core -> yarn build since typescript lib doesn't support DOM. Simple-git uses DOM object AbortSignal.
> Update simple-git and add support for GIT_TOKEN

- ern-composite-gen/src/createMetroConfig.ts
Resolve issue - https://github.com/expo/expo/issues/23180
Support mjs extension in metro config.
> Add mjs extension to metroConfig

- ern-container-gen-ios/src/IosGenerator.ts
For iOS
**yargs** has published a new version 18.0.0 which has introduced a breaking change for electrode-native
https://github.com/yargs/yargs/releases/tag/v18.0.0
Currently IosGenerator.ts is configured to always pull the latest version of **yargs** which causes build issues during container regeneration.
Fix is to stop pulling latest version of yargs and instead use the last latest stable version of **yargs** which is **17.7.2**
> Update yargs to use last latest stable version

- ern-container-gen-android/src/hull/lib/build.gradle
Starting with AGP 8.0:
Automatic component creation is disabled by default.
To publish, you need to manually configure component creation using the publishing DSL.
When configuring multiple variants for publishing, the component name is set to "default" by default, unless we specify a different name in the multipleVariants function call.
Therefore, if we were previously publishing the "release" variant using components.release, we would now refer to the component as components.default when using the multiple variants publishing approach with the default component name.
The change from components.release to components.default is a consequence of AGP 8.0 disabling automatic component creation and adopting a different naming convention for the default component created when publishing …
> Declare variants for publishing for AGP 8
