electrode-io/electrode-native

- .travis.yml
- ern-api-gen/src/index.js
- ern-api-gen/yarn.lock
- ern-api-impl-gen/yarn.lock
- ern-cauldron-api/yarn.lock
- ern-container-gen/yarn.lock
- ern-core/src/MiniApp.js
- ern-core/src/compatibility.js
- ern-core/src/index.js
- ern-core/yarn.lock
- ern-local-cli/yarn.lock
- ern-runner-gen/yarn.lock
- ern-util-dev/yarn.lock
- ern-util/src/index.js
- ern-util/yarn.lock
- yarn.lock
- Add `.travis.yml` file
- Update all yarn locks to make sure they don't link to walmart npm for some packages
- Fix some bad imports (case sensitiveness)
> Setup Travis CI

- docs/getting-started/getting-started.md
Update the `Getting Started` documentation page to reflect recent improvement of `ern create-miniapp` command.
> Update Getting Started documentation

- ern-runner-gen/runner-hull/android/app/src/main/res/layout/activity_main.xml
- ern-runner-gen/runner-hull/android/app/src/main/res/values/dimens.xml
- ern-runner-gen/runner-hull/android/app/src/main/res/values/strings.xml
Update the Welcome message on Android Activity
Provide suggestion `Force close to reload ern mini-app bundle`
> Modify the mini-app with relevant message

- docs/overview/contributing.md
updated the contributing.md file
> committing changes to contributing.md file

- ern-local-cli/src/lib/utils.js
Sample Before :
```
More info about this command @ https://gecgithub01.walmart.com/Electrode-Mobile-Platform/ern-platform/blob/master/docs/cli/add.md
```
Sample After :
```
More info about this command @ https://electrode.gitbooks.io/electrode-native/content/cli/add.html
```
> Update ern-local-cli epilog url to point to GitBook

- docs/getting-started/getting-started.md
Make minor updates on the getting started initial documentation
> Make minor updates on the getting started initial documentation

- docs/overview/requirements.md
- docs/platform-parts/cauldron.md
- docs/platform-parts/container.md
- docs/platform-parts/manifest.md
* **Problem:** doc's code examples formatting is off in a few spots
* **Solution:** Fix 'em! (see commits for play-by-play)
* **Testing:** ?
> Fix minor doc code problems

- docs/getting-started/getting-started.md
Fix getting-started to move up a section to fix an issue
> move modification of ViewController.h above

- docs/getting-started/getting-started.md
- Modify Nav Bar names for both miniapp
- set nav bar translucent to NO
> fix minor places in getting started

- docs/getting-started/getting-started.md
Amended section of the documentation.
> Fix Typos in getting started and remove text

- docs/getting-started/getting-started.md
add command+s reminder after js file change; add the command to go to miniapp root dir before last command
> Getting started fixes

- docs/getting-started/getting-started.md
Re introducing the text to exit from the ErnRunner app and relaunching for the first time users.
> Add text to relaunch the starter app

- docs/cli/cauldron/add/dependencies.md
- docs/cli/cauldron/add/miniapps.md
- docs/cli/cauldron/add/nativeapp.md
- docs/cli/cauldron/batch.md
- docs/cli/cauldron/del/miniapps.md
- docs/cli/cauldron/update/dependencies.md
- docs/cli/cauldron/update/miniapps.md
- docs/cli/cauldron/update/nativeapp.md
- docs/cli/code-push.md
- docs/cli/create-api-impl.md
- docs/cli/create-api.md
- docs/cli/create-container.md
- docs/cli/link.md
- docs/cli/platform/current.md
- docs/cli/platform/install.md
- docs/cli/platform/uninstall.md
- docs/cli/platform/use.md
- docs/cli/start.md
- docs/cli/unlink.md
Add links to the Related commands section of cli
> Add links to the Related commands section of cli

- docs/getting-started/getting-started.md
`ListView` is deprecated, replace with `FlatList` as suggested by @swashcap 
Tested on both iOS and Android by following all updated steps.
Closes https://github.com/electrode-io/electrode-native/issues/106
> Update getting started to use FlatList instead of ListView

- README.md
> Article tc

- ern-local-cli/src/lib/start.js
Closes https://github.com/electrode-io/electrode-native/issues/100
> Fix ern start command

- .gitignore
Add exclusion of a directory that gets generated when serving GitBook locally through [gitbook-cli](https://github.com/GitbookIO/gitbook-cli)
> Update .gitignore for GitBook

- docs/cli/code-push.md
- ern-local-cli/src/commands/code-push.js
- ern-local-cli/src/lib/publication.js
Closes https://github.com/electrode-io/electrode-native/issues/114
> Add skipConfirmation option to code-push command

- ern-util/src/CodePushCli.js
- ern-util/src/ReactNativeCli.js
- ern-util/src/YarnCli.js
Add more debug logging to log every third party CLI command command line before run (CodePush, react-native, yarn).
> Add more debug logging

- ern-api-impl-gen/src/generators/android/ApiImplMavenGenerator.js
- ern-api-impl-gen/src/generators/ios/ApiImplGithubGenerator.js
This PR fixes issues with `ern create-api-impl` command while generating the project for iOS.!
> Fix ern create-api-impl command

- docs/platform-parts/cauldron.md
Add native-app-descriptior example for Cauldron doc
> Add cauldron native-app-descriptior example

- ern-util/scripts/launchPackager.command
> update packager script to support directory names with spaces.

- docs/getting-started/getting-started.md
Note: This Pull Request is targeting `v0.7` branch, not `master`
> :book: Update Getting Started 0.7 documentation to use fixed package versions

- ern-api-gen/resources/android/libraries/ern/api.mustache
Fixes Issue : https://github.com/electrode-io/electrode-native/issues/158
> Update the  api-regen event interface (android)

- docs/getting-started/getting-started.md
- update navigation api implementation instructions to make it more clear.
- add '@' symbol to ern run-ios for moviedetailsminiapp.
> update getting started instructions

- ern-util/src/config.js
Closes issue https://github.com/electrode-io/electrode-native/issues/147
> .ernrc formatting/indentation

- docs/GLOSSARY.md
- docs/SUMMARY.md
- docs/cli/cauldron/add/nativeapp.md
- docs/cli/cauldron/get/config.md
- docs/cli/cauldron/get/nativeapp.md
- docs/platform-parts/cauldron.md
Add Glossary, Define complete and partial native app selector
> Add Glossary, Define complete and partial native app selector

- ern-local-cli/src/commands/create-api-impl.js
- ern-local-cli/src/commands/create-api.js
- ern-local-cli/src/commands/create-miniapp.js
- ern-local-cli/src/lib/utils.js
Fixes https://github.com/electrode-io/electrode-native/issues/148
> Check if package name is not published on NPM

- ern-local-cli/src/commands/create-api-impl.js
- ern-local-cli/src/commands/create-api.js
- ern-local-cli/src/commands/create-miniapp.js
- ern-local-cli/src/lib/utils.js
Fixes https://github.com/electrode-io/electrode-native/issues/179
> Relax the create-api, create-api-impl, create-miniapp commands

- docs/overview/what-is-a-miniapp.md
Fix: corrected a couple of typos.
> Updated what-is-a-miniapp.md - corrected typos

- ern-util-dev/babelhook.js
- Cleanup `babelhook.js` source file by removing some unnecessary comments, removing some dead code, unnecessary code, quick renaming and fixing some indentations
- Make `babelhook.js` truly cross-platform by using `path.sep` / `path.join` where needed instead of constructing pathes manually or using hard coded path separators.
Tested on Mac and Windows, `babelhook` is doing its job properly on both platforms.
> Cleanup babelhook.js and make it cross-platform

- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-runner-gen/src/index.js
- ern-util/src/findNativeDependencies.js
Fix some bugs for Runner / Container Generator, that were introduced in recent commits (my bad).
> Fix runner and container generator

- ern-local-cli/src/commands/run-android.js
- ern-local-cli/src/commands/run-ios.js
- ern-util/src/android.js
- ern-util/src/ios.js
Fixes https://github.com/electrode-io/electrode-native/issues/103
> Allow device configuration

- ern-api-gen/src/apigen.js
- ern-local-cli/src/commands/cauldron/add/nativeapp.js
- ern-local-cli/src/commands/create-api-impl.js
- ern-local-cli/src/commands/create-miniapp.js
- ern-local-cli/src/lib/publication.js
- ern-local-cli/src/lib/utils.js
add flow type to the methods returning promise
> add flow type to method returning promise

- ern-api-gen/src/ApiGenUtils.js
- ern-api-gen/src/index.js
- ern-api-impl-gen/package.json
- ern-api-impl-gen/resources/android/RequestHandlerConfig.java
- ern-api-impl-gen/resources/android/RequestHandlerProvider.java
- ern-api-impl-gen/resources/android/apiController.mustache
- ern-api-impl-gen/resources/android/requestHandlerProvider.mustache
- ern-api-impl-gen/resources/android/requestHandlers.mustache
- ern-api-impl-gen/src/ApiImplGeneratable.js
- ern-api-impl-gen/src/generators/ApiImplGen.js
- ern-api-impl-gen/src/generators/android/ApiImplMavenGenerator.js
- ern-api-impl-gen/src/generators/ios/ApiImplGithubGenerator.js
- ern-api-impl-gen/src/index.js
- ern-local-cli/src/commands/create-api-impl.js
This PR adds support for generating API implementation code for Android.!
> Api Implemenation code generation

- ern-core/src/GitManifest.js
- ern-util/src/findNativeDependencies.js
More fixes around paths for Windows. 
Now able to generate a container that includes native plugins.
> Windows fixes

- ern-local-cli/src/lib/utils.js
- ern-runner-gen/src/index.js
Refactor `runMiniApp` function to make it lighter and avoid platform conditional switches in it.
> Light refactoring of runner

- ern-api-gen/resources/android/libraries/ern/apidatamodel.mustache
- ern-api-gen/resources/android/libraries/ern/model.mustache
- ern-api-impl-gen/hull/android/.gitignore
- ern-api-impl-gen/src/ApiImplGeneratable.js
- ern-api-impl-gen/src/generators/ApiImplGen.js
- ern-api-impl-gen/src/generators/android/ApiImplMavenGenerator.js
- ern-api-impl-gen/src/generators/ios/ApiImplGithubGenerator.js
- ern-api-impl-gen/src/index.js
- ern-container-gen/hull/android/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-core/src/MiniApp.js
- ern-core/src/utils.js
This PR adds support for generating api-impl initialization code inside a container.
> Container gen for api-impl

- docs/cli/code-push.md
> Fix `code-push` note formatting

- ern-local-cli/src/commands/code-push.js
Sorry noticed while tracing specific flow with `code-push` command
> fix typos with code-push options

- ern-api-gen/src/apigen.js
Fixes https://github.com/electrode-io/electrode-native/issues/149
> ern regen-api must clear the existing files

- ern-api-impl-gen/src/ApiImpl.js
- ern-api-impl-gen/src/generators/android/ApiImplMavenGenerator.js
- ern-core/src/utils.js
- ern-local-cli/src/commands/regen-api-impl.js
- ern-util/src/fileUtil.js
1. Make copied library files read-only
2. Perform version check and display proper messages.
3. Minor cleanups.
> Api implementation enhancements

- docs/cli/cauldron/add/nativeapp.md
- docs/cli/platform/config.md
- ern-local-cli/src/commands/cauldron/add/nativeapp.js
- ern-local-cli/src/commands/create-api-impl.js
- ern-local-cli/src/commands/platform/config.js
Remove the options if specified as command arguments
> Remove the options if specified as command arguments

- ern-local-cli/package.json
- ern-local-cli/src/lib/Ensure.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/Esnure-test.js
- ern-local-cli/test/fixtures/common.js
- ern-local-cli/test/utils-test.js
- ern-local-cli/yarn.lock
- Add new check function `isValidNpmPackageName` to `Ensure` class and `logErrorAndExitIfNotSatisfied` function.
- Add tests
Will accordingly update CLI commands that can make use of this check in a subsequent PR.
> Add new validity check isValidNpmPackageName

- ern-local-cli/src/commands/create-api-impl.js
Fixes https://github.com/electrode-io/electrode-native/issues/265
> check if api exisits before proceeding with create-impl

- ern-local-cli/src/lib/utils.js
- system-tests.js
Fixes https://github.com/electrode-io/electrode-native/issues/268
> fix create-api command to work without --skipNpmCheck flag

- ern-local-cli/src/lib/utils.js
- ern-util/src/ios.js
Add support for ern run-ios when real devices are connected and when signing and bundle id are set in ErnRunner.xcodeproj in xcode
> Add support for ern run-ios on real device

- ern-api-impl-gen/package.json
- ern-api-impl-gen/yarn.lock
- ern-core/package.json
- ern-core/yarn.lock
- ern-local-cli/package.json
- ern-local-cli/yarn.lock
- ern-util/package.json
- ern-util/yarn.lock
- global-cli/package.json
- package.json
- yarn.lock
Upgrade to [chalk 2](https://github.com/chalk/chalk/releases/tag/v2.0.0)
> Upgrade chalk version

- ern-api-gen/src/apigen.js
- ern-core/src/Manifest.js
- ern-core/src/utils.js
- ern-local-cli/src/commands/regen-api-impl.js
Check the module type using the `ern` object in `package.json`
Did not change the original regex check
> look up package name using moduleType

- system-tests.js
Fixes https://github.com/electrode-io/electrode-native/issues/292
> Daily system test build failure

- ern-core/src/MiniApp.js
PR is tested for `create-miniapp` followed by `run-android`
node system-tests are passing
> add moduleName in ern object written in package json

- ern-api-gen/src/Constants.js
- ern-api-gen/src/normalizeConfig.js
Remove unused configFilePath from normalizeConfig
> Remove unused configFilePath from normalizeConfig

- docs/cli/regen-api.md
add options to the regen-api command documentation
> add options to the regen-api command documentation

- ern-local-cli/src/commands/binarystore/add.js
- ern-local-cli/src/commands/binarystore/get.js
- ern-local-cli/src/commands/binarystore/remove.js
- ern-local-cli/src/lib/utils.js
- ern-util/src/utils.js
> Fix error log misspelling

- ern-core/src/utils.js
- ern-local-cli/src/lib/utils.js
> Avoid duplicating suffix for module names

- ern-util/src/android.js
- ern-util/test/android-test.js
- ern-util/test/fixtures/adb_devices
- ern-util/test/fixtures/adb_with_no_devices
- ern-util/test/fixtures/adb_with_one_device
- ern-util/test/fixtures/common.js
- ern-util/test/fixtures/emulator_list_avds
- ern-util/test/fixtures/emulator_one_avd
- ern-util/test/ios-test.js
> unit test android ern-util

- ern-util/test/Utils-test.js
- ern-util/test/android-test.js
- ern-util/test/fixtures/adb_devices
- ern-util/test/fixtures/adb_with_no_devices
- ern-util/test/fixtures/adb_with_one_device
- ern-util/test/fixtures/common.js
add test for logErrorAndExitProcess
>  add test for logErrorAndExitProcess

- ern-core/src/GitManifest.js
Bug similar to a previously identified one.
Do not use string comparisons to compare versions but rather rely on `semver` lib.
This bug had no impact yet based on current manifest but might have bite us later down the road.
> Fix a bug in GitManifest versions comparisons logic

- ern-core/src/cauldron.js
- ern-local-cli/src/lib/publication.js
- Fixes https://github.com/electrode-io/electrode-native/issues/299
> Improve code-push command

- docs/cli/platform/config.md
- ern-local-cli/src/commands/platform/config.js
- ern-local-cli/src/index.js
- system-tests.js
Closes https://github.com/electrode-io/electrode-native/issues/329
> Refactor logLevel and showBanner ern command options

- ern-local-cli/src/lib/publication.js
- ern-util/src/ios.js
- ern-util/test/android-test.js
- ern-util/test/fixtures/common.js
- ern-util/test/fixtures/ios_iphone_simulators.json
- ern-util/test/fixtures/ios_no_iphone_simulators.json
- ern-util/test/ios-test.js
- ern-util/test/required-test.js
* add unit test for `require.js`
* add unit test for `ios.js`
* add unit test for `android.js`
* modify the spin message for code-push
> test coverage util package

- system-tests.js
Closes https://github.com/electrode-io/electrode-native/issues/309
> Perform system-tests cleanup if interupted by SIGINT

- ern-util/src/android.js
- ern-util/test/android-test.js
- ern-util/test/ios-test.js
add unit test for execp references
> add unit test for execp references

- ern-core/src/utils.js
- ern-core/test/coreutils-test.js
> unit test the plugin path

- ern-api-gen/src/apigen.js
- ern-api-gen/src/languages/ErnAndroidApiCodegen.js
* remove the mysterious log.error 
* unused imports
> remove the mysterious log.error

- docs/cli/run-android.md
- docs/cli/run-ios.md
- ern-container-gen/src/utils.js
- ern-local-cli/src/commands/run-android.js
- ern-local-cli/src/commands/run-ios.js
- ern-util/src/android.js
- ern-util/src/deviceConfig.js
- ern-util/src/index.js
- ern-util/src/ios.js
- ern-util/test/android-test.js
- ern-util/test/ios-test.js
> Device config

- ern-local-cli/src/lib/Ensure.js
- ern-local-cli/src/lib/utils.js
- ern-local-cli/test/Esnure-test.js
- ern-local-cli/test/fixtures/common.js
- ern-local-cli/test/utils-test.js
Needed for an upcoming in dev feature.
> Add noFileSystemPath guard check

- ern-cauldron-api/src/api.js
> look for exact name match while looking up native dependencies.

- system-tests.js
Fixes [system-test-failure](https://travis-ci.org/electrode-io/electrode-native/builds/306609930?utm_source=email&utm_medium=notification)
> fix system test : api-impl naming convention issue

- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-core/src/Manifest.js
- ern-core/src/MiniApp.js
- ern-util/src/YarnCli.js
These fixes were shipped in Electrode Native [v0.10.2](https://github.com/electrode-io/electrode-native/releases/tag/v0.10.2) patch release
> :bug: Fix some bugs affecting scoped npm plugins

- ern-cauldron-api/src/util.js
- ern-cauldron-api/test/util-test.js
> Add tests for CauldronApi utils

- docs/cli/cauldron/get/nativeapp.md
- ern-local-cli/src/commands/cauldron/get/nativeapp.js
- system-tests.js
Closes https://github.com/electrode-io/electrode-native/issues/398
> Improve cauldron get nativeapp command

- ern-container-gen/hull/android/lib/src/debug/AndroidManifest.xml
- ern-container-gen/hull/android/lib/src/main/AndroidManifest.xml
- ern-runner-gen/runner-hull/android/app/src/main/AndroidManifest.xml
fix android crash if Dev Settings is clicked on  Dev menu
> fix android crash if Dev Settings is clicked on  Dev menu

- ern-container-gen/src/generators/ios/IosGenerator.js
change plugin.name to plugin.scopedName
> change plugin.name to plugin.scopedName

- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-runner-gen/src/index.js
close https://github.com/electrode-io/electrode-native/issues/433
> ios: only render mustache for runner gen for files that has templates

- ern-core/src/utils.js
Fixes https://github.com/electrode-io/electrode-native/issues/427
> handle errors while checking isDependencyApiOrApiImpl

- ern-local-cli/src/commands/cauldron/add/dependencies.js
- ern-local-cli/src/commands/cauldron/add/miniapps.js
- ern-local-cli/src/commands/cauldron/batch.js
- ern-local-cli/src/commands/cauldron/del/dependencies.js
- ern-local-cli/src/commands/cauldron/del/miniapps.js
- ern-local-cli/src/commands/cauldron/regen-container.js
- ern-local-cli/src/commands/cauldron/update/dependencies.js
- ern-local-cli/src/commands/cauldron/update/miniapps.js
- ern-local-cli/src/commands/code-push/patch.js
- ern-local-cli/src/lib/utils.js
throw error for no qualifying nap descriptors
Fixes # https://github.com/electrode-io/electrode-native/issues/419
> throw error for no qualifying nap descriptors

- docs/cli/list/dependencies.md
- ern-local-cli/src/commands/list.js
- ern-local-cli/src/commands/list/dependencies.js
- system-tests.js
Depends on https://github.com/electrode-io/electrode-native/pull/439
Please merge https://github.com/electrode-io/electrode-native/pull/439 before merging this one
> Add list dependencies command

- ern-container-gen/hull/android/.gitignore
- ern-container-gen/hull/ios/README.md
> General bug fixes

- ern-cauldron-api/src/CauldronApi.js
> Look for config entry existence before adding containerVersion entry.

- ern-api-gen/package.json
- ern-api-impl-gen/package.json
- ern-cauldron-api/package.json
- ern-container-gen/package.json
- ern-core/package.json
- ern-local-cli/package.json
- ern-local-cli/scripts/postinstall.js
- ern-runner-gen/package.json
- ern-util-dev/package.json
- ern-util/package.json
- lerna.json
- system-tests.js
Version of modules on master branch (dev version) should always remain on v1000.0.0.
> Set modules versions to 1000.0.0 on master

- ern-local-cli/src/lib/start.js
Closes https://github.com/electrode-io/electrode-native/issues/438
If no `miniapps` nor a `descriptor` are specified on the command line, then display a list of all descriptors to choose from (from Cauldron) instead of failing the command.
> start command lists descriptors from Cauldron

- ern-container-gen/src/ContainerGeneratorConfig.js
- ern-container-gen/src/FlowTypes.js
- ern-container-gen/src/generateContainer.js
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/android/hull/lib/src/main/AndroidManifest.xml
- ern-container-gen/src/generators/android/hull/lib/src/main/java/com/walmartlabs/ern/container/miniapps/MiniAppsConfig.java
- ern-container-gen/src/generators/android/templates/MiniAppActivity.mustache
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/index.js
- ern-container-gen/src/publishers/GithubPublisher.js
- ern-container-gen/src/publishers/MavenPublisher.js
- ern-container-gen/src/publishers/Publisher.js
- ern-container-gen/src/publishers/UnKnownPublisher.js
- ern-container-gen/src/utils.js
- ern-core/src/Manifest.js
- ern-core/src/MiniApp.js
- ern-runner-gen/src/index.js
Various refactorings around container generator.
Android and iOS containers have been generated and compared before and after these changes to ensure no breaking changes were introduced in this PR.
> Refactoring around container gen

- docs/cli/code-push.md
- ern-local-cli/src/commands/platform/config.js
Ref: https://github.com/Microsoft/appcenter-cli/issues/315
> Add more logs for platform config command.

- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/utils.js
- ern-core/src/Manifest.js
Light refactoring to simplify things towards further refactorings
> Refactor container generator plugin hooks

- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/utils.js
Remove rnpm assets handling code duplication.
> Move duplicated Container generator code to dedicated util functions

- ern-core/src/YarnCli.js
Close https://github.com/electrode-io/electrode-native/issues/412
> Use non interactive mode of yarn add

- docs/overview/what-is-a-miniapp.md
> grammar & punctuation

- docs/cli/start.md
- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/utils.js
* update start command documentation
* removing back ticks for non template strings
> update start command documentation

- ern-api-gen/resources/es6/libraries/ern/api.mustache
Fixes https://github.com/electrode-io/electrode-native/issues/479
> for event only api's , mustache is missing export

- ern-container-gen/src/generators/android/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
- ern-container-gen/src/generators/android/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
This commit was missed in the previous PR.
> add missing hasIntance() method to container.

- ern-local-cli/src/lib/utils.js
- Fixes https://github.com/electrode-io/electrode-native/issues/384
> Display container version

- ern-core/src/utils.js
> Update logErrorAndExitProcess to log exception stack

- ern-api-gen/src/generateProject.js
- ern-api-gen/src/normalizeConfig.js
- ern-api-gen/test/generateProject-test.js
remove shouldGenerateBlankApi config parameter from normalize config option
> remove shouldGenerateBlankApi config parameter from normalize config option

- ern-core/src/ReactNativeCli.js
Tested on Ubuntu 16.04.3
Close https://github.com/electrode-io/electrode-native/issues/391
> Linux support of run-android command

- ern-local-cli/src/index.js
Fixes https://github.com/electrode-io/electrode-native/issues/537
> Fix ern --version

- docs/cli/create-container.md
- docs/cli/publish-container.md
- ern-local-cli/src/commands/publish-container.js
Closes https://github.com/electrode-io/electrode-native/issues/535
> Add new command publish-container

- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-local-cli/src/lib/publication.js
Fixes https://github.com/electrode-io/electrode-native/issues/534
> Fix access to deprecated name property

- ern-container-gen/src/publishers/MavenPublisher.js
Closes https://github.com/electrode-io/electrode-native/issues/545
> Improve MavenPublisher local repository path resolution

- docs/overview/requirements.md
Close https://github.com/electrode-io/electrode-native/issues/553
> Add git as a requirement of Electrode Native

- ern-local-cli/src/lib/publication.js
- ern-local-cli/test/publication-test.js
Close https://github.com/electrode-io/electrode-native/issues/558
> Reverse precedence order of CodePush access key lookup

- ern-local-cli/scripts/postinstall.js
Close https://github.com/electrode-io/electrode-native/issues/554
> Throw error during Electrode Native install if git is not installed

- ern-core/src/MiniApp.js
- ern-core/src/compatibility.js
> cauldron update dependency command downgrades local native dependency version

- ern-core/src/compatibility.js
- ern-local-cli/src/lib/Ensure.js
- Fix `cauldron update miniapps` command
- Fix compatibility table display format
> Fix cauldron update miniapps

- README.md
- docs/README.md
add the walmartlabs electrode native case study
> add the walmartlabs electrode native case study

- docs/platform-parts/manifest.md
Close https://github.com/electrode-io/electrode-native/issues/605
> [documentation] remove internal link references from documenation.

- docs/cli/platform/use.md
Minor clarification that you don't need to run "ern platform install" by yourself
> Docs: Update ern platform use

- docs/cli/regen-api.md
Minor update, similar to "ern create-api" page
> Docs: Update regen-api.md

- ern-local-cli/src/commands/cauldron/add/publisher.js
Fixes https://github.com/electrode-io/electrode-native/issues/621
Thanks @inturbidus for reporting this issue
> change --gitHubUrl to --githubUrl

- system-tests-fixtures/android-container/build.gradle
- system-tests-fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeMiniAppActivity.java
- system-tests-fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
fix the system tests relating to container generation
> fix the system tests relating to container generation

- docs/cli/cauldron/repo/add.md
- ern-cauldron-api/src/BaseGit.js
- ern-core/src/utils.js
Closes https://github.com/electrode-io/electrode-native/issues/631
> Allow use of arbitrary branches for Cauldron

- package.json
- yarn-lock.js
- yarn.lock
Fixes https://github.com/electrode-io/electrode-native/issues/610
> Add pre-commit hook to ensure yarn.lock validity

- ern-container-gen/src/generators/android/hull/build.gradle
- system-tests-fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeMiniAppActivity.java
resolve white spaces in the system test fixtures
> resolve white spaces in the system test fixtures

- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/android/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- system-tests-fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
> Code push fails to install js bundle (android platform)

- global-cli/src/index.js
- Fix `isYarnInstalled` function on Windows (it was always throwing, thus leading in `isYarnInstalled` always returning `false` on Windows, even when yarn is properly installed).
- Fix cleanup of `.ern` directory on Windows in case Electrode Native installation fails (it was using linux/mac command `rm -rf` which does not exist on Windows).
> Fix some Windows specific bugs in global-cli

- ern-local-cli/src/commands/create-container.js
Was using in eternal code variable name instead of human understandable term
> Clarify error message

- ern-container-gen/src/generators/android/AndroidGenerator.js
- ern-container-gen/src/generators/ios/IosGenerator.js
- ern-container-gen/src/utils.js
Fixes https://github.com/electrode-io/electrode-native/issues/669
> Fix rnpm assets copy for iOS

- global-cli/src/index.js
If a local `.ernrc` file is present, use the platform version from this configuration file for first time install of Electrode Native, instead of the latest available version of Electrode Native.
Close https://github.com/electrode-io/electrode-native/issues/673
> Update global cli to support first time install of specific version instead of latest

- docs/cli/code-push.md
Fix JSON sample for code push configuration, which was deprecated.
> Fix CodePush documentation

- docs/cli/code-push.md
correct android syntax at initialize the Container with CodePush
> correct android syntax at initialize the Container with CodePush

- docs/cli/code-push/promote.md
- docs/cli/code-push/release.md
- ern-local-cli/src/commands/code-push/promote.js
- ern-local-cli/src/commands/code-push/release.js
- ern-local-cli/src/lib/publication.js
https://github.com/electrode-io/electrode-native/issues/711
> support --targetBinaryVersion option for code-push release & promote

- ern-container-gen/src/generators/ios/hull/ElectrodeContainer.xcodeproj/project.pbxproj
- ern-container-gen/src/generators/ios/hull/ElectrodeContainer/ElectrodeBridgeDelegate.h
- ern-container-gen/src/generators/ios/hull/ElectrodeContainer/ElectrodePluginConfig.h
- ern-container-gen/src/generators/ios/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen/src/generators/ios/hull/ElectrodeContainer/ElectrodeReactNative.m
Fix warnings inside ElectrodeContainer.
> Fix warning for ElectrodeContainer

- .vscode/settings.json
Improve development experience in Visual Studio Code by enabling CodeLens for TypeScript implementations. It makes it easy to see if an interface has implementations, and to navigate to the implementations conveniently.
**BEFORE**
**AFTER**
> Enable CodeLens for TypeScript implementations

- ern-api-gen/resources/swift/libraries/ern/api.mustache
- ern-api-gen/resources/swift/libraries/ern/apievents.mustache
- ern-api-gen/resources/swift/libraries/ern/apirequests.mustache
Add unregisterRequestHandler to API gen template
Add removeEventHandler to API gen template.
> add unregister/remove listener for api-gen

- README.md
- docs/overview/requirements.md
- docs/overview/what-is-ern.md
- docs/platform-parts/cli.md
- Update XCode version requirement to XCode 9.2+
- Update Node version requirement to Node 6+
> Update requirements in documentation

- ern-util-dev/bin/ern-mocha.js
- tsconfig.json
Adjust some of the TypeScript settings to make it work properly on Windows.
> Fix TypeScript compilation on Windows

- ern-core/src/MiniApp.ts
Fix https://github.com/electrode-io/electrode-native/issues/759
> Add .npmignore to MiniApps

- ern-api-impl-gen/package.json
- ern-container-gen/package.json
- ern-core/package.json
- yarn.lock
Bump `xcode-ern` dependency version from `1.0.1` to `^1.0.2`
> Bump xcode-ern dependency version

- ern-local-cli/src/commands/regen-api.ts
block user from passing invalid bridgeVersion
Enhances #793
> block user from passing invalid bridgeVersion

- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
> upgrade toplevel container with semver check

- docs/platform-parts/container.md
update docs with new android directives
> update docs with new android directives 

- ern-core/src/MiniApp.ts
Cleanup : This property is not used anymore.
> Remove isLocal property from MiniApp class

- ern-core/src/MiniApp.ts
[ern add] avoid adding transitive dependency 
Restrict `yarn add` for transitive native dependency
> [ern add] avoid adding transitive dependency 

- global-cli/src/index.js
> fixing string interpolation in global cli

- ern-container-publisher-maven/README.md
ern cauldron add publisher with well formed json string
> ern cauldron add publisher with well formed json string

- ern-local-cli/src/lib/utils.ts
Container transformers can now be specified in Container generator configuration as for publishers (will need to rework this at some point as this is not properly structured ... publishers and transformers config have nothing to do inside container generator config as they are fully decoupled. anyway..)
The transformers will be run sequentially in the order they appear in the `transformers` array.
Here is a simple Container generator configuration including a single transformer and a single publisher :
```javascript
"config": {
"containerGenerator": {
"containerVersion": "1.0.4",
"transformers": [
{
"name": "build-config@^1.0.0",
"extra": {
"configurations": ["ElectrodeContainer-Debug", "ElectrodeContainer-Release"],
"settings": {
"ENABLE_BITCODE": "NO"
}
}
}
],
"publishers": [
{
"extra": …
```
> Handle Container transformers configured in Cauldron

- ern-local-cli/src/commands/platform/plugins/search.ts
report platform version in error message if plugin not found
> report platform version in error message if plugin not found

- ern-container-publisher/src/getPublisher.ts
- ern-container-transformer/src/getTransformer.ts
Fix an identified bug that was not retrieving the proper latest version of a publisher / transformer matching a semver range, when one was provided.
For example if `git@^1.0.0` was used, and resolved as `1.0.1` during first use of the publisher, a newer published version of the publisher satisfying the semver range (for example `1.0.2`) would not be retrieved and installed upon next use of the publisher.
This was due to the fact that only `yarn add` was being used, which does not upgrade package versions when used with a version range, if a version satisfying the range is already installed (even if older).
Instead of relying solely on `yarn add`, this fixed code now also use `yarn upgrade`.
`yarn add` is used for first time install of a publisher/transformer (cannot use `yarn upgrade` in …
> Fix proper transformer/publisher version retrieval

- ern-core/src/Manifest.ts
> remove await from sync fnc

- docs/SUMMARY.md
- docs/cli/platform/versions.md
- docs/overview/upgrading-platform.md
- ern-local-cli/src/commands/platform/versions.ts
- system-tests/tests/misc.js
`ern platform list` > `ern platform versions` (feels more intuitive)
**For Release Notes : List in breaking changes**
> Rename platform list command to platform versions

- ern-local-cli/src/lib/constants.ts
- ern-local-cli/test/utils-test.js
white list overrideManifestUrlModifier platform config
> Whitelist overrideManifestUrlModifier config key

- docs/platform-parts/manifest/native-modules.md
- ern-container-gen-android/src/AndroidGenerator.ts
- ern-core/src/Manifest.ts
Fixes https://github.com/electrode-io/electrode-native/issues/885
> Allow injection of transitive dependencies in Android Container

- docs/getting-started/getting-started.md
Update dependencies versions to use for 0.24 release
> Update Getting Started guide for 0.24 release

- ern-local-cli/src/lib/Ensure.ts
- ern-local-cli/test/Ensure-test.js
- ern-local-cli/test/fixtures/common.js
Coverage of `Ensure` utility class should now be close to 100%
> Add more Ensure unit tests

- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
Follow up of https://github.com/electrode-io/electrode-native/pull/920
> Regenerate Android Container System Tests Fixture

- ern-container-gen/src/generateMiniAppsComposite.ts
- ern-container-gen/test/temp-test.ts
Update `.babelrc` presets of the Composite MiniApp to `['module:metro-react-native-babel-preset']` instead of `['react-native']` for proper support of React Native 0.57+. 
Without this, the metro bundler will fail creating the composite bundle when using React Native 0.57.
Reference : [Updating to React Native 0.57+](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#updating-to-this-version)
> Update Composite MiniApp generation for RN 0.57+

- ern-local-cli/src/commands/binarystore/get.ts
- ern-local-cli/src/commands/cauldron/add/nativeapp.ts
- ern-local-cli/src/commands/cauldron/config/get.ts
- ern-local-cli/src/commands/cauldron/repo/add.ts
- ern-local-cli/src/commands/cauldron/repo/current.ts
- ern-local-cli/src/commands/cauldron/update/file.ts
- ern-local-cli/src/commands/code-push/patch.ts
- ern-local-cli/src/commands/code-push/promote.ts
- ern-local-cli/src/commands/code-push/release.ts
- ern-local-cli/src/commands/create-api-impl.ts
- ern-local-cli/src/commands/create-api.ts
- ern-local-cli/src/commands/create-container.ts
- ern-local-cli/src/commands/create-miniapp.ts
- ern-local-cli/src/commands/platform/uninstall.ts
- ern-local-cli/src/commands/run-android.ts
- ern-local-cli/src/lib/askUserConfirmation.ts
- ern-local-cli/src/lib/askUserForCodePushLabel.ts
- ern-local-cli/src/lib/askUserToInputPackageName.ts
- ern-local-cli/src/lib/askUserToSelectAPlatform.ts
- ern-local-cli/src/lib/askUserToSelectAnEnvironment.ts
- ern-local-cli/src/lib/index.ts
- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
Removes some duplication and lightens command handlers.
> Extract user prompts to local cli lib

- system-tests/fixtures/ios-container/Config/ElectrodeContainer-Debug.xcconfig
- system-tests/fixtures/ios-container/Config/ElectrodeContainer-QADeployment.xcconfig
- system-tests/fixtures/ios-container/Config/ElectrodeContainer-Release.xcconfig
- system-tests/fixtures/ios-container/Config/ElectrodeContainerTests-Debug.xcconfig
- system-tests/fixtures/ios-container/Config/ElectrodeContainerTests-QADeployment.xcconfig
- system-tests/fixtures/ios-container/Config/ElectrodeContainerTests-Release.xcconfig
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
Follow up of https://github.com/electrode-io/electrode-native/pull/950 (forgot to regen iOS Container fixture in this PR)
> Regen iOS Container fixture

- ern-cauldron-api/src/BaseGit.ts
- ern-cauldron-api/test/BaseGit-test.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/fixtures/cauldron-0.0.0.json
- ern-cauldron-api/test/fixtures/cauldron-1.0.0.json
- ern-cauldron-api/test/upgrade-scripts-test.ts
- ern-core/package.json
- ern-core/src/GitManifest.ts
- ern-core/src/gitCli.ts
- ern-core/src/utils.ts
- ern-core/test/Utils-test.ts
- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
- yarn.lock
- Also make use of [simple-git/promise](https://github.com/steveukx/git-js#async-await-with-simple-gitpromise) rather than promisifying the `simple-git` library using bluebird. This is more direct and also it avoids having to prefix all git methods with `async`.
> Add more unit tests to ern-cauldron-api

- docs/cli/code-push/patch.md
- docs/cli/code-push/promote.md
- docs/cli/code-push/release.md
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/src/types/CauldronCodePushMetadata.ts
- ern-local-cli/src/commands/code-push/patch.ts
- ern-local-cli/src/commands/code-push/promote.ts
- ern-local-cli/src/commands/code-push/release.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/test/codepush-test.ts
add description option to code-push commands
- release
- patch
- promote
> add description option to code-push commands

- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
- ern-core/src/CodePushSdk.ts
- ern-core/test/CodePushSdk-test.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/test/codepush-test.ts
refactor definition of updateCodePushEntry to look consistent with addCodePushEntry, patch method to look consistent with promote and release
> refactor definition of updateCodePushEntry & patch method

- ern-api-impl-gen/hull/android/gradle.properties
- ern-container-gen-android/src/hull/gradle.properties
- ern-runner-gen-android/src/hull/gradle.properties
- ern-runner-gen-android/test/fixtures/simple-android-runner/gradle.properties
- system-tests/fixtures/android-container/gradle.properties
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/gradle.properties
> assign more heap to the jvm in gradle properties

- docs/cli/run-android.md
> document a note to state use name in mainMiniAppName property

- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/README.md
For https://github.com/electrode-io/electrode-native/pull/987
> Regenerate iOS Container system tests fixture

- docs/getting-started/getting-started.md
Just bump the version of `moviedetailsminiapp` to `0.0.23` as it contains the update to RN `0.57.5`
> Update getting started doc for 0.26 release

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/build.gradle
- ern-container-gen-android/src/hull/lib/build.gradle
- ern-container-gen/src/types/ContainerGeneratorConfig.ts
- ern-orchestrator/src/container.ts
- system-tests/fixtures/android-container/build.gradle
- system-tests/fixtures/android-container/lib/build.gradle
Add support to configure android build config
> Add support to configure android build config

- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
When performing a state update in Cauldron, if no MiniApps nor native dependencies have changed at all compared to previous Container version, then just re-publish the Container.
This optimization can be especially useful in a CI context, to 'promote' a Container (in that case just publishing a given Container version with a new version).
> Add optimization to perforContainerStateUpdateInCauldron

- ern-local-cli/src/commands/cauldron/update/miniapps.ts
When using `cauldron update miniapps` command, in the case of updating a branch of a MiniApp, but there is no changes to the head commit SHA (for example, updating a branch for a MiniApp from 'development' to 'release_123' and HEAD commit on both 'development' and 'release_123' is the same commit), then there is no need to retrieve the MiniApp to see if there was any native dependency changes, given that the MiniApp has not been updated, and does not contain any new code or dependencies. In that case, optimize to speed up the command and only consider MiniApps that have really been updated. For MiniApps where only the branch has been updated, take a fast path.
> Optimize cauldron update miniapps for git branches

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/gradle/wrapper/gradle-wrapper.properties
- system-tests/fixtures/android-container/gradle/wrapper/gradle-wrapper.properties
Add support for setting gradle distribution url
> Add support for setting gradle distribution url

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-core/src/android.ts
- ern-runner-gen-android/src/AndroidRunnerGenerator.ts
- ern-runner-gen-android/src/hull/app/build.gradle
- ern-runner-gen-android/src/hull/build.gradle
- ern-runner-gen-android/src/hull/gradle/wrapper/gradle-wrapper.properties
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/gradle/wrapper/gradle-wrapper.properties
align the runner gen android build config
> align the runner gen android build config 

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/lib/build.gradle
- ern-core/src/android.ts
- ern-runner-gen-android/src/AndroidRunnerGenerator.ts
- ern-runner-gen-android/src/hull/app/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/build.gradle
- system-tests/fixtures/android-container/lib/build.gradle
Configure support library version compatible with android build tools
> Configure support library version compatible with android build tools

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/lib/build.gradle
- ern-runner-gen-android/src/hull/app/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/app/build.gradle
- system-tests/fixtures/android-container/lib/build.gradle
replace build.gradle dependency with the new configuration directives #1023
https://developer.android.com/studio/build/dependencies?utm_source=android-studio#dependency_configurations
> replace build.gradle dependency with the new configuration directives

- package.json
- yarn.lock
https://github.com/Microsoft/TypeScript/releases
> Upgrade TypeScript to 3.2.2

- ern-orchestrator/src/performContainerStateUpdateInCauldron.ts
Even if only publishing, container transformers needs to be applied.
> Run container transformers even if only publishing

- ern-container-gen-android/src/AndroidGenerator.ts
- ern-container-gen-android/src/hull/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
Enable bridge logger for react native dev mode
> Enable bridge logger for react native dev mode

- global-cli/src/index.js
The process was exiting with a success code in case of failure ...
> Exit process with error code 1 on global cli failure

- docs/cli/platform/config/del.md
- docs/cli/platform/config/get.md
- docs/cli/platform/config/set.md
- ern-core/src/getCodePushInitConfig.ts
- ern-orchestrator/src/constants.ts
Fixes https://github.com/electrode-io/electrode-native/issues/1096
> Whitelist all available CodePush config keys

- .vscode/extensions.json
Update [deprecated TSLint](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) extension, with [new one](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) for workspace recommended Visual Studio Code extensions.
> Update deprecated vscode extension

- docs/cli/create-container.md
- ern-local-cli/src/commands/create-container.ts
Description in documentation file update.
> Add fromGitBranches flag to create-container command

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronApi-test.ts
Removing a lot of duplicated code
> Light refactoring of CauldronApi and CauldronHelper

- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/index.ts
- ern-orchestrator/test/codepush-test.ts
Fixes https://github.com/electrode-io/electrode-native/issues/1161
Also some quick refactoring to remove some duplication and split function in smaller ones easing unit testing.
> Fix trimZeroPatchDigit flag for pre release versions

- docs/cli/add.md
- docs/cli/upgrade-miniapp.md
- ern-core/src/BaseMiniApp.ts
- ern-core/src/MiniApp.ts
- ern-core/src/NpmCli.ts
- ern-core/src/PackageManager.ts
- ern-core/src/clients.ts
- ern-core/src/index.ts
Closes https://github.com/electrode-io/electrode-native/issues/1169
> Add a way to select package manager to use for MiniApps

- ern-core/src/android.ts
- ern-runner-gen-android/test/fixtures/simple-android-runner/build.gradle
- ern-runner-gen-android/test/fixtures/simple-android-runner/gradle/wrapper/gradle-wrapper.properties
> Bump default android versions

- ern-cauldron-api/src/CauldronApi.ts
Keep application versions sorted in Cauldron.
Due to the fact that Electrode Native allows non semver compliant versions in Cauldron (for example 'foo'), we need to sort the semver compliant versions separately from other non semver compliant versions. This is needed, because the `semver.compare` function throw an exception for non valid semver versions.
> Sort application versions in Cauldron

- ern-core/src/ReactNativeCli.ts
Tested on Linux and OSX as well
> Fix packager script for Windows

- ern-runner-gen-android/test/fixtures/simple-android-runner/build.gradle
Fixing https://github.com/electrode-io/electrode-native/pull/1212
> Regen Android Runner Generator test fixture

- ern-core/src/MiniApp.ts
Add double escaping to get proper escaping in written file.
> Fix metro.config.js

- azure-pipelines.yml
- azure/templates/system-tests.yml
Trigger it at 19:00 UTC for now for testing (12PM PST)
> Update Azure config to trigger daily builds

- ern-api-impl-gen/hull/android/build.gradle
- ern-api-impl-gen/hull/android/gradle/wrapper/gradle-wrapper.properties
- ern-api-impl-gen/hull/android/lib/build.gradle
- ern-api-impl-gen/src/generators/android/ApiImplAndroidGenerator.ts
- ern-core/src/android.ts
- ern-core/test/android-test.ts
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/build.gradle
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/gradle/wrapper/gradle-wrapper.properties
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/android/lib/build.gradle
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
This PR provides few improvements to the native api implementation project for android.
> Update gradle config for api-impl-native android.

- docs/platform-parts/composite/index.md
- ern-composite-gen/src/generateComposite.ts
- ern-composite-gen/src/types/CompositeGeneratorConfig.ts
- ern-composite-gen/test/compositegen-test.ts
- ern-container-gen/src/bundleMiniApps.ts
- ern-local-cli/src/commands/create-composite.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/composite.ts
- ern-orchestrator/src/container.ts
- ern-orchestrator/src/start.ts
Refer to new [Selective dependency resolutions support](https://github.com/electrode-io/electrode-native/blob/ccc21b293833e22593fe6ece5046ce63350593b6/docs/platform-parts/composite/index.md#selective-dependency-resolutions-support) in documentation for more details regarding this PR.
> Introduce composite selective dependencies resolution

- docs/cli/code-push/promote.md
- docs/cli/code-push/release.md
- ern-core/src/CodePushSdk.ts
- ern-local-cli/src/commands/code-push/promote.ts
- ern-local-cli/src/commands/code-push/release.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/test/codepush-test.ts
add noDuplicateReleaseError option to code push release and promote
Fixes #1230
> add noDuplicateReleaseError option to code push release and promote

- ern-composite-gen/src/generateComposite.ts
Fix an issue related to `.babelrc` proper resolution when using `ern start` with linked MiniApps.
Issue was due to `.babelrc` files from node modules to be processed when they shouldn't be.
For example, if a MiniApp `MiniAppA` is depending on a dependency, `DependencyA`, each of them having their own `.babelrc`, then the file structure would end up being something like this inside a composite :
```
.
├── index.js
├── node_modules
│   ├── DependencyA
│   │   ├── .babelrc
│   ├── MiniAppA
│   │   ├── .babelrc
```
However, using `ern start` with linked `MiniAppA`, the structure would look as follow, because we copy over the whole content of `MiniAppA` working directory to the `MiniAppA` directory in `node_modules` of composite:
```
.
├── index.js
├── node_modules
│   ├── MiniAppA
│   │   ├── …
```
> Fix ern start .babelrc resolution

- ern-api-impl-gen/resources/ios/apiController.mustache
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/APIImpls/MoviesApiController.swift
> Fix api controller instance

- ern-runner-gen-android/.npmignore
- ern-runner-gen-android/package.json
- ern-runner-gen-ios/package.json
> Remove leftover hullx remnants

- ern-composite-gen/src/generateComposite.ts
See comment in code for description.
> Patch metro BABEL_ENV resolution issue

- docs/cli/cauldron/regen-container.md
- docs/cli/code-push/release.md
- docs/cli/create-container.md
- ern-container-gen/src/generateContainer.ts
- ern-container-gen/src/types/ContainerGeneratorConfig.ts
- ern-local-cli/src/commands/cauldron/regen-container.ts
- ern-local-cli/src/commands/code-push/release.ts
- ern-local-cli/src/commands/create-container.ts
- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/container.ts
- ern-orchestrator/src/syncCauldronContainer.ts
Add sourceMapOutput option to the following commands
- create-container 
- cauldron regen-container
- code-push release
> Add sourceMapOutput option to some commands

- ern-api-gen/src/generateProject.ts
- ern-local-cli/src/commands/regen-api.ts
- system-tests/fixtures/api/ComplexApi/package.json
- system-tests/fixtures/api/TestApi/package.json
:bug: reset the schema path post API creation
Fixes #1327
> reset the schema path post api creation

- ern-api-gen/resources/swift/libraries/ern/api.mustache
- system-tests/fixtures/api/ComplexApi/IOS/SystemTestsAPI.swift
- system-tests/fixtures/api/TestApi/IOS/WalmartItemAPI.swift
add it back to fix the compiling issue
> missed `{` in api.mustache

- docs/cli/cauldron/update/miniapps.md
:books: fix the formatting of --targetVersion
> fix the formatting of --targetVersion in update miniapp command

- ern-container-gen-ios/src/hull/ElectrodeContainer.xcodeproj/project.pbxproj
- ern-container-gen-ios/src/hull/ElectrodeContainer/DevAssist/ERNDevSettingsViewController.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/DevAssist/ERNDevSettingsViewController.m
- ern-container-gen-ios/src/hull/ElectrodeContainer/DevAssist/ElectrodeBundle.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/DevAssist/ElectrodeBundle.m
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer/DevAssist/ERNDevSettingsViewController.h
- system-tests/fixtures/ios-container/ElectrodeContainer/DevAssist/ERNDevSettingsViewController.m
- system-tests/fixtures/ios-container/ElectrodeContainer/DevAssist/ElectrodeBundle.h
- system-tests/fixtures/ios-container/ElectrodeContainer/DevAssist/ElectrodeBundle.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
- Add bundle store support in iOS Container 🎉 
- Please refer https://github.com/electrode-io/electrode-native/pull/1304 to know more about Bundle Store 
-
> Add bundle store support for iOS

- docs/SUMMARY.md
- docs/guides/multi-miniapps-debug.md
Done upon request of internal team, but generic enough to be of use to anyone :)
> Add guide on debugging multiple miniapps

- ern-container-gen-ios/src/hull/ElectrodeContainer/DevAssist/ERNDevSettingsViewController.m
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer/DevAssist/ERNDevSettingsViewController.m
- Update bundle store URL for iOS.
- Default port number updated to `8080`
> Update bundle store url for iOS

- docs/platform-parts/container/container-integration.md
:books: fix typo and spacing in container doc
> fix spacing and amend the container documentation

- lerna.json
- package.json
- yarn.lock
Note: The `lerna` field is no longer in use: https://github.com/lerna/lerna#legacy-fields
> Update lerna to 3.18.1

- ern-api-gen/initialApiSchema.json
- ern-api-gen/src/Constants.ts
- ern-api-gen/src/generateProject.ts
read default schema from a file
> read default schema from a file

- package.json
- yarn.lock
Includes a couple of minor bugfixes, see [changelog](https://github.com/lerna/lerna/blob/master/CHANGELOG.md)
> Update lerna to 3.18.3

- system-tests/fixtures/constants.js
- system-tests/tests/create-api-base-fixture.js
- system-tests/tests/create-api-complex-fixture.js
- system-tests/tests/misc.js
Follow up to https://github.com/electrode-io/electrode-native/pull/1400
The system tests are unfortunately still failing :( This PR fixes the remaining issues.
System test run locally ✅
> Fix api generation system tests

- ern-orchestrator/src/start.ts
This PR is the port to master branch of https://github.com/electrode-io/electrode-native/pull/1411 (initially done directly on `v0.38` branch for `v0.38.8` hotfix release)
> Fix an issue with ern start command

- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/build.gradle
Missing in https://github.com/electrode-io/electrode-native/pull/1430
> Regenerate native api impl system test fixture

- ern-local-cli/src/index.ts
Running `ern --version` would fail with the following error, if `electrode-native` was installed using `yarn global add` (instead of `npm i -g`).
```
$ ern --version
[v1000.0.0] [Cauldron: -NONE-]
Error: Command failed: npm ls -g electrode-native --json
at checkExecSyncError (child_process.js:629:11)
at Object.execSync (child_process.js:666:13)
at showVersion (<dir>/ern-local-cli/src/index.ts:58:50)
at run (<dir>/ern-local-cli/src/index.ts:156:16)
at Object.<anonymous> (<dir>/ern-local-cli/src/index.ts:167:3)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Module.m._compile (<dir>/node_modules/ts-node/src/index.ts:536:23)
at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Object.require.extensions.(anonymous function) [as .ts] …
```
> Fix and update version cli command

- package.json
- yarn.lock
Two minor TypeScript related updates to `devDependencies`.
> Update ts-node and typescript

- ern-orchestrator/src/container.ts
Fix regression introduced in https://github.com/electrode-io/electrode-native/pull/1465
Fixes https://github.com/electrode-io/electrode-native/issues/1468
> Fix an issue impacting container gen

- ern-container-gen-android/src/AndroidGenerator.ts
Missed a crucial step in bundle source map generation when using Hermes engine.
The non-hermes JS bundle source map ('packager' one) needs to be combined with the Hermes one ('compiler' one) to obtain the final usable bundle source map, by running a react-native script.
This PR fixes this issue, so that we get proper source maps when using Hermes engine.
> Fix hermes source map generation

- ern-container-gen-ios/src/hull/ElectrodeContainer.xcodeproj/project.pbxproj
- ern-core/src/iosUtil.ts
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/container-metadata.json
Add support of new `addEmbeddedFramework` directive for configuration of iOS plugin injection.
> New addEmbeddedFramework directive for iOS plugins

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/ios/ElectrodeApiImpl.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer.xcodeproj/project.pbxproj
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
Need this to make sure we add ERN event listener after RCT bridge is ready
> add rctModuleDidInitialize delegate function

- docs/cli/platform/config/del.md
- docs/cli/platform/config/get.md
- docs/cli/platform/config/set.md
- ern-core/src/GitManifest.ts
- ern-core/src/LocalManifest.ts
- ern-core/src/Manifest.ts
- ern-local-cli/src/index.ts
- ern-orchestrator/src/constants.ts
Add support for local master / override manifests set through `.ernrc` configuration.
> Add support for local manifests

- docs/guides/multi-miniapps-debug.md
This is a full overhaul of the **Debugging Multiple MiniApps** guide. Many sections have been simplified, consolidated, and a few links were added. It also contains a bunch of other smaller corrections and additional information related to updated platform code. Those are the things I got stuck on when first working through it.
The updated Markdown file also had all whitespace errors fixed and is 100% markdownlint free.
> Update debugging guide

- ern-api-gen/README.md
Moved this commit over from #1420 for easier, more targeted review.
> Update README.md for ern-api-gen

- docs/platform-parts/composite/index.md
Add additional command to the list of commands supporting `--baseComposite` option.
> Update composite documentation

- yarn.lock
> Update https-proxy-agent to 2.2.4

- ern-local-cli/src/index.ts
Ensure that the Node version used to run `ern` is compatible with Node engine requirements of current `ern` version, otherwise exit the process.
This will avoid some bad surprise when not using a compatible node version, which might cause some `ern` command to behave incorrectly or crash.
This is needed because Iinstallation of an `ern` version and actual run of `ern` commands are decoupled in time, meaning that one could use Node 12 to install ern 0.41.0 for example, satisfying the requirement at the time of installation, but at the time of actually running an `ern` command, the node version might have been changed by the user, to an incompatible one.
> Exit process if Node version does not satisfy requirement

- ern-local-cli/package.json
- ern-orchestrator/package.json
- package.json
- yarn.lock
Also removed an unused (?) old dependency on `yargs` from `ern-orchestrator`.
> Update yargs to 15.3.1

- docs/platform-parts/container/container-initialization.md
- docs/platform-parts/container/container-integration.md
Added documentation for pain points discovered when integrating with container on iOS.
> Update iOS container init and integration docs

- ern-core/src/iosUtil.ts
Fix a bug introduced in recent refactoring of manifest directives around cocoapods support, leading to the following error when trying to generate a container using a version of react native less than 0.61.0.
```
✖ An error occurred: ENOENT: no such file or directory, open '/Users/blemair/.ern/containergen/out/ios/Podfile'
```
This was due to missing react native version conditional switches to evaluate manifest directives, leading to pod directives getting wrongly evaluated when using a version of react native less than 0.61.0 but also all other manifest directives not to be evaluated unless `requiresManualLinking` was set ... totally wrong :(
This fixes an issue present on dev platform only. No released versions are impacted.
Thanks @friederbluemle for catching this one :)
> Fix a bug generating pre rn61 ios containers

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
fix memory leak on registering UIFont
> fix memory leak on registering UIFont

- ern-composite-gen/src/generateComposite.ts
Some users reported failures with ERN 0.41 when trying to generate containers with one or more local miniapp(s) running a version of React Native < 0.60, leading to bundling errors such as `'Unable to resolve module [...]`.
This is due to the new mechanism introduced in ERN 0.41 to speedup composite generation when dealing with local MiniApp(s), only installing the dependencies that are required to be found at the root of the composite, react wasn't one of them (at least for RN >= 0.60), so ern is not installing it but instead pointing to its location in a local miniapp directory instead (to reduce generation time). 
For some reason, (probably haste related), with versions of React Native < 0.60.0, react dependency need to be present in the root bundling directory and cannot be located in …
> Fix an issue with local miniapps on RN<60

- ern-core/src/android.ts
show error message if no emulator is configured
> show error message if no emulator is configured

- ern-core/src/android.ts
- ern-core/test/android-test.ts
Fixes#https://github.com/electrode-io/electrode-native/issues/1489
> throw error if emulator fails to start

- ern-orchestrator/src/runMiniApp.ts
> remove unused variable

- ern-composite-gen/src/generateComposite.ts
Keep react in composite project root no matter what.
Electrode Native was only installing react in project root for versions of react native <= 0.60.0 as it is needed to have react in the root for these older versions of react native.
But we recently noticed an issue that is causing MiniApps using [react hooks](https://reactjs.org/docs/hooks-intro.html) to fail. After investigating the issue, it appears that react has to be kept in the project root for these guys to properly work.
This PR is also making sure to add the react dependencies kept inside the local MiniApps node modules, to the blacklist of metro config, to avoid running into haste duplication issues.
> Fix composite issue impacting react hooks

- global-cli/package.json
I think it's time for a new version and release of `global-cli` with the recent updates in #1645 and #1643 merged?
> global-cli: 1.1.0

- ern-cauldron-api/src/CauldronApi.ts
- ern-cauldron-api/src/CauldronHelper.ts
- ern-cauldron-api/test/CauldronApi-test.ts
- ern-cauldron-api/test/CauldronHelper-test.ts
Just some cleanup as this method is not used anymore at all.
> Remove CauldronApi unused method setYarnLockId

- ern-orchestrator/src/codepush.ts
- ern-orchestrator/src/syncCauldronContainer.ts
Port of https://github.com/electrode-io/electrode-native/pull/1632
> Do not upload sources to Bugsnag

- ern-core/src/HermesCli.ts
Starting with Hermes 0.5.0, the binary inside `hermes-engine` has been renamed from `hermes` to `hermesc`, causing Electrode Native to fail when trying to compile the bundle of a MiniApp using React Native 0.63.0, if Hermes engine is used.
This comes from the decision by Hermes team to split the `hermes-engine` package into two different packages, `hermes-engine-cli` and `hermes-engine` (see https://github.com/facebook/hermes/commit/284ae5e70d6bb2c7d98e859e74907c68ae6abae0).
The `hermes-engine-cli` still contains `hermes` binary, in addition to other binaries. The `hermes` binary can compile as well as run hermes bytecode. The `hermesc` binary is only the compiler (and this is the only binary in `hermes-engine`). 
Based on this, we had two choices. Either use `hermes-engine-cli` instead …
> Fix hermes binary name for hermes 0.5.0+

- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.h
- ern-container-gen-ios/src/hull/ElectrodeContainer/ElectrodeReactNative.m
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.h
- system-tests/fixtures/ios-container/ElectrodeContainer/ElectrodeReactNative.m
Add new init method to accept overlay option. Also some method name inconsistencies addressed. Helped method added for rootview color
> Add overlay option to miniapp view init method

- system-tests/fixtures/android-container/container-metadata.json
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeBridgeHolder.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeBridgeTransceiver.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeNativeBridge.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestHandlerHandle.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestHandlerProcessor.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestRegistrar.java
- system-tests/fixtures/android-container/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestRegistrarImpl.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeBridgeHolder.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeBridgeTransceiver.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeNativeBridge.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestHandlerHandle.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestHandlerProcessor.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestRegistrar.java
- system-tests/fixtures/api-impl-native/ern-movie-api-impl/android/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/RequestRegistrarImpl.java
- system-tests/fixtures/ios-container/container-metadata.json
- system-tests/fixtures/ios-container/package.json
> Regen fixtures

- ern-composite-gen/package.json
- package.json
- yarn.lock
This includes the `ini` update to 1.3.7
Closes #1748
> Update js-beautify to 1.13.0

- docs/platform-parts/manifest/native-modules.md
- ern-core/src/Manifest.ts
- ern-core/src/iosUtil.ts
Will update Podfile templates in master manifest accordingly and link PR
> Add new extraPodfileStatements manifest directive for iOS

- docs/platform-parts/container/container-integration.md
add documentation for proguarding the library module
> add documentation for proguarding the library module

- ern-composite-gen/src/patchMetroBabelRcRoots.ts
`metro-react-native-babel-transformer` dependency was [bumped to v0.64.0](https://github.com/facebook/react-native/blob/v0.64.0/package.json#L101) _(from v0.59.0)_ in  React Native 0.64.0.
Version 0.64.0 of `metro-react-native-babel-transformer` contains some code changes, causing Electrode Native to fail when trying to patch a source file from this library _(because the LOC to patch, doesn't exist anymore in this version)_. 
This causes issues for MiniApps relying on some babel plugins _(via `ern.useBabelRc` flag)_ as such babel plugins are now plainly ignored.
The fix is just to use a different patch in case the detected version of metro is >= 0.64.0 _(which is the case starting from React Native 0.64.0)_
> Fix babel support for RN 0.64+

- auto-rebuild.js
- regen-fixtures-check.js
- setup-dev.js
- typings/modules.d.ts
- yarn-lock-check.js
A quick formatting only PR that applies Prettier with default repo settings to the root level js scripts.
> Format root level js files

- ern-orchestrator/src/codepush.ts
- ern-orchestrator/test/codepush-test.ts
- ern-util-dev/fixtures/default-cauldron-fixture-custom-app-name.json
- ern-util-dev/src/index.js
Uses cauldron CodePush config app name when releasing to CodePush.
Fixes #1843
> Fix cauldron app name for releasing to codepush

- ern-core/src/Platform.ts
> Fix isYarnInstalled issue on Windows OS

- ern-container-gen/src/generateContainer.ts
> Fix relative path problem when creating container

- yarn.lock
Update the versions all dependencies in yarn.lock (within semver range, _not_ latest).
> Update dependencies (yarn.lock/semver)

- ern-core/src/MiniApp.ts
Fix logic error that prevented .npmignore from being created. Remove unnecessary files generated by later versions of RN.
> Update and fix files generated by create-miniapp
